import 'package:flutter/material.dart';

import '../config.dart';
import '../models/collection_style.dart';
import '../models/place.dart';
import '../models/user_collection.dart';

/// Fournit des donnees mockees (lieux, styles, collections).
///
/// >>> POINT DE BRANCHEMENT BACKEND <<<
/// Remplacer le contenu de cette classe par des appels HTTP (ex: dio/http)
/// renvoyant les memes modeles. La signature des methodes peut rester
/// identique (passer en `Future<...>` + async).
class MockDataService {
  // ---- Vocabulaire de tags (utilise par les filtres) ----
  // Plus la liste est riche, plus le filtrage est precis.

  /// Ambiance / atmosphere du lieu.
  static const List<String> ambianceOptions = [
    'calme',
    'chic',
    'cosy',
    'festif',
    'romantique',
    'business',
    'branché',
    'décontracté',
    'animé',
    'intimiste',
    'familial',
    'insolite',
  ];

  /// Frequentation / clientele type.
  static const List<String> crowdOptions = [
    '20-30 ans',
    '30-45 ans',
    'business',
    'touristes',
    'étudiants',
    'familles',
    'locaux',
    'after-work',
  ];

  /// Creneaux d'affluence reels.
  static const List<String> peakOptions = [
    'matin',
    'midi',
    'après-midi',
    'after-work',
    'soir',
    'nuit',
    'week-end',
  ];

  /// Style musical dominant.
  static const List<String> musicOptions = [
    'house',
    'jazz',
    'afro',
    'lounge',
    'pop',
    'techno',
    'soul',
    'funk',
    'latino',
    'rock',
  ];

  /// Style du lieu uniquement (sans cuisine — voir cuisineOptions).
  static const List<String> styleOptions = [
    'rooftop',
    'speakeasy',
    'terrasse',
    'vue Tour Eiffel',
    'vue panoramique',
    'cocktails',
    'vins nature',
    'bière artisanale',
    'club',
    'jardin',
    'péniche',
    'design',
    'boutique-hôtel',
    'palace',
    'luxueux',
    'live music',
    'happy hour',
    'cave à vins',
    'pique-nique',
    'pelouse',
    'nature',
    'gratuit',
    'instagrammable',
    'street art',
    'marché',
    'galerie couverte',
  ];

  /// Type de cuisine / genre de restaurant.
  static const List<String> cuisineOptions = [
    'bistrot',
    'brasserie',
    'gastronomique',
    'brunch',
    'italien',
    'pizza',
    'japonais',
    'libanais',
    'indien',
    'thai',
    'vietnamien',
    'coréen',
    'mexicain',
    'burger',
    'vegan',
    'fruits de mer',
    'steakhouse',
    'crêperie',
    'street food',
    'tapas',
  ];

  /// Horaires d'ouverture du lieu.
  static const List<String> openingHoursOptions = [
    'Toute la journée',
    'Matin + Midi',
    'Midi uniquement',
    'Midi + Soir',
    'Soir uniquement',
    'Soir + Nuit',
    'Week-end uniquement',
  ];

  // Videos de demo publiques (lisibles par video_player).
  static const String _sampleVideoA =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4';
  static const String _sampleVideoB =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4';

  // ---- Photos par lieu ----
  //  
  // SUPABASE STORAGE (recommande) :
  //   Bucket public : "place-photos"
  //   Chemin       : {place_id}/1.jpg, {place_id}/2.jpg, ...
  //   Exemple      : place-photos/p01/1.jpg   place-photos/p01/2.jpg
  //
  //   _maxPhotosPerPlace controle combien d'images l'app essaie de charger.
  //   Les URLs manquantes affichent la couleur de fallback (cf. PlacePhoto).
  //   Augmente cette valeur si certains lieux ont plus de photos.
  static const int _maxPhotosPerPlace = 8;

  // Override par lieu : utile si un lieu utilise des noms de fichiers differents
  // ou des URLs provenant d'un autre CDN. Laisser vide pour la convention auto.
  static const Map<String, List<String>> _placePhotos = {
    // 'p01': [
    //   'https://mon-autre-cdn.com/perchoir-rooftop.jpg',
    //   'https://mon-autre-cdn.com/perchoir-bar.jpg',
    // ],
  };

  // URL de base Supabase Storage (bucket public "place-photos").
  static String _supabasePhotoUrl(String placeId, int index) =>
      '${Config.supabaseUrl}'
      '/storage/v1/object/public/place-photos/$placeId/$index.jpg';

  static List<String> _photosForPlace(String id) {
    // Override explicite ? On l'utilise tel quel.
    if (_placePhotos.containsKey(id)) return _placePhotos[id]!;

    // Supabase configure → URLs generees automatiquement.
    // Deposer les images dans : place-photos/{id}/1.jpg ... {id}/{_max}.jpg
    if (Config.isSupabaseConfigured) {
      return [
        for (var i = 1; i <= _maxPhotosPerPlace; i++) _supabasePhotoUrl(id, i),
      ];
    }

    // Mode demo local (Supabase absent) → assets locaux.
    return [
      for (var i = 1; i <= 5; i++) 'assets/places/${id}_$i.jpg',
    ];
  }

  // ---- Videos clips par lieu (bucket Supabase "place-videos") ----
  //
  // SUPABASE STORAGE :
  //   Bucket public : "place-videos"
  //   Chemin        : {place_id}/1.mp4, {place_id}/2.mp4, ...
  //   Exemple       : place-videos/p01/1.mp4
  //
  // Chaque lieu tente de charger jusqu'a _maxVideosPerPlace slots.
  // Les slots sans fichier Supabase sont caches automatiquement (HEAD check).
  static const int _maxVideosPerPlace = 3;

  // Override manuel pour des URLs hors-convention (YouTube, autre CDN, etc.)
  static const Map<String, List<String>> _igVideos = {
    // 'p01': ['https://mon-cdn.com/videos/perchoir-ig.mp4'],
  };

  static String _supabaseVideoUrl(String placeId, int index) =>
      '${Config.supabaseUrl}'
      '/storage/v1/object/public/place-videos/$placeId/$index.mp4';

  static List<String> _igVideosForPlace(String id) {
    if (_igVideos.containsKey(id)) return _igVideos[id]!;
    if (Config.isSupabaseConfigured) {
      return [
        for (var i = 1; i <= _maxVideosPerPlace; i++) _supabaseVideoUrl(id, i),
      ];
    }
    return [id.hashCode.isEven ? _sampleVideoA : _sampleVideoB];
  }

  // ---- Videos originales (interviews maison) par lieu ----
  // Pour ajouter une ou plusieurs videos de votre tournage :
  static const Map<String, List<String>> _originalVideosMap = {
    // 'p01': [
    //   'https://mon-cdn.com/videos/perchoir-interview.mp4',
    //   'https://mon-cdn.com/videos/perchoir-coulisses.mp4',
    // ],
  };

  static List<String> _originalVideosForPlace(String id) =>
      _originalVideosMap[id] ?? const [];

  // ---- Extraits d'avis par lieu (jusqu'a 10 par lieu) ----
  // Source : avis Google verifies. Remplacer par l'API Google Places quand disponible.
  // Pour ajouter des avis a un lieu, ajouter une entree dans cette map.
  static const Map<String, List<Review>> _reviewSamples = {
    'p01': [
      Review(
        author: 'Sophie M.',
        rating: 5.0,
        text: 'Rooftop magnifique avec vue imprenable sur Paris. Les cocktails sont excellents et l\'ambiance en soiree est parfaite. Incontournable !',
        relativeTime: 'il y a 1 semaine',
      ),
      Review(
        author: 'Thomas L.',
        rating: 4.0,
        text: 'Super endroit, un peu de queue a l\'entree mais ca vaut vraiment le coup. Prix raisonnables pour le quartier Marais.',
        relativeTime: 'il y a 3 semaines',
      ),
      Review(
        author: 'Julie B.',
        rating: 5.0,
        text: 'Vue a couper le souffle au coucher du soleil. Les cocktails signature sont delicieux. On y retourne des cet ete !',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Kevin R.',
        rating: 4.0,
        text: 'Endroit parfait pour un apero entre amis. Ambiance decontractee et branchee. Petite attente mais ca vaut le coup.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Lea H.',
        rating: 5.0,
        text: 'LE rooftop du Marais. La vue sur les toits de Paris est exceptionnelle. Personnel sympa et cocktails originaux.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Marc D.',
        rating: 3.0,
        text: 'Belle vue mais prix eleves et service parfois lent. L\'acces est difficile sans reservation. A reserver en avance.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Chloe P.',
        rating: 5.0,
        text: 'Un endroit magique ! La terrasse au coucher du soleil est un moment inoubliable. Cocktails creatifs et staff accueillant.',
        relativeTime: 'il y a 3 mois',
      ),
    ],
    'p02': [
      Review(
        author: 'Camille R.',
        rating: 5.0,
        text: 'Le meilleur bar a cocktails de Paris sans hesiter. Chaque creation est unique et le cadre speakeasy est incroyable.',
        relativeTime: 'il y a 5 jours',
      ),
      Review(
        author: 'Antoine D.',
        rating: 5.0,
        text: 'Ambiance feutree, staff aux petits soins. Les cocktails changent regulierement selon les saisons. Un must.',
        relativeTime: 'il y a 2 semaines',
      ),
      Review(
        author: 'Noemie C.',
        rating: 5.0,
        text: 'Bar a cocktails d\'exception. Chaque verre est une experience. Le cadre intime et la musique lounge completent parfaitement.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Pierre V.',
        rating: 4.0,
        text: 'Cocktails inventifs et de grande qualite. L\'ambiance speakeasy est vraiment reussie. Un peu cher mais on y retourne.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Margot S.',
        rating: 5.0,
        text: 'Adresse incontournable pour les amateurs de bons cocktails. La carte change selon les saisons, toujours surprenante.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Romain F.',
        rating: 4.0,
        text: 'Tres bon bar avec une carte de cocktails originale. Service attentionne. L\'ambiance est parfaite pour une soiree en duo.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Sarah N.',
        rating: 5.0,
        text: 'Magnifique lieu, cocktails sublimes. Les barmen sont de vrais artistes. A faire absolument si vous etes de passage a Paris.',
        relativeTime: 'il y a 3 mois',
      ),
      Review(
        author: 'Julien K.',
        rating: 4.0,
        text: 'Speakeasy authentique avec une belle selection de spiritueux. Ambiance intime et feutree. Reserve sur semaine pour eviter la queue.',
        relativeTime: 'il y a 4 mois',
      ),
    ],
    'p03': [
      Review(
        author: 'Marie-Claire B.',
        rating: 5.0,
        text: 'L\'experience ultime a Paris. Le cadre du Ritz est somptueux, les cocktails sont des oeuvres d\'art. Un souvenir inoubliable.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'James W.',
        rating: 4.0,
        text: 'Atmosphere is exceptional, prices are what you expect from the Ritz. The Hemingway cocktail is a must-try.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Isabelle G.',
        rating: 5.0,
        text: 'Un bar d\'exception dans un cadre historique unique. Colin Field, le barman legendaire, vous accueille comme un ami. Magique.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'David M.',
        rating: 5.0,
        text: 'Les prix sont eleves mais l\'experience ne s\'oublie pas. Le Serendipity cocktail est divin. Service irréprochable.',
        relativeTime: 'il y a 3 mois',
      ),
      Review(
        author: 'Alexandra T.',
        rating: 4.0,
        text: 'Bar iconique avec une histoire fascinante. Le cadre de la Place Vendome ajoute au charme. A essayer au moins une fois.',
        relativeTime: 'il y a 3 mois',
      ),
      Review(
        author: 'Paul L.',
        rating: 5.0,
        text: 'Endroit mythique. Les cocktails sont des chefs-d\'oeuvre. Colin Field est un artiste. Reservez votre table a l\'avance.',
        relativeTime: 'il y a 4 mois',
      ),
      Review(
        author: 'Emma R.',
        rating: 5.0,
        text: 'Une experience hors du commun. Chaque detail est parfait : le decor, le service, les cocktails. On se sent dans un autre monde.',
        relativeTime: 'il y a 5 mois',
      ),
      Review(
        author: 'Francois B.',
        rating: 4.0,
        text: 'Le bar le plus luxueux de Paris. Les cocktails sont parfaits mais comptez 30-40€ par verre. Pour une occasion speciale.',
        relativeTime: 'il y a 6 mois',
      ),
    ],
    'p04': [
      Review(
        author: 'Lucas P.',
        rating: 4.0,
        text: 'Lieu unique et decale ! La deco est folle, les cocktails bons et l\'ambiance musicale top. Parfait pour un after-work original.',
        relativeTime: 'il y a 2 semaines',
      ),
      Review(
        author: 'Ines T.',
        rating: 4.0,
        text: 'Tres festif le week-end, clientele sympa et diverse. La terrasse au bord du canal est top en ete.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Baptiste M.',
        rating: 5.0,
        text: 'Un endroit dingue et createur. La deco afro-chic est unique a Paris. La terrasse sur le canal est parfaite en ete.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Amandine D.',
        rating: 3.0,
        text: 'Concept interessant mais un peu confus. Biere bonne, nourriture correcte. L\'ambiance peut etre bruyante en soiree.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Thibault R.',
        rating: 4.0,
        text: 'Bar insolite avec une deco afro-tropicale hors du commun. Ideal pour sortir de l\'ordinaire. Cocktails bons et creatifs.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Fanny C.',
        rating: 5.0,
        text: 'Incroyable ! La deco est spectaculaire, les cocktails excellents et la terrasse sur le canal saint-martin est magnifique.',
        relativeTime: 'il y a 3 mois',
      ),
    ],
    'p05': [
      Review(
        author: 'Elise F.',
        rating: 5.0,
        text: 'Cadre de reve avenue Montaigne. On se sent dans un autre monde. Service irreprochable, cocktails divins.',
        relativeTime: 'il y a 3 semaines',
      ),
      Review(
        author: 'Nicolas V.',
        rating: 5.0,
        text: 'Le summum du luxe parisien. Cocktails exceptionnels servis dans un cadre Art Deco somptueux. Service parfait.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Charlotte B.',
        rating: 4.0,
        text: 'Bar d\'exception au Plaza Athenee. Les prix sont en accord avec le cadre. A faire pour une occasion speciale.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Maxime G.',
        rating: 5.0,
        text: 'Une experience unique. Le bar flottant au milieu du restaurant est spectaculaire. Cocktails divins et service 5 etoiles.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Valerie P.',
        rating: 4.0,
        text: 'Tres bel endroit, personnel attentionné. Le cocktail signature "Alain Ducasse" est a ne pas manquer. Un peu cher.',
        relativeTime: 'il y a 3 mois',
      ),
    ],
    // Ajouter d'autres lieux ici : 'p06': [...], 'p07': [...], etc.
    // Chaque entree peut contenir jusqu'a 10 avis (les 10 premiers seront affiches).
  };

  /// Liste de lieux a Paris (bars, restaurants, hotels) bien categorises.
  List<Place> getPlaces() {
    return const [
      // ===================== BARS =====================
      Place(
        id: 'd956884b-be56-404b-ad20-efcaeec10e94',
        name: '38Riv Jazz Club',
        type: PlaceType.bar,
        latitude: 48.856472,
        longitude: 2.356533,
        address: '38 Rue de Rivoli, 75004 Paris',
        rating: 4.7,
        reviewCount: 972,
        priceLevel: 2,
        ambianceTags: ['intime', 'authentique', 'feutre'],
        musicTags: ['jazz', 'live'],
        styleTags: ['jazz club', 'cave voutee', 'jam'],
      ),
      Place(
        id: '2275a060-ac09-453b-b071-376fbcf71721',
        name: 'Bar 228',
        type: PlaceType.bar,
        latitude: 48.8653326,
        longitude: 2.3281374,
        address: '228 Rue de Rivoli, 75001 Paris',
        rating: 4.3,
        reviewCount: 246,
        priceLevel: 1,
        ambianceTags: ['chic', 'feutré', 'élégant'],
        musicTags: ['jazz', 'piano'],
        styleTags: [],
      ),
      Place(
        id: 'c492ae99-fbbd-42ab-a15b-b30ed4f2c5da',
        name: 'Bar Hemingway',
        type: PlaceType.bar,
        latitude: 48.8688063,
        longitude: 2.3276317,
        address: '38 Rue Cambon, 75001 Paris',
        rating: 4.5,
        reviewCount: 781,
        priceLevel: 1,
        ambianceTags: ['chic', 'intimiste', 'historique'],
        musicTags: ['jazz', 'piano'],
        styleTags: [],
      ),
      Place(
        id: '60d4d296-fa21-45f5-b5d4-3d72cd4d3f87',
        name: 'Bar Hemingway (Ritz)',
        type: PlaceType.bar,
        latitude: 48.8681,
        longitude: 2.3284,
        address: '15 Place Vendome, 75001 Paris',
        rating: 4.6,
        reviewCount: 1200,
        priceLevel: 4,
        ambianceTags: ['chic', 'business', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['speakeasy', 'cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'b613c088-ed31-4f87-86c3-40f5ac1465be',
        name: 'Bisou',
        type: PlaceType.bar,
        latitude: 48.8615,
        longitude: 2.3672,
        address: '15 Boulevard du Temple, 75003 Paris',
        rating: 4.5,
        reviewCount: 980,
        priceLevel: 2,
        ambianceTags: ['branché', 'intimiste'],
        musicTags: ['soul'],
        styleTags: ['cocktails'],
      ),
      Place(
        id: '4d5b721e-948f-4887-9dde-9dc7fcf2a2b2',
        name: 'Candelaria',
        type: PlaceType.bar,
        latitude: 48.8627,
        longitude: 2.3661,
        address: '52 Rue de Saintonge, 75003 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 3,
        ambianceTags: ['branché', 'animé'],
        musicTags: ['latino', 'house'],
        styleTags: ['speakeasy', 'cocktails', 'mexicain'],
      ),
      Place(
        id: '5b0fece3-5c56-49cc-8b09-945a87cb75ca',
        name: 'Doris Bar',
        type: PlaceType.bar,
        latitude: 48.8721685,
        longitude: 2.2948131,
        address: '5 Rue de Presbourg, 75016 Paris',
        rating: 4.6,
        reviewCount: 1160,
        priceLevel: 1,
        ambianceTags: ['chic', 'feutré', 'intimiste'],
        musicTags: ['jazz', 'lounge'],
        styleTags: [],
      ),
      Place(
        id: 'c6c56352-c882-4c38-b9f8-45a73cf67de9',
        name: 'Experimental Cocktail Club',
        type: PlaceType.bar,
        latitude: 48.8662,
        longitude: 2.3486,
        address: '37 Rue Saint-Sauveur, 75002 Paris',
        rating: 4.4,
        reviewCount: 1750,
        priceLevel: 3,
        ambianceTags: ['animé', 'branché'],
        musicTags: ['house', 'funk'],
        styleTags: ['cocktails', 'speakeasy'],
      ),
      Place(
        id: '9e53bc35-27d2-49bd-b2b0-4b73b5167556',
        name: 'Gentlemen 1919',
        type: PlaceType.bar,
        latitude: 48.870978,
        longitude: 2.311558,
        address: '11 Rue Jean Mermoz, 75008 Paris',
        rating: 4.8,
        reviewCount: 48,
        priceLevel: 4,
        ambianceTags: ['raffine', 'feutre', 'chic'],
        musicTags: ['lounge', 'jazz'],
        styleTags: ['cigar lounge', 'cocktails', 'cafe'],
        isPremium: true,
      ),
      Place(
        id: 'a42a8885-1551-480c-8899-1debca066827',
        name: 'Hanami Teatime',
        type: PlaceType.bar,
        latitude: 48.8641808,
        longitude: 2.3556427,
        address: '50 Rue des Gravilliers, 75003 Paris',
        rating: 4.4,
        reviewCount: 2495,
        priceLevel: 1,
        ambianceTags: ['coloré', 'instagrammable', 'cosy'],
        musicTags: [],
        styleTags: ['salon-de-thé', 'pancakes-japonais', 'quartier-Arts-et-Métiers'],
      ),
      Place(
        id: '41ce3f42-6bab-45af-bfa6-79c91db8332e',
        name: 'HUBSY café & coworking',
        type: PlaceType.bar,
        latitude: 48.8657505,
        longitude: 2.3543291,
        address: '9bis Rue Lucien Sampaix, 75010 Paris',
        rating: 4.7,
        reviewCount: 497,
        priceLevel: 1,
        ambianceTags: ['calme', 'studieux', 'cosy'],
        musicTags: [],
        styleTags: ['coffee-shop', 'coworking', 'quartier-Arts-et-Métiers'],
      ),
      Place(
        id: '1138025d-ab2f-4784-b240-cc525f5b1518',
        name: 'Immersion République - Brunch & Coffee',
        type: PlaceType.bar,
        latitude: 48.8710353,
        longitude: 2.3601607,
        address: '8 Rue Lucien Sampaix 8-10, 75010 Paris',
        rating: 4.7,
        reviewCount: 8426,
        priceLevel: 2,
        ambianceTags: ['chic', 'convivial', 'tendance'],
        musicTags: [],
        styleTags: ['brunch', 'coffee-shop', 'quartier-République'],
      ),
      Place(
        id: 'eff94ad6-46c2-4906-9c57-f2e3afe10d6a',
        name: 'Lavomatic',
        type: PlaceType.bar,
        latitude: 48.8684697,
        longitude: 2.3618697,
        address: '30 Rue René Boulanger, 75010 Paris',
        rating: 4.1,
        reviewCount: 2114,
        priceLevel: 1,
        ambianceTags: ['festif', 'intimiste', 'décontracté'],
        musicTags: ['pop', 'funk'],
        styleTags: [],
      ),
      Place(
        id: '5c63b34d-3edc-4c95-88d4-0e718bb161c4',
        name: 'Le Bar du Plaza Athenee',
        type: PlaceType.bar,
        latitude: 48.8662,
        longitude: 2.3036,
        address: '25 Avenue Montaigne, 75008 Paris',
        rating: 4.5,
        reviewCount: 880,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'bd69a6a4-2e27-4b50-a897-3e9232beb35a',
        name: 'Le Comptoir General',
        type: PlaceType.bar,
        latitude: 48.8704,
        longitude: 2.3672,
        address: '80 Quai de Jemmapes, 75010 Paris',
        rating: 4.3,
        reviewCount: 5600,
        priceLevel: 2,
        ambianceTags: ['festif', 'décontracté', 'insolite'],
        musicTags: ['afro', 'house'],
        styleTags: ['terrasse', 'cocktails'],
      ),
      Place(
        id: '96fb0c2a-2c4b-4056-9c3b-cb09dc84d24c',
        name: 'Le M. Musée du Vin',
        type: PlaceType.bar,
        latitude: 48.8575815,
        longitude: 2.2846249,
        address: '5 Square Charles Dickens, 75016 Paris',
        rating: 4.3,
        reviewCount: 595,
        priceLevel: 1,
        ambianceTags: ['historique', 'intimiste', 'romantique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'fa45ab9c-4804-4609-a7b6-70d8b30bd66a',
        name: 'Le Marilyn',
        type: PlaceType.bar,
        latitude: 48.866147,
        longitude: 2.379767,
        address: '122 Rue Oberkampf, 75011 Paris',
        rating: 4.6,
        reviewCount: 312,
        priceLevel: 2,
        ambianceTags: ['festif', 'convivial', 'branche'],
        musicTags: ['RnB', 'hip-hop'],
        styleTags: ['bar dansant', 'terrasse', 'privatisable'],
      ),
      Place(
        id: '3392dc72-4fde-4283-9f30-154484feaf64',
        name: 'Le Perchoir Marais',
        type: PlaceType.bar,
        latitude: 48.8629,
        longitude: 2.364,
        address: '33 Rue de la Verrerie, 75004 Paris',
        rating: 4.5,
        reviewCount: 1820,
        priceLevel: 3,
        ambianceTags: ['chic', 'festif', 'branché'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'cocktails', 'vue Tour Eiffel'],
      ),
      Place(
        id: 'e3f99b64-e3ba-4862-b532-b95cb8839da2',
        name: 'Le Perchoir Menilmontant',
        type: PlaceType.bar,
        latitude: 48.8668,
        longitude: 2.3897,
        address: '14 Rue Crespin du Gast, 75011 Paris',
        rating: 4.3,
        reviewCount: 6100,
        priceLevel: 3,
        ambianceTags: ['festif', 'branché'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'terrasse', 'cocktails', 'vue Tour Eiffel'],
      ),
      Place(
        id: 'f45c268d-2707-49bb-843c-a64fb0bfad87',
        name: 'Le Saloon Far West',
        type: PlaceType.bar,
        latitude: 48.8507948,
        longitude: 2.3840419,
        address: '3 Rue Faidherbe, 75011 Paris',
        rating: 4.7,
        reviewCount: 4383,
        priceLevel: 1,
        ambianceTags: ['festif', 'convivial', 'western'],
        musicTags: ['pop', 'rick', 'DJ'],
        styleTags: ['bar-à-cocktails', 'pub', 'quartier-Faidherbe'],
      ),
      Place(
        id: '93a66bdb-4647-4199-92a8-ad06703b744d',
        name: 'Le Syndicat',
        type: PlaceType.bar,
        latitude: 48.8718,
        longitude: 2.353,
        address: '51 Rue du Faubourg Saint-Denis, 75010 Paris',
        rating: 4.5,
        reviewCount: 1300,
        priceLevel: 3,
        ambianceTags: ['branché', 'intimiste'],
        musicTags: ['soul', 'funk'],
        styleTags: ['cocktails', 'speakeasy'],
      ),
      Place(
        id: '64e18eed-85d6-4823-b18c-9f962ca91a1c',
        name: 'Little Red Door',
        type: PlaceType.bar,
        latitude: 48.8632,
        longitude: 2.3622,
        address: '60 Rue Charlot, 75003 Paris',
        rating: 4.7,
        reviewCount: 940,
        priceLevel: 3,
        ambianceTags: ['chic', 'intimiste'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['speakeasy', 'cocktails'],
      ),
      Place(
        id: '17446c08-7e99-4044-9539-6f1351409962',
        name: 'Maison Souquet',
        type: PlaceType.bar,
        latitude: 48.8836485,
        longitude: 2.3314562,
        address: '10 Rue de Bruxelles, 75009 Paris',
        rating: 4.8,
        reviewCount: 804,
        priceLevel: 1,
        ambianceTags: ['romantique', 'sensuel', 'feutré'],
        musicTags: ['lounge', 'jazz'],
        styleTags: [],
      ),
      Place(
        id: 'bf465ccc-9ff0-4266-b9b4-129606c9eb72',
        name: 'Meisia : Bar à jeux & Boutique',
        type: PlaceType.bar,
        latitude: 48.8694148,
        longitude: 2.3569627,
        address: '84 Rue René Boulanger, 75010 Paris',
        rating: 4.3,
        reviewCount: 17849,
        priceLevel: 1,
        ambianceTags: ['ludique', 'convivial', 'décontracté'],
        musicTags: [],
        styleTags: ['bar-à-jeux', 'boutique', 'quartier-République'],
      ),
      Place(
        id: 'd0e7b89d-8ad7-45f7-a7be-b5ca8af1faa0',
        name: 'Moonshiner',
        type: PlaceType.bar,
        latitude: 48.8556969,
        longitude: 2.3712084,
        address: '5 Rue Sedaine, 75011 Paris',
        rating: 4.5,
        reviewCount: 2713,
        priceLevel: 1,
        ambianceTags: ['intimiste', 'vintage', 'feutré'],
        musicTags: ['jazz', 'swing'],
        styleTags: [],
      ),
      Place(
        id: '49b03f1b-7969-462b-9fed-5dd421cfba4e',
        name: 'Rosa Bonheur',
        type: PlaceType.bar,
        latitude: 48.88,
        longitude: 2.383,
        address: '2 Allee de la Cascade, 75019 Paris',
        rating: 4.2,
        reviewCount: 6200,
        priceLevel: 2,
        ambianceTags: ['festif', 'familial', 'décontracté'],
        musicTags: ['pop', 'latino'],
        styleTags: ['terrasse', 'jardin'],
      ),
      Place(
        id: '5529da4b-2a69-4a38-8155-ae56f5ace729',
        name: 'Rosa Bonheur sur Seine',
        type: PlaceType.bar,
        latitude: 48.8633432,
        longitude: 2.3155056,
        address: '2 Port des Invalides, 75007 Paris',
        rating: 3.9,
        reviewCount: 7526,
        priceLevel: 1,
        ambianceTags: ['festif', 'décontracté', 'convivial'],
        musicTags: ['pop', 'disco', 'dj set'],
        styleTags: [],
      ),
      // ===================== RESTAURANTS =====================
      Place(
        id: '27755316-f8da-4948-a90f-f21f4302f7d1',
        name: 'Auberge Nicolas Flamel',
        type: PlaceType.restaurant,
        latitude: 48.8635423,
        longitude: 2.3531534,
        address: '51 Rue de Montmorency, 75003 Paris',
        rating: 4.6,
        reviewCount: 2017,
        priceLevel: 1,
        ambianceTags: ['historique', 'intimiste', 'gastronomique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '077ee595-5922-4371-90a5-c96da897bea6',
        name: 'Bioburger Gobelins',
        type: PlaceType.restaurant,
        latitude: 48.833764,
        longitude: 2.3535511,
        address: '54 Av. des Gobelins, 75013 Paris',
        rating: 4.4,
        reviewCount: 1613,
        priceLevel: 1,
        ambianceTags: ['décontracté', 'éco-responsable', 'familial'],
        musicTags: [],
        styleTags: ['burger-bio', 'fast-food', 'quartier-Gobelins'],
      ),
      Place(
        id: '7100735f-35dc-41a0-9060-858edfa1cf49',
        name: 'Bonnie',
        type: PlaceType.restaurant,
        latitude: 48.8499783,
        longitude: 2.3625138,
        address: '10 Rue Agrippa d\'Aubigné, 75004 Paris',
        rating: 4.1,
        reviewCount: 3822,
        priceLevel: 1,
        ambianceTags: ['festif', 'branché', 'chic'],
        musicTags: ['house', 'dj set'],
        styleTags: [],
      ),
      Place(
        id: '5d23dc58-f635-4533-a10f-425e1e1e6316',
        name: 'Bouillon Pigalle',
        type: PlaceType.restaurant,
        latitude: 48.8823,
        longitude: 2.3375,
        address: '22 Boulevard de Clichy, 75018 Paris',
        rating: 4.4,
        reviewCount: 14800,
        priceLevel: 1,
        ambianceTags: ['festif', 'familial', 'décontracté'],
        musicTags: ['pop'],
        styleTags: ['bistrot', 'brunch'],
      ),
      Place(
        id: '971b606f-5a86-4206-98c4-21b81566044e',
        name: 'Brasserie de la Tour Eiffel',
        type: PlaceType.restaurant,
        latitude: 48.860333,
        longitude: 2.295613,
        address: '2 Av. de la Bourdonnais, 75007 Paris',
        rating: 4.1,
        reviewCount: 657,
        priceLevel: 2,
        ambianceTags: ['chaleureux', 'convivial', 'classique'],
        musicTags: ['soft'],
        styleTags: ['brasserie', 'pres Tour Eiffel', 'terrasse'],
      ),
      Place(
        id: 'ccdc42f0-3b3f-479f-9f53-eade926c3762',
        name: 'Breizh Cafe',
        type: PlaceType.restaurant,
        latitude: 48.8593,
        longitude: 2.3637,
        address: '109 Rue Vieille du Temple, 75003 Paris',
        rating: 4.4,
        reviewCount: 9100,
        priceLevel: 2,
        ambianceTags: ['cosy', 'familial'],
        musicTags: ['pop'],
        styleTags: ['crêperie'],
      ),
      Place(
        id: 'f13b4af3-0619-48ab-871a-b4670d557482',
        name: 'Café Laurent',
        type: PlaceType.restaurant,
        latitude: 48.8547358,
        longitude: 2.3395366,
        address: '33 Rue Dauphine, 75006 Paris',
        rating: 4.8,
        reviewCount: 804,
        priceLevel: 1,
        ambianceTags: ['feutré', 'historique', 'romantique'],
        musicTags: ['jazz'],
        styleTags: [],
      ),
      Place(
        id: '41cd0ee8-9668-4a85-a036-34b80cd2d750',
        name: 'Candelaria',
        type: PlaceType.restaurant,
        latitude: 48.8629825,
        longitude: 2.3640307,
        address: '52 Rue de Saintonge, 75003 Paris',
        rating: 4.4,
        reviewCount: 3079,
        priceLevel: 1,
        ambianceTags: ['festif', 'convivial', 'branché'],
        musicTags: ['latino', 'dj set'],
        styleTags: [],
      ),
      Place(
        id: '57b1429b-e1cf-4f14-a549-997b40406eba',
        name: 'Dalmata Paris 2',
        type: PlaceType.restaurant,
        latitude: 48.8645246,
        longitude: 2.3494238,
        address: '8 Rue Tiquetonne, 75002 Paris',
        rating: 4.6,
        reviewCount: 5189,
        priceLevel: 1,
        ambianceTags: ['convivial', 'chaleureux', 'branché'],
        musicTags: [],
        styleTags: ['pizzeria', 'italien', 'quartier-Montorgueil'],
      ),
      Place(
        id: '3d09d6f6-9a61-44c8-b998-c25eb0a14a40',
        name: 'Dans le Noir',
        type: PlaceType.restaurant,
        latitude: 48.86521,
        longitude: 2.34791,
        address: '51 Rue Quincampoix, 75004 Paris',
        rating: 4.4,
        reviewCount: 2500,
        priceLevel: 1,
        ambianceTags: ['dark', 'immersive'],
        musicTags: ['lounge'],
        styleTags: [],
      ),
      Place(
        id: '576a28e3-b3bb-4cbf-a517-2e9d3a20bea4',
        name: 'Derrière',
        type: PlaceType.restaurant,
        latitude: 48.864518,
        longitude: 2.354208,
        address: '69 Rue des Gravilliers, 75003 Paris',
        rating: 4.2,
        reviewCount: 2012,
        priceLevel: 1,
        ambianceTags: ['intimiste', 'bohème', 'convivial'],
        musicTags: ['lounge', 'éclectique'],
        styleTags: [],
      ),
      Place(
        id: '3798f5b0-c112-47a3-abfc-b9286e77495a',
        name: 'Derrière',
        type: PlaceType.restaurant,
        latitude: 48.86351,
        longitude: 2.36571,
        address: '69 Rue des Gravilliers, 75003 Paris',
        rating: 4.3,
        reviewCount: 1300,
        priceLevel: 1,
        ambianceTags: ['secret room', 'home vibe'],
        musicTags: ['chill'],
        styleTags: [],
      ),
      Place(
        id: '11bab4a2-10ec-4c54-8b7f-875aad17746f',
        name: 'Ducasse sur Seine',
        type: PlaceType.restaurant,
        latitude: 48.8605363,
        longitude: 2.2918296,
        address: '19 Port Debilly, 75116 Paris',
        rating: 4.7,
        reviewCount: 2164,
        priceLevel: 1,
        ambianceTags: ['romantique', 'chic', 'gastronomique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '29e4d638-5022-4b13-8114-cdd220f280ca',
        name: 'East Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8519,
        longitude: 2.3782,
        address: '133 Rue du Faubourg Saint-Antoine, 75011 Paris',
        rating: 4.4,
        reviewCount: 11200,
        priceLevel: 2,
        ambianceTags: ['animé', 'familial', 'festif'],
        musicTags: ['pop'],
        styleTags: ['italien', 'pizza'],
      ),
      Place(
        id: 'fc3b377c-ab08-4ed8-8959-4dab6efee47b',
        name: 'Girafe',
        type: PlaceType.restaurant,
        latitude: 48.8630338,
        longitude: 2.2885823,
        address: '1 Place du Trocadéro, 75016 Paris',
        rating: 4.4,
        reviewCount: 5548,
        priceLevel: 1,
        ambianceTags: ['chic', 'festif', 'branché'],
        musicTags: ['lounge', 'dj set'],
        styleTags: [],
      ),
      Place(
        id: 'c2cfbcd8-dbf8-49e8-87a9-b47bf3ab95a6',
        name: 'Hanok',
        type: PlaceType.restaurant,
        latitude: 48.8651018,
        longitude: 2.2937604,
        address: '6 Place d\'Iéna, 75116 Paris ',
        rating: 4.4,
        reviewCount: 5548,
        priceLevel: 1,
        ambianceTags: ['paisible', 'dépaysant', 'élégant'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '05565222-c4cc-42dd-9aa5-0c2ad2914b58',
        name: 'Jungle Palace by Ephemera',
        type: PlaceType.restaurant,
        latitude: 48.8748014,
        longitude: 2.35665,
        address: '12 Rue de la Fidélité, 75010 Paris',
        rating: 4.8,
        reviewCount: 21414,
        priceLevel: 2,
        ambianceTags: ['exotique', 'festif', 'instagrammable'],
        musicTags: ['lounge', 'DJ'],
        styleTags: ['restaurant-bar', 'jungle', 'quartier-Gare-de-l\'Est'],
      ),
      Place(
        id: '9421d19e-d2d3-44e9-bec4-a412750c2bf5',
        name: 'Kodawari Ramen',
        type: PlaceType.restaurant,
        latitude: 48.853,
        longitude: 2.336,
        address: '29 Rue Mazarine, 75006 Paris',
        rating: 4.4,
        reviewCount: 4100,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'animé', 'insolite'],
        musicTags: ['pop'],
        styleTags: ['japonais'],
      ),
      Place(
        id: '7c30c9fc-6486-4bf0-a6e1-7eda0c4653a6',
        name: 'Kodawari Ranen (Tsukiji)',
        type: PlaceType.restaurant,
        latitude: 48.8546339,
        longitude: 2.3381036,
        address: '12 Rue de Richelieu, 75001 Paris',
        rating: 4.4,
        reviewCount: 12299,
        priceLevel: 2,
        ambianceTags: ['authentique', 'immersif', 'animé'],
        musicTags: [],
        styleTags: ['ramen', 'japonais', 'quartier-Odéon'],
      ),
      Place(
        id: '515a5a31-f8fa-4543-8cd3-d36b79e3d1c8',
        name: 'La Felicita',
        type: PlaceType.restaurant,
        latitude: 48.83343,
        longitude: 2.371874,
        address: '5 Parv. Alan Turing, 75013 Paris',
        rating: 4.5,
        reviewCount: 433,
        priceLevel: 2,
        ambianceTags: ['festif', 'branche', 'immense'],
        musicTags: ['DJ'],
        styleTags: ['food court italien', 'ancienne gare', 'groupe'],
      ),
      Place(
        id: 'e16f9f92-5c08-463e-b6bc-e25717543c63',
        name: 'La Halle aux Grains',
        type: PlaceType.restaurant,
        latitude: 48.8629365,
        longitude: 2.3423588,
        address: '2 Rue de Viarmes, 75001 Paris ',
        rating: 4.3,
        reviewCount: 881,
        priceLevel: 1,
        ambianceTags: ['chic', 'élégant', 'gastronomique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'dd6e6fe7-ab4a-4234-a609-485da1a6a5b0',
        name: 'La Recyclerie',
        type: PlaceType.restaurant,
        latitude: 48.89491,
        longitude: 2.33721,
        address: '83 Boulevard Ornano, 75018 Paris',
        rating: 4.4,
        reviewCount: 4500,
        priceLevel: 1,
        ambianceTags: ['eco', 'casual'],
        musicTags: ['chill'],
        styleTags: [],
      ),
      Place(
        id: '26d1d5fb-61e5-48d5-911b-4b1c08fcc131',
        name: 'La Tour d\'Argent',
        type: PlaceType.restaurant,
        latitude: 48.849856,
        longitude: 2.354994,
        address: '15 Quai de la Tournelle, 75005 Paris',
        rating: 4.6,
        reviewCount: 808,
        priceLevel: 1,
        ambianceTags: ['chic', 'romantique', 'gastronomique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'c54a3560-691e-47ab-87bd-3ca16832d687',
        name: 'Lapérouse',
        type: PlaceType.restaurant,
        latitude: 48.8551202,
        longitude: 2.3415552,
        address: '51 Quai des Grands Augustins, 75006 Paris',
        rating: 4.4,
        reviewCount: 2120,
        priceLevel: 1,
        ambianceTags: ['romantique', 'historique', 'intimiste'],
        musicTags: ['jazz', 'piano'],
        styleTags: [],
      ),
      Place(
        id: '86259d9d-7ba5-455a-be09-6a112214ce81',
        name: 'Le Café des Chats',
        type: PlaceType.restaurant,
        latitude: 48.8558739,
        longitude: 2.371819,
        address: '9 Rue Sedaine, 75011 Paris',
        rating: 4.3,
        reviewCount: 7040,
        priceLevel: 1,
        ambianceTags: ['cosy', 'insolite', 'nostalgique'],
        musicTags: [],
        styleTags: ['bar-à-chats', 'salon-de-thé', 'quartier-Bastille'],
      ),
      Place(
        id: '0c07d31f-9eb1-45db-9f84-3ffd920314bd',
        name: 'Le Coupe-Chou',
        type: PlaceType.restaurant,
        latitude: 48.8485228,
        longitude: 2.3462711,
        address: '11 Rue de Lanneau, 75005 Paris',
        rating: 4.6,
        reviewCount: 2483,
        priceLevel: 1,
        ambianceTags: ['romantique', 'intimiste', 'historique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '9c12b464-d2d4-42ba-90c6-1cb49b2c4c71',
        name: 'Le Jules Verne',
        type: PlaceType.restaurant,
        latitude: 48.8583698,
        longitude: 2.2944833,
        address: '2e étage Tour Eiffel, Av. Gustave Eiffel, 75007 Paris',
        rating: 4.4,
        reviewCount: 3588,
        priceLevel: 1,
        ambianceTags: ['chic', 'romantique', 'gastronomique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'f5a18bbc-8731-4ba7-abe9-ced844779351',
        name: 'Le Jules Verne',
        type: PlaceType.restaurant,
        latitude: 48.8582,
        longitude: 2.2945,
        address: 'Tour Eiffel Avenue Gustave Eiffel, 75007 Paris',
        rating: 4.5,
        reviewCount: 2200,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'd5fee0e0-c331-42b0-afd0-004574a54a00',
        name: 'Le Tout-Paris',
        type: PlaceType.restaurant,
        latitude: 48.8585,
        longitude: 2.347,
        address: 'Cheval Blanc 8 Quai du Louvre, 75001 Paris',
        rating: 4.5,
        reviewCount: 880,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'rooftop', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: '84fc1636-d0d6-4e48-8490-9a747ff6ef3f',
        name: 'Le Train Bleu',
        type: PlaceType.restaurant,
        latitude: 48.8448989,
        longitude: 2.3732694,
        address: 'Gare de Lyon, Place Louis-Armand, 75012 Paris',
        rating: 4.4,
        reviewCount: 18363,
        priceLevel: 1,
        ambianceTags: ['chic', 'historique', 'élégant'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'b0f0c7f6-f497-4116-8a45-5e1895e0b9dd',
        name: 'Les Ombres',
        type: PlaceType.restaurant,
        latitude: 48.86178,
        longitude: 2.29869,
        address: '27 Quai Jacques Chirac, 75007 Paris',
        rating: 4.1,
        reviewCount: 358,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique', 'spectaculaire'],
        musicTags: ['lounge'],
        styleTags: ['vue Tour Eiffel', 'rooftop musee', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'b00ad27e-b321-4efa-b842-46d0f8c3849a',
        name: 'Les Ombres',
        type: PlaceType.restaurant,
        latitude: 48.86178,
        longitude: 2.29869,
        address: '27 Quai Jacques Chirac, 75007 Paris',
        rating: 4.1,
        reviewCount: 3270,
        priceLevel: 1,
        ambianceTags: ['romantique', 'élégant', 'gastronomique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '538d134a-da2f-405f-bc14-e1276715393c',
        name: 'Liza',
        type: PlaceType.restaurant,
        latitude: 48.8676,
        longitude: 2.3399,
        address: '14 Rue de la Banque, 75002 Paris',
        rating: 4.4,
        reviewCount: 2300,
        priceLevel: 3,
        ambianceTags: ['cosy', 'romantique'],
        musicTags: ['lounge', 'latino'],
        styleTags: ['libanais'],
      ),
      Place(
        id: '6c4abe63-f36e-44a1-a9a8-ff0802186700',
        name: 'Monsieur Bleu',
        type: PlaceType.restaurant,
        latitude: 48.8643563,
        longitude: 2.2968759,
        address: '20 Av. de New York, 75116 Paris ',
        rating: 4.7,
        reviewCount: 3987,
        priceLevel: 1,
        ambianceTags: ['chic', 'élégant', 'branché'],
        musicTags: ['lounge'],
        styleTags: [],
      ),
      Place(
        id: '63ab43fa-8fdd-4e1a-8385-513064462011',
        name: 'Père et Fish',
        type: PlaceType.restaurant,
        latitude: 48.875682,
        longitude: 2.3481175,
        address: '67 Rue du Faubourg Poissonnière, 75009 Paris',
        rating: 4.6,
        reviewCount: 5227,
        priceLevel: 1,
        ambianceTags: ['décontracté', 'moderne', 'convivial'],
        musicTags: [],
        styleTags: ['fish-burger', 'fish-and-chips', 'quartier-Poissonnière'],
      ),
      Place(
        id: '3e9e8ac5-b2c4-418c-b63b-e6d1c0e6e7f3',
        name: 'Pink Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8819469,
        longitude: 2.3345309,
        address: '20bis Rue de Douai, 75009 Paris',
        rating: 4.7,
        reviewCount: 50067,
        priceLevel: 1,
        ambianceTags: ['festif', 'branché', 'convivial'],
        musicTags: ['pop', 'italo'],
        styleTags: [],
      ),
      Place(
        id: 'b8365e2f-5085-4944-8080-d4110a449357',
        name: 'Pink Mamma',
        type: PlaceType.restaurant,
        latitude: 48.87941,
        longitude: 2.33721,
        address: '20 Avenue Trudaine, 75009 Paris',
        rating: 4.5,
        reviewCount: 5000,
        priceLevel: 1,
        ambianceTags: ['instagrammable', 'cozy'],
        musicTags: ['chill'],
        styleTags: [],
      ),
      Place(
        id: '95e5778c-6638-4340-85dd-c666a07c08ac',
        name: 'Pink Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8819,
        longitude: 2.3375,
        address: '20bis Rue de Douai, 75009 Paris',
        rating: 4.5,
        reviewCount: 13900,
        priceLevel: 3,
        ambianceTags: ['branché', 'animé'],
        musicTags: ['pop', 'soul'],
        styleTags: ['italien', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'ef29d828-e955-425a-8c00-359072011765',
        name: 'Soon Grill Le Marais 순그릴 마레',
        type: PlaceType.restaurant,
        latitude: 48.858096,
        longitude: 2.367436,
        address: '78 Rue des Tournelles, 75003 Paris',
        rating: 4.5,
        reviewCount: 3082,
        priceLevel: 3,
        ambianceTags: ['chaleureux', 'minimaliste', 'convivial'],
        musicTags: [],
        styleTags: ['barbecue-coréen', 'wine-bar', 'quartier-Marais'],
      ),
      Place(
        id: '91b75131-7216-4cf6-bbad-7eeda9bea246',
        name: 'Sphere',
        type: PlaceType.restaurant,
        latitude: 48.874267,
        longitude: 2.316939,
        address: '18 Rue La Boetie, 75008 Paris',
        rating: 4.8,
        reviewCount: 974,
        priceLevel: 4,
        ambianceTags: ['gastronomique', 'raffine', 'elegant'],
        musicTags: ['soft'],
        styleTags: ['haute cuisine', 'menu degustation', 'mocktails'],
        isPremium: true,
      ),
      Place(
        id: '9fb4e658-e464-4406-9429-1efdacebe70d',
        name: 'Wagon Bleu',
        type: PlaceType.restaurant,
        latitude: 48.88351,
        longitude: 2.31571,
        address: '7 Rue Boursault, 75017 Paris',
        rating: 4.4,
        reviewCount: 1400,
        priceLevel: 1,
        ambianceTags: ['corsican', 'vintage'],
        musicTags: ['lounge'],
        styleTags: [],
      ),
      // ===================== HOTELS =====================
      Place(
        id: 'c63fe33f-c3ab-4440-89db-866c46d6e8a6',
        name: 'Bloom House Hotel & Spa',
        type: PlaceType.hotel,
        latitude: 48.881494,
        longitude: 2.362626,
        address: '23 R. du Chateau Landon, 75010 Paris',
        rating: 4.6,
        reviewCount: 711,
        priceLevel: 3,
        ambianceTags: ['cosy', 'verdoyant', 'relax'],
        musicTags: ['soft'],
        styleTags: ['jardin', 'spa piscine', 'cocktail bar'],
      ),
      Place(
        id: '44536cb5-1a1d-40a5-acac-0674fbfc2c4c',
        name: 'Brach Paris',
        type: PlaceType.hotel,
        latitude: 48.8636,
        longitude: 2.282,
        address: '1-7 Rue Jean Richepin, 75116 Paris',
        rating: 4.6,
        reviewCount: 1400,
        priceLevel: 4,
        ambianceTags: ['branché', 'chic', 'cosy'],
        musicTags: ['lounge', 'soul'],
        styleTags: ['design', 'rooftop'],
        isPremium: true,
      ),
      Place(
        id: 'ed5cea5e-eee1-4a6f-a2fd-1765817ea1f8',
        name: 'Chateau des Fleurs',
        type: PlaceType.hotel,
        latitude: 48.871826,
        longitude: 2.298396,
        address: '19 Rue Vernet, 75008 Paris',
        rating: 4.7,
        reviewCount: 320,
        priceLevel: 4,
        ambianceTags: ['fleuri', 'charmant', 'raffine'],
        musicTags: ['soft'],
        styleTags: ['boutique-hotel', 'pres Champs-Elysees', 'lounge'],
        isPremium: true,
      ),
      Place(
        id: '162db586-2b60-4181-ac9e-a55ebc26992e',
        name: 'Chateau Voltaire',
        type: PlaceType.hotel,
        latitude: 48.867112,
        longitude: 2.33328,
        address: '55 Rue Saint-Roch, 75001 Paris',
        rating: 4.6,
        reviewCount: 179,
        priceLevel: 4,
        ambianceTags: ['design', 'cosy', 'raffine'],
        musicTags: ['lounge'],
        styleTags: ['boutique-hotel', 'bar', 'quartier Saint-Honore'],
        isPremium: true,
      ),
      Place(
        id: '33922c30-b334-4998-9f50-c9b4b1e3f506',
        name: 'Four Seasons George V',
        type: PlaceType.hotel,
        latitude: 48.8686,
        longitude: 2.3008,
        address: '31 Avenue George V, 75008 Paris',
        rating: 4.8,
        reviewCount: 4100,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace'],
        isPremium: true,
      ),
      Place(
        id: '7a7e566e-3cfc-4a9d-b733-6ed515625736',
        name: 'Generator Paris',
        type: PlaceType.hotel,
        latitude: 48.8809,
        longitude: 2.37,
        address: '9-11 Place du Colonel Fabien, 75010 Paris',
        rating: 4.1,
        reviewCount: 6400,
        priceLevel: 2,
        ambianceTags: ['festif', 'décontracté', 'business'],
        musicTags: ['house', 'pop'],
        styleTags: ['rooftop', 'vue Tour Eiffel'],
      ),
      Place(
        id: '58d2511a-7418-4ad2-ab04-89c2348e4681',
        name: 'Hotel Costes',
        type: PlaceType.hotel,
        latitude: 48.8676,
        longitude: 2.3274,
        address: '239 Rue Saint-Honore, 75001 Paris',
        rating: 4.4,
        reviewCount: 1800,
        priceLevel: 4,
        ambianceTags: ['chic', 'festif'],
        musicTags: ['lounge', 'house'],
        styleTags: ['palace', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: '51c56a0b-3bdf-464f-86f3-ce191ce64641',
        name: 'Hotel Dame des Arts',
        type: PlaceType.hotel,
        latitude: 48.852847,
        longitude: 2.342293,
        address: '4 Rue Danton, 75006 Paris',
        rating: 4.7,
        reviewCount: 331,
        priceLevel: 4,
        ambianceTags: ['design', 'chic', 'elegant'],
        musicTags: ['lounge'],
        styleTags: ['rooftop vue Tour Eiffel', 'terrasse', 'Rive Gauche'],
        isPremium: true,
      ),
      Place(
        id: 'ccc8cbdd-72dd-43d1-8ca6-19e286369706',
        name: 'Hotel Grand Amour',
        type: PlaceType.hotel,
        latitude: 48.8714,
        longitude: 2.355,
        address: '18 Rue de la Fidelite, 75010 Paris',
        rating: 4.3,
        reviewCount: 1100,
        priceLevel: 3,
        ambianceTags: ['cosy', 'festif', 'branché'],
        musicTags: ['pop', 'afro'],
        styleTags: ['boutique-hôtel', 'design', 'terrasse'],
      ),
      Place(
        id: '0fcd95c1-9654-4263-88f8-b92e32e3ffca',
        name: 'Hotel Madame Reve',
        type: PlaceType.hotel,
        latitude: 48.864535,
        longitude: 2.342873,
        address: '48 Rue du Louvre, 75001 Paris',
        rating: 4.6,
        reviewCount: 665,
        priceLevel: 4,
        ambianceTags: ['design', 'romantique', 'sexy'],
        musicTags: ['lounge'],
        styleTags: ['ancien hotel des postes', 'rooftop', 'sauna'],
        isPremium: true,
      ),
      Place(
        id: '3b375410-bf0f-4a90-903b-a071e50c3454',
        name: 'Hotel Marignan Champs-Elysees',
        type: PlaceType.hotel,
        latitude: 48.868532,
        longitude: 2.306548,
        address: '12 Rue de Marignan, 75008 Paris',
        rating: 4.7,
        reviewCount: 521,
        priceLevel: 4,
        ambianceTags: ['chaleureux', 'elegant', 'intime'],
        musicTags: ['soft'],
        styleTags: ['boutique-hotel', 'vue Tour Eiffel', 'Champs-Elysees'],
        isPremium: true,
      ),
      Place(
        id: '6643699b-a23d-4391-96e7-0cb0acbbc16c',
        name: 'Hotel National des Arts et Metiers',
        type: PlaceType.hotel,
        latitude: 48.865717,
        longitude: 2.353225,
        address: '243 Rue Saint-Martin, 75003 Paris',
        rating: 4.4,
        reviewCount: 318,
        priceLevel: 3,
        ambianceTags: ['design', 'branche', 'elegant'],
        musicTags: ['lounge'],
        styleTags: ['rooftop', 'bar', 'Marais'],
      ),
      Place(
        id: 'e702ef78-41ac-45cd-a894-ed5835e4a4cc',
        name: 'Hôtel Pont Royal Paris',
        type: PlaceType.hotel,
        latitude: 48.856686,
        longitude: 2.327746,
        address: '3 Rue de Montalembert, 75007 Paris',
        rating: 4.7,
        reviewCount: 301,
        priceLevel: 3,
        ambianceTags: ['raffiné', 'littéraire', 'élégant'],
        musicTags: ['jazz'],
        styleTags: ['hôtel-5-étoiles', 'bar-jazz', 'quartier-Saint-Germain'],
        isPremium: true,
      ),
      Place(
        id: '127f6df1-7865-4d3a-a2c1-7a0ef0e67516',
        name: 'Hôtel Pullman Paris Montparnasse',
        type: PlaceType.hotel,
        latitude: 48.838455,
        longitude: 2.320393,
        address: '19 Rue du Commandant René Mouchotte, 75014 Paris',
        rating: 4.8,
        reviewCount: 15646,
        priceLevel: 2,
        ambianceTags: ['moderne', 'design', 'vue-panoramique'],
        musicTags: ['lounge', 'DJ'],
        styleTags: ['hôtel-4-étoiles', 'sky-bar', 'rooftop', 'quartier-Montparnasse'],
        isPremium: true,
      ),
      Place(
        id: '358ce5ab-6bd9-4c43-a50c-8ddf5333cc91',
        name: 'Hôtel Westminster',
        type: PlaceType.hotel,
        latitude: 48.869373,
        longitude: 2.331062,
        address: '13 Rue de la Paix, 75002 Paris',
        rating: 4.0,
        reviewCount: 821,
        priceLevel: 3,
        ambianceTags: ['classique', 'historique', 'luxe'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['hôtel-5-étoiles', 'bar', 'quartier-Opéra'],
        isPremium: true,
      ),
      Place(
        id: 'c451f11e-98fd-4728-9eb4-fbf6178fc08c',
        name: 'Hôtel Whistler Paris - 10e arrondissement',
        type: PlaceType.hotel,
        latitude: 48.8793055,
        longitude: 2.3559889,
        address: '36 Rue de Saint-Quentin, 75010 Paris',
        rating: 4.5,
        reviewCount: 622,
        priceLevel: 1,
        ambianceTags: ['thématique', 'insolite', 'cosy'],
        musicTags: ['lounge'],
        styleTags: ['hôtel-boutique', 'bar', 'quartier-Gare-du-Nord'],
      ),
      Place(
        id: 'b6a789b4-71ad-42c1-95a7-c891c9875741',
        name: 'Le Bristol Paris',
        type: PlaceType.hotel,
        latitude: 48.8721,
        longitude: 2.3157,
        address: '112 Rue du Faubourg Saint-Honore, 75008 Paris',
        rating: 4.8,
        reviewCount: 2600,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace', 'jardin'],
        isPremium: true,
      ),
      Place(
        id: '7c69c842-747c-42d8-a400-3f76d4290bfa',
        name: 'Le Grand Mazarin',
        type: PlaceType.hotel,
        latitude: 48.8577,
        longitude: 2.3545,
        address: '6 Rue des Archives, 75004 Paris',
        rating: 4.5,
        reviewCount: 1800,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique', 'cosy'],
        musicTags: ['lounge', 'jazz'],
        styleTags: ['boutique-hôtel', 'design'],
      ),
      Place(
        id: '33f5dc5d-acef-4306-9132-a21795b6b1ee',
        name: 'Le Meurice',
        type: PlaceType.hotel,
        latitude: 48.8654,
        longitude: 2.3281,
        address: '228 Rue de Rivoli, 75001 Paris',
        rating: 4.7,
        reviewCount: 2900,
        priceLevel: 4,
        ambianceTags: ['chic', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace'],
        isPremium: true,
      ),
      Place(
        id: '004a013a-b26a-4644-8d60-feac066b395e',
        name: 'Le Pavillon de la Reine',
        type: PlaceType.hotel,
        latitude: 48.8556,
        longitude: 2.3661,
        address: '28 Place des Vosges, 75003 Paris',
        rating: 4.7,
        reviewCount: 950,
        priceLevel: 4,
        ambianceTags: ['romantique', 'chic', 'intimiste'],
        musicTags: ['lounge'],
        styleTags: ['boutique-hôtel', 'jardin'],
      ),
      Place(
        id: 'c7ea09b7-5d4a-4422-af25-a58c3c6c45bf',
        name: 'Maison Proust Hotel & Spa',
        type: PlaceType.hotel,
        latitude: 48.864092,
        longitude: 2.363236,
        address: '26 Rue de Picardie, 75003 Paris',
        rating: 4.8,
        reviewCount: 284,
        priceLevel: 4,
        ambianceTags: ['luxueux', 'romantique', 'feutre'],
        musicTags: ['lounge'],
        styleTags: ['inspiration Proust', 'spa La Mer', 'Marais'],
        isPremium: true,
      ),
      Place(
        id: '9cbfb3a4-ec61-4ecf-96ae-64cc427ce23d',
        name: 'Mama Shelter Paris East',
        type: PlaceType.hotel,
        latitude: 48.8676,
        longitude: 2.4053,
        address: '109 Rue de Bagnolet, 75020 Paris',
        rating: 4.2,
        reviewCount: 3900,
        priceLevel: 2,
        ambianceTags: ['festif', 'décontracté', 'familial'],
        musicTags: ['afro', 'house'],
        styleTags: ['rooftop', 'design'],
      ),
      Place(
        id: '550df4b4-9132-4f73-b06d-cea20cfb9914',
        name: 'OFF Paris Seine',
        type: PlaceType.hotel,
        latitude: 48.8388,
        longitude: 2.3736,
        address: '20-22 Port Austerlitz, 75013 Paris',
        rating: 4.2,
        reviewCount: 2200,
        priceLevel: 3,
        ambianceTags: ['insolite', 'branché', 'romantique'],
        musicTags: ['lounge', 'house'],
        styleTags: ['péniche', 'design', 'terrasse'],
      ),
      Place(
        id: '9326a4a8-c832-4f1a-aab3-2552ca9ed5ac',
        name: 'Pullman Paris Centre Bercy',
        type: PlaceType.hotel,
        latitude: 48.831625,
        longitude: 2.386782,
        address: '1 Rue de Libourne, 75012 Paris',
        rating: 4.6,
        reviewCount: 8026,
        priceLevel: 2,
        ambianceTags: ['moderne', 'spa', 'confort'],
        musicTags: ['lounge'],
        styleTags: ['hôtel-4-étoiles', 'piscine-spa', 'quartier-Bercy'],
        isPremium: true,
      ),
      Place(
        id: '5fc6d628-3c1a-4ea2-adf9-8d8bf9e4e385',
        name: 'Pullman Paris Tour Eiffel',
        type: PlaceType.hotel,
        latitude: 48.855649,
        longitude: 2.292858,
        address: '18 Avenue De Suffren, 22 Rue Jean Rey Entrée Au, 75015 Paris',
        rating: 4.6,
        reviewCount: 15614,
        priceLevel: 4,
        ambianceTags: ['moderne', 'élégant', 'vue-Tour-Eiffel'],
        musicTags: ['lounge', 'DJ'],
        styleTags: ['hôtel-4-étoiles', 'bar', 'vue-Tour-Eiffel', 'quartier-Champ-de-Mars'],
        isPremium: true,
      ),
      Place(
        id: '41e2aa41-d050-4864-80ef-77d53c6ad7d4',
        name: 'Ritz Paris',
        type: PlaceType.hotel,
        latitude: 48.8681,
        longitude: 2.3284,
        address: '15 Place Vendome, 75001 Paris',
        rating: 4.8,
        reviewCount: 3600,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace', 'jardin'],
        isPremium: true,
      ),
      Place(
        id: '28c8e646-e2f6-42e1-84c8-4db7764f38b1',
        name: 'SO/ Paris',
        type: PlaceType.hotel,
        latitude: 48.852,
        longitude: 2.361,
        address: '10 Rue Agrippa d Aubigne, 75004 Paris',
        rating: 4.5,
        reviewCount: 1800,
        priceLevel: 4,
        ambianceTags: ['branché', 'festif', 'chic'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'design', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: '7bf1fa72-668c-408d-be8e-3c44f149506d',
        name: 'Sourire Boutique Hotel',
        type: PlaceType.hotel,
        latitude: 48.85503,
        longitude: 2.275528,
        address: '29 Rue des Marronniers, 75016 Paris',
        rating: 4.7,
        reviewCount: 108,
        priceLevel: 3,
        ambianceTags: ['charmant', 'familial', 'chaleureux'],
        musicTags: ['soft'],
        styleTags: ['hotel particulier', 'terrasse rooftop', 'petit-dejeuner'],
      ),
      Place(
        id: '540521ac-843e-4c4a-a146-7f766a3d3c0b',
        name: 'The Hoxton Paris',
        type: PlaceType.hotel,
        latitude: 48.8688,
        longitude: 2.3506,
        address: '30-32 Rue du Sentier, 75002 Paris',
        rating: 4.4,
        reviewCount: 3200,
        priceLevel: 3,
        ambianceTags: ['branché', 'cosy', 'business'],
        musicTags: ['house', 'soul'],
        styleTags: ['boutique-hôtel', 'design'],
      ),
      Place(
        id: '6218ac00-de49-41f3-b4a4-c5aa00a2fd35',
        name: 'Villa des Pres',
        type: PlaceType.hotel,
        latitude: 48.853485,
        longitude: 2.336409,
        address: '29 Rue de Buci, 75006 Paris',
        rating: 4.6,
        reviewCount: 108,
        priceLevel: 4,
        ambianceTags: ['luxueux', 'raffine', 'elegant'],
        musicTags: ['soft'],
        styleTags: ['boutique-hotel', 'spa sauna', 'art deco'],
        isPremium: true,
      ),
      Place(
        id: 'e7e161e5-c46c-4c5a-a322-8fdb379a0ea0',
        name: 'Zoku Paris',
        type: PlaceType.hotel,
        latitude: 48.895894,
        longitude: 2.311326,
        address: '48 Av. de la Prte de Clichy, 75017 Paris',
        rating: 4.6,
        reviewCount: 855,
        priceLevel: 2,
        ambianceTags: ['design', 'convivial', 'cosy'],
        musicTags: ['lounge'],
        styleTags: ['aparthôtel', 'coworking', 'rooftop', 'quartier-Clichy-Batignolles'],
      ),
      // ===================== ROOFTOPS =====================
      Place(
        id: 'ff9d7528-b76d-4d3b-b275-b50c1c9e6e2d',
        name: '10eme Ciel',
        type: PlaceType.rooftop,
        latitude: 48.855512,
        longitude: 2.292716,
        address: '18 Av. de Suffren, 75015 Paris',
        rating: 4.1,
        reviewCount: 566,
        priceLevel: 3,
        ambianceTags: ['chic', 'festif', 'branche'],
        musicTags: ['DJ'],
        styleTags: ['vue Tour Eiffel', 'Pullman', 'cocktails'],
      ),
      Place(
        id: '7697cd0a-5a51-4116-8212-13a367bebab9',
        name: 'Gigi Rooftop',
        type: PlaceType.rooftop,
        latitude: 48.87112,
        longitude: 2.33191,
        address: '15 Rue de la Paix, 75002 Paris',
        rating: 4.5,
        reviewCount: 900,
        priceLevel: 1,
        ambianceTags: ['italian', 'luxury'],
        musicTags: ['lounge'],
        styleTags: [],
      ),
      Place(
        id: '97d7089c-3bbd-4334-adec-20c0835c00e8',
        name: 'Ilvolo Bar Rooftop',
        type: PlaceType.rooftop,
        latitude: 48.839935,
        longitude: 2.303228,
        address: '257 Rue de Vaugirard, 75015 Paris',
        rating: 4.4,
        reviewCount: 779,
        priceLevel: 2,
        ambianceTags: ['chic', 'romantique', 'convivial'],
        musicTags: ['lounge'],
        styleTags: ['vue Tour Eiffel', 'cocktails dauteur'],
      ),
      Place(
        id: '9cdc2bc3-db21-407e-b3c4-20a077eba6f6',
        name: 'L\'Oiseau Blanc Peninsula',
        type: PlaceType.rooftop,
        latitude: 48.8686,
        longitude: 2.2964,
        address: '19 Avenue Kleber, 75016 Paris',
        rating: 4.7,
        reviewCount: 2400,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['rooftop', 'vue Tour Eiffel', 'gastronomique', 'palace'],
        isPremium: true,
      ),
      Place(
        id: 'ec804971-b3ee-4ae3-97ab-60ad657d8f53',
        name: 'Perruche',
        type: PlaceType.rooftop,
        latitude: 48.87339,
        longitude: 2.32652,
        address: 'Printemps Haussmann, 2 Rue du Havre, 75009 Paris',
        rating: 4.3,
        reviewCount: 1500,
        priceLevel: 1,
        ambianceTags: ['chic', 'sunset'],
        musicTags: ['lounge'],
        styleTags: [],
      ),
      Place(
        id: 'cb181f75-81be-42b3-84a3-98bb8e0ca6f3',
        name: 'Rooftop Dame des Arts',
        type: PlaceType.rooftop,
        latitude: 48.8528666,
        longitude: 2.3422929,
        address: '4 Rue Danton, 75006 Paris',
        rating: 4.3,
        reviewCount: 727,
        priceLevel: 1,
        ambianceTags: ['chic', 'intimiste', 'romantique'],
        musicTags: ['lounge', 'deep house'],
        styleTags: [],
      ),
      Place(
        id: '343441a2-3e1a-462b-b9a5-816fb8ed01eb',
        name: 'Rooftop du Printemps Haussmann',
        type: PlaceType.rooftop,
        latitude: 48.8738,
        longitude: 2.3316,
        address: '64 Boulevard Haussmann, 75009 Paris',
        rating: 4.3,
        reviewCount: 18000,
        priceLevel: 1,
        ambianceTags: ['animé', 'décontracté', 'familial'],
        musicTags: [],
        styleTags: ['rooftop', 'vue panoramique', 'vue Tour Eiffel', 'gratuit'],
      ),
      Place(
        id: '77901f33-3712-4496-8100-44fd686a1f2a',
        name: 'Rooftop Nijinsky',
        type: PlaceType.rooftop,
        latitude: 48.857703,
        longitude: 2.346822,
        address: '1 Pl. du Chatelet, 75001 Paris',
        rating: 4.3,
        reviewCount: 78,
        priceLevel: 3,
        ambianceTags: ['chic', 'central', 'branche'],
        musicTags: ['lounge'],
        styleTags: ['terrasse', 'vue toits de Paris'],
      ),
      Place(
        id: '69de4f46-3e04-4103-a065-006726c65f91',
        name: 'Rooftop Villa M',
        type: PlaceType.rooftop,
        latitude: 48.842378,
        longitude: 2.312452,
        address: '28 Bd Pasteur, 75015 Paris',
        rating: 3.9,
        reviewCount: 207,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique', 'vegetal'],
        musicTags: ['lounge'],
        styleTags: ['vue Tour Eiffel', 'facade vegetale', 'coucher de soleil'],
      ),
      Place(
        id: '248dcabe-0db1-46c0-a5f7-d3a73a9896a5',
        name: 'Terraza Mikuna',
        type: PlaceType.rooftop,
        latitude: 48.857333,
        longitude: 2.354002,
        address: '1 Rue des Archives, 75004 Paris',
        rating: 3.9,
        reviewCount: 892,
        priceLevel: 3,
        ambianceTags: ['chic', 'branche', 'romantique'],
        musicTags: ['lounge'],
        styleTags: ['vue Marais', 'cuisine peruvienne', 'coucher de soleil'],
      ),
      Place(
        id: 'acace5f4-8c76-4c7c-b09d-8daed56e5ef9',
        name: 'TOO TacTac',
        type: PlaceType.rooftop,
        latitude: 48.82547,
        longitude: 2.382415,
        address: '65 Rue Bruneseau, 75013 Paris',
        rating: 4.1,
        reviewCount: 329,
        priceLevel: 3,
        ambianceTags: ['festif', 'glamour', 'branche'],
        musicTags: ['DJ'],
        styleTags: ['27e etage', 'vue panoramique', 'cocktails'],
        isPremium: true,
      ),
      // ===================== PARCS =====================
      Place(
        id: '15ebc994-7e34-468b-b36c-0d9d2c88d304',
        name: 'Coulee Verte Rene-Dumont',
        type: PlaceType.parc,
        latitude: 48.849455,
        longitude: 2.371486,
        address: 'Coulee Verte Rene-Dumont, 75012 Paris',
        rating: 4.6,
        reviewCount: 683,
        priceLevel: 1,
        ambianceTags: ['insolite', 'romantique', 'verdoyant'],
        musicTags: ['aucun'],
        styleTags: ['promenade plantee', 'ancien viaduc', 'balade'],
      ),
      Place(
        id: '110a2dd0-e2f1-40a2-a17d-651f4a7f6012',
        name: 'Jardin alpin (Jardin des Plantes)',
        type: PlaceType.parc,
        latitude: 48.8439069,
        longitude: 2.359658,
        address: '57 Rue Cuvier, 75005 Paris',
        rating: 4.5,
        reviewCount: 727,
        priceLevel: 1,
        ambianceTags: ['paisible', 'nature', 'romantique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '06bfc1cf-eb70-4405-9477-9dc137ff57fd',
        name: 'Jardin de la Nouvelle France',
        type: PlaceType.parc,
        latitude: 48.865083,
        longitude: 2.310609,
        address: 'Av. Franklin Delano Roosevelt, 75008 Paris',
        rating: 4.7,
        reviewCount: 39,
        priceLevel: 1,
        ambianceTags: ['romantique', 'cache', 'intime'],
        musicTags: ['aucun'],
        styleTags: ['jardin secret', 'cascade', '1900'],
      ),
      Place(
        id: 'b1c16fe7-7bb5-483f-88c7-a7b8b0275c8b',
        name: 'Jardin du Luxembourg',
        type: PlaceType.parc,
        latitude: 48.846614,
        longitude: 2.336331,
        address: '75006 Paris',
        rating: 4.7,
        reviewCount: 938,
        priceLevel: 1,
        ambianceTags: ['romantique', 'emblematique', 'verdoyant'],
        musicTags: ['aucun'],
        styleTags: ['bassin', 'statues', 'chaises vertes'],
      ),
      Place(
        id: 'd19928dd-e017-4474-8db4-b36905e14001',
        name: 'Parc de Bercy',
        type: PlaceType.parc,
        latitude: 48.83706,
        longitude: 2.378902,
        address: '128 Quai de Bercy, 75012 Paris',
        rating: 4.0,
        reviewCount: 543,
        priceLevel: 1,
        ambianceTags: ['paisible', 'verdoyant', 'familial'],
        musicTags: ['aucun'],
        styleTags: ['jardins thematiques', 'passerelles', 'peu touristique'],
      ),
      Place(
        id: '6bf9b077-5e9f-48f0-b2cc-6c20d79884bb',
        name: 'Parc des Buttes-Chaumont',
        type: PlaceType.parc,
        latitude: 48.88095,
        longitude: 2.382761,
        address: '1 Rue Botzaris, 75019 Paris',
        rating: 4.6,
        reviewCount: 761,
        priceLevel: 1,
        ambianceTags: ['romantique', 'sauvage', 'spectaculaire'],
        musicTags: ['aucun'],
        styleTags: ['falaises', 'lac', 'temple belvedere'],
      ),
      Place(
        id: '171f3bd6-073c-41d4-8952-f81c1ddefd62',
        name: 'Parc Floral de Paris',
        type: PlaceType.parc,
        latitude: 48.837702,
        longitude: 2.444298,
        address: 'Rte de la Pyramide, 75012 Paris',
        rating: 4.5,
        reviewCount: 898,
        priceLevel: 1,
        ambianceTags: ['nature', 'familial', 'verdoyant'],
        musicTags: ['aucun'],
        styleTags: ['jardin botanique', 'papillons', 'aires de jeux'],
      ),
      Place(
        id: '26d96505-1716-46fe-93c7-a03857e02ea1',
        name: 'Parc Monceau',
        type: PlaceType.parc,
        latitude: 48.879684,
        longitude: 2.308955,
        address: '35 Bd de Courcelles, 75008 Paris',
        rating: 4.6,
        reviewCount: 963,
        priceLevel: 1,
        ambianceTags: ['romantique', 'verdoyant', 'calme'],
        musicTags: ['aucun'],
        styleTags: ['colonnades', 'statues', 'plan deau'],
      ),
      Place(
        id: 'fd85718d-16bd-4406-bfee-ac69ac2c5c47',
        name: 'Parc Montsouris',
        type: PlaceType.parc,
        latitude: 48.822672,
        longitude: 2.33766,
        address: '2 Rue Gazan, 75014 Paris',
        rating: 4.6,
        reviewCount: 721,
        priceLevel: 1,
        ambianceTags: ['paisible', 'verdoyant', 'familial'],
        musicTags: ['aucun'],
        styleTags: ['vallonne', 'lac', 'allees boisees'],
      ),
      Place(
        id: 'd8340397-a6ca-47a2-b7f8-590a864c1aaf',
        name: 'Square des Batignolles',
        type: PlaceType.parc,
        latitude: 48.8875,
        longitude: 2.316479,
        address: '144bis Rue Cardinet, 75017 Paris',
        rating: 4.5,
        reviewCount: 841,
        priceLevel: 1,
        ambianceTags: ['romantique', 'paisible', 'verdoyant'],
        musicTags: ['aucun'],
        styleTags: ['style paysager', 'lac', 'cascade'],
      ),
      Place(
        id: '1f452fd7-06b0-4f68-bce0-63ca5ade35bc',
        name: 'Square du Vert-Galant',
        type: PlaceType.parc,
        latitude: 48.857487,
        longitude: 2.3401677,
        address: '15 Place du Pont Neuf, 75001 Paris',
        rating: 4.5,
        reviewCount: 1539,
        priceLevel: 1,
        ambianceTags: ['romantique', 'paisible'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '2aca08e4-3bcb-4214-a741-ab83c62488a1',
        name: 'Square Saint-Lambert',
        type: PlaceType.parc,
        latitude: 48.842244,
        longitude: 2.296935,
        address: '2 Rue Jean Formige, 75015 Paris',
        rating: 4.3,
        reviewCount: 312,
        priceLevel: 1,
        ambianceTags: ['familial', 'verdoyant', 'local'],
        musicTags: ['aucun'],
        styleTags: ['square', 'carrousel', 'aires de jeux'],
      ),
      // ===================== ADRESSES & SPOTS PHOTO =====================
      Place(
        id: '27ea6453-4037-4cc0-86a1-7d32cd8bcb32',
        name: 'Arénes de Lutèce',
        type: PlaceType.adresse,
        latitude: 48.845116,
        longitude: 2.3528366,
        address: '49 Rue Monge, 75005 Paris',
        rating: 4.2,
        reviewCount: 5726,
        priceLevel: 1,
        ambianceTags: ['historique', 'paisible', 'insolite'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '38a1e32e-2909-4fb4-b8d5-938d3b9d93c2',
        name: 'Atelier des Lumières',
        type: PlaceType.adresse,
        latitude: 48.86191,
        longitude: 2.37021,
        address: '38 Rue Saint-Maur, 75011 Paris',
        rating: 4.7,
        reviewCount: 12000,
        priceLevel: 1,
        ambianceTags: ['immersive', 'digital'],
        musicTags: ['ambient'],
        styleTags: [],
      ),
      Place(
        id: '143078c7-f1ed-4a2b-a314-46f87737f8a8',
        name: 'Bercy Village',
        type: PlaceType.adresse,
        latitude: 48.83284,
        longitude: 2.386188,
        address: '28 Rue Francois Truffaut, 75012 Paris',
        rating: 4.4,
        reviewCount: 934,
        priceLevel: 1,
        ambianceTags: ['convivial', 'verdoyant', 'anime'],
        musicTags: ['aucun'],
        styleTags: ['village pave', 'anciens chais', 'boutiques'],
      ),
      Place(
        id: 'd9b87969-143a-441f-b9f7-081b3a8bde91',
        name: 'Bunker de la Gare de l\'Est',
        type: PlaceType.adresse,
        latitude: 48.8768146,
        longitude: 2.3591978,
        address: 'Place du 11 Novembre 1918, 75010 Paris',
        rating: 4.7,
        reviewCount: 595,
        priceLevel: 1,
        ambianceTags: ['mystérieux', 'historique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '0fb257b6-dad3-42ee-9ce3-a5fdce63b417',
        name: 'Cité du Figuier',
        type: PlaceType.adresse,
        latitude: 48.8659278,
        longitude: 2.3785695,
        address: 'Cité du Figuier, 75011 Paris',
        rating: 4.5,
        reviewCount: 2034,
        priceLevel: 1,
        ambianceTags: ['paisible', 'bucolique', 'caché'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'a15000ca-6ee3-4b4a-b76c-e5185f057d84',
        name: 'Cité Florale',
        type: PlaceType.adresse,
        latitude: 48.8227065,
        longitude: 2.3453748,
        address: 'Cité Florale, 75013 Paris',
        rating: 4.4,
        reviewCount: 330,
        priceLevel: 1,
        ambianceTags: ['bucolique', 'paisible', 'charmant'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '2d191576-3161-4c6c-a2a5-d40e09a603a6',
        name: 'Deyrolle',
        type: PlaceType.adresse,
        latitude: 48.8565331,
        longitude: 2.3264245,
        address: '46 Rue du Bac, 75007 Paris',
        rating: 4.7,
        reviewCount: 2115,
        priceLevel: 1,
        ambianceTags: ['insolite', 'feutré', 'curieux'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '53fa8672-16d5-46fd-a447-37b9d1020638',
        name: 'Galerie Véro-Dodat',
        type: PlaceType.adresse,
        latitude: 48.8628173,
        longitude: 2.3402386,
        address: '19 Rue Jean-Jacques Rousseau, 75001 Paris',
        rating: 4.4,
        reviewCount: 493,
        priceLevel: 1,
        ambianceTags: ['historique', 'élégant', 'calme'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '9d009d7a-b247-4c5f-8b21-a71d5b1bd237',
        name: 'Librairie Galignani',
        type: PlaceType.adresse,
        latitude: 48.865062,
        longitude: 2.328547,
        address: '224 Rue de Rivoli, 75001 Paris',
        rating: 4.5,
        reviewCount: 365,
        priceLevel: 1,
        ambianceTags: ['raffine', 'historique', 'calme'],
        musicTags: ['aucun'],
        styleTags: ['librairie anglaise', 'boiseries 1930', 'Tuileries'],
      ),
      Place(
        id: '95e60197-deeb-42d3-9f97-1c58b3a68493',
        name: 'Librairie Jousseaume',
        type: PlaceType.adresse,
        latitude: 48.866961,
        longitude: 2.339886,
        address: '45-47 Gal Vivienne, 75002 Paris',
        rating: 4.6,
        reviewCount: 245,
        priceLevel: 1,
        ambianceTags: ['historique', 'romantique', 'feutre'],
        musicTags: ['aucun'],
        styleTags: ['librairie 1826', 'Galerie Vivienne', 'livres anciens'],
      ),
      Place(
        id: '10d4446b-8c55-4b45-9809-64183dfba808',
        name: 'Maison Loo (Pagode)',
        type: PlaceType.adresse,
        latitude: 48.8767766,
        longitude: 2.3077965,
        address: '48 Rue de Courcelles, 75008 Paris',
        rating: 4.2,
        reviewCount: 330,
        priceLevel: 1,
        ambianceTags: ['insolite', 'dépaysant', 'historique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'f8ad7490-db3e-4854-82a9-c0aea28a97ec',
        name: 'Musée Albert-Kahn',
        type: PlaceType.adresse,
        latitude: 48.8412532,
        longitude: 2.2284942,
        address: '2 Rue du Port, 92100 Boulogne-Billancourt',
        rating: 4.6,
        reviewCount: 5113,
        priceLevel: 1,
        ambianceTags: ['dépaysant', 'paisible', 'contemplatif'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '05c41474-da88-4ee4-9741-6c931982ecee',
        name: 'Musée des Arts Forains',
        type: PlaceType.adresse,
        latitude: 48.83391,
        longitude: 2.38621,
        address: '53 Avenue des Terroirs de France, 75012 Paris',
        rating: 4.7,
        reviewCount: 3000,
        priceLevel: 1,
        ambianceTags: ['vintage', 'fairground'],
        musicTags: ['lounge'],
        styleTags: [],
      ),
      Place(
        id: '7656b8a4-551b-490c-80c5-6871903f8fe4',
        name: 'Musée du cirque Bouglione',
        type: PlaceType.adresse,
        latitude: 48.863308,
        longitude: 2.367233,
        address: '110 Rue Amelot, 75011 Paris',
        rating: 4.3,
        reviewCount: 5113,
        priceLevel: 1,
        ambianceTags: ['nostalgique', 'insolite'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: '37878f40-bf8f-4481-9f66-ca6de8f482bc',
        name: 'Palais Garnier',
        type: PlaceType.adresse,
        latitude: 48.87197,
        longitude: 2.331601,
        address: 'Pl. de l\'Opera, 75009 Paris',
        rating: 4.7,
        reviewCount: 817,
        priceLevel: 1,
        ambianceTags: ['spectaculaire', 'emblematique', 'feerique'],
        musicTags: ['aucun'],
        styleTags: ['opera', 'grand escalier', 'plafond Chagall'],
      ),
      Place(
        id: 'c3acac3c-1c55-4368-aac3-7f8a470b6f3c',
        name: 'Passage du Grand Cerf',
        type: PlaceType.adresse,
        latitude: 48.864669,
        longitude: 2.350091,
        address: '145 Rue St Denis, 75002 Paris',
        rating: 4.5,
        reviewCount: 546,
        priceLevel: 1,
        ambianceTags: ['raffine', 'artisanal', 'historique'],
        musicTags: ['aucun'],
        styleTags: ['haute verriere', 'createurs', '1825'],
      ),
      Place(
        id: 'fe529d6f-f219-48be-8489-cedc6565f381',
        name: 'Passage secret rue des Anglais',
        type: PlaceType.adresse,
        latitude: 48.850652,
        longitude: 2.3475339,
        address: 'Rue des Anglais, 75005 Paris',
        rating: 4.3,
        reviewCount: 2115,
        priceLevel: 1,
        ambianceTags: ['mystérieux', 'ludique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'e2fc9386-284d-4fe8-ba49-189f78450a14',
        name: 'Piscine Roger Le Gall (créneaux naturistes)',
        type: PlaceType.adresse,
        latitude: 48.841751,
        longitude: 2.4128012,
        address: '34 Bd Carnot, 75012 Paris',
        rating: 3.4,
        reviewCount: 1584,
        priceLevel: 1,
        ambianceTags: ['insolite', 'décontracté'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'cf75678f-9d35-4e24-8d71-a1ecc4755e7d',
        name: 'Quartier de la Mouzaéa',
        type: PlaceType.adresse,
        latitude: 48.8810751,
        longitude: 2.3938225,
        address: 'Quartier de la Mouzaéa, 75019 Paris',
        rating: 4.4,
        reviewCount: 2017,
        priceLevel: 1,
        ambianceTags: ['bucolique', 'paisible', 'romantique'],
        musicTags: [],
        styleTags: [],
      ),
      Place(
        id: 'd8e62bd8-0c73-48b0-bbe3-305e8f5a7454',
        name: 'Shakespeare and Company',
        type: PlaceType.adresse,
        latitude: 48.852563,
        longitude: 2.34713,
        address: '37 Rue de la Bucherie, 75005 Paris',
        rating: 4.6,
        reviewCount: 613,
        priceLevel: 1,
        ambianceTags: ['mythique', 'romantique', 'feerique'],
        musicTags: ['aucun'],
        styleTags: ['librairie anglaise', 'face Notre-Dame', 'legendaire'],
      ),
      Place(
        id: 'c41b48ab-a1f1-401a-a842-7c81df0e9c2b',
        name: 'Temple Ganesh',
        type: PlaceType.adresse,
        latitude: 48.8859431,
        longitude: 2.3606865,
        address: '17 Rue Pajol, 75018 Paris',
        rating: 4.5,
        reviewCount: 604,
        priceLevel: 1,
        ambianceTags: ['spirituel', 'dépaysant', 'paisible'],
        musicTags: [],
        styleTags: [],
      ),
    ].map(_withMockMedia).toList();
  }

  /// Enrichit chaque lieu (medias + donnees derivees pour les filtres avances).
  ///
  /// >>> POINT DE BRANCHEMENT BACKEND <<<
  /// Le prix reel, la frequentation et les horaires d'affluence sont ici
  /// DERIVES de façon deterministe a partir du type/prix/tags (heuristiques
  /// de demo). Quand un backend sera branche, ces valeurs viendront de vraies
  /// donnees (ex: Google Popular Times, tickets moyens, etc.).
  Place _withMockMedia(Place p) {
    final ambiance = [...p.ambianceTags];
    // "calme" : intimiste/cosy sans cote festif/anime.
    if ((ambiance.contains('intimiste') || ambiance.contains('cosy')) &&
        !ambiance.contains('festif') &&
        !ambiance.contains('animé')) {
      ambiance.add('calme');
    }

    final style = [...p.styleTags];
    // "luxueux" : haut de gamme (prix 4, palace ou premium).
    if (p.priceLevel >= 4 || style.contains('palace') || p.isPremium) {
      if (!style.contains('luxueux')) style.add('luxueux');
    }

    // Lien Google Maps REEL (recherche par nom + adresse) : ouvre la vraie
    // fiche du lieu avec ses avis reels, photos et itineraire.
    final mapsUrl = 'https://www.google.com/maps/search/?api=1&query='
        '${Uri.encodeComponent('${p.name} ${p.address}')}';
    // Hashtag Instagram (best-effort a partir du nom).
    final slug = p.name
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]'), '');
    final instagramUrl = 'https://www.instagram.com/explore/tags/$slug/';

    return Place(
      id: p.id,
      name: p.name,
      type: p.type,
      latitude: p.latitude,
      longitude: p.longitude,
      address: p.address,
      rating: p.rating,
      reviewCount: p.reviewCount,
      priceLevel: p.priceLevel,
      ambianceTags: ambiance,
      musicTags: p.musicTags,
      styleTags: style,
      photos: _photosForPlace(p.id),
      videos: const [],
      isPremium: p.isPremium,
      averagePrice: _averagePrice(p),
      crowdTags: _crowd(p),
      peakTags: _peak(p),
      mapsUrl: mapsUrl,
      instagramUrl: instagramUrl,
      // websiteUrl laisse a null : on ne fabrique pas de faux site.
      // Extraits "Instagram" : utilise _igVideos[id] si rempli, sinon demo.
      instagramVideos: _igVideosForPlace(p.id),
      // Nos interviews maison : rempli via _originalVideosMap si disponible.
      originalVideos: _originalVideosForPlace(p.id),
      // Extraits d'avis Google : specifiques si disponibles, sinon generes.
      reviews: _reviewSamples[p.id] ?? _generateReviews(p),
    );
  }

  /// Prix moyen reel (€) derive du type et du niveau de prix, avec variation.
  int _averagePrice(Place p) {
    const barTiers = [15, 25, 45, 70];
    const restoTiers = [20, 35, 60, 110];
    const hotelTiers = [90, 150, 250, 430];
    const rooftopTiers = [15, 25, 45, 70];
    const parcTiers = [0, 5, 12, 20];
    const adresseTiers = [0, 0, 0, 0];
    final tiers = switch (p.type) {
      PlaceType.bar => barTiers,
      PlaceType.restaurant => restoTiers,
      PlaceType.hotel => hotelTiers,
      PlaceType.rooftop => rooftopTiers,
      PlaceType.parc => parcTiers,
      PlaceType.adresse => adresseTiers,
    };
    final base = tiers[(p.priceLevel - 1).clamp(0, 3)];
    if (base == 0) return 0;
    final jitter = p.id.hashCode.abs() % 11; // 0..10
    return base + jitter;
  }

  /// Frequentation type derivee de l'ambiance / du style.
  List<String> _crowd(Place p) {
    final s = <String>{};
    final a = p.ambianceTags;
    final st = p.styleTags;
    if (st.contains('club') || a.contains('festif') || a.contains('animé')) {
      s.addAll(['20-30 ans', 'étudiants']);
    }
    if (a.contains('business') ||
        st.contains('gastronomique') ||
        st.contains('palace')) {
      s.add('business');
    }
    if (st.contains('vue Tour Eiffel') ||
        st.contains('palace') ||
        st.contains('rooftop') ||
        p.isPremium) {
      s.add('touristes');
    }
    if (a.contains('familial')) s.add('familles');
    if (a.contains('cosy') ||
        a.contains('intimiste') ||
        st.contains('bistrot') ||
        st.contains('vins nature')) {
      s.add('locaux');
    }
    if (st.contains('cocktails') ||
        a.contains('branché') ||
        a.contains('chic')) {
      s.addAll(['after-work', '30-45 ans']);
    }
    // Parcs et adresses : toujours familles + locaux par défaut.
    if (p.type == PlaceType.parc || p.type == PlaceType.adresse) {
      s.add('familles');
      if (p.rating >= 4.5 ||
          p.styleTags.contains('vue Tour Eiffel') ||
          p.styleTags.contains('instagrammable')) {
        s.add('touristes');
      }
    }
    if (s.isEmpty) s.add('locaux');
    return s.toList();
  }

  /// Creneaux d'affluence derives du type et du style.
  List<String> _peak(Place p) {
    final s = <String>{};
    switch (p.type) {
      case PlaceType.bar:
        s.addAll(['after-work', 'soir', 'week-end']);
        if (p.styleTags.contains('club') || p.ambianceTags.contains('festif')) {
          s.add('nuit');
        }
        break;
      case PlaceType.restaurant:
        s.addAll(['midi', 'soir']);
        if (p.styleTags.contains('brunch')) s.addAll(['matin', 'week-end']);
        break;
      case PlaceType.hotel:
        s.addAll(['soir', 'nuit', 'week-end']);
        break;
      case PlaceType.rooftop:
        s.addAll(['after-work', 'soir', 'week-end']);
        if (p.ambianceTags.contains('festif')) s.add('nuit');
        break;
      case PlaceType.parc:
        s.addAll(['matin', 'après-midi', 'week-end']);
        if (p.ambianceTags.contains('animé')) s.add('soir');
        break;
      case PlaceType.adresse:
        s.addAll(['matin', 'après-midi', 'week-end']);
        break;
    }
    if (p.styleTags.contains('terrasse') || p.styleTags.contains('jardin')) {
      s.add('après-midi');
    }
    return s.toList();
  }

  // ---- Génération d'avis Google pour les lieux sans entrée dans _reviewSamples ----

  /// Avis d'un lieu : extraits Google specifiques (_reviewSamples) si
  /// disponibles, sinon avis generes coherents avec le type/la note.
  ///
  /// Expose pour que PlacesService (chemin Supabase) affiche AUSSI des avis
  /// sur les fiches, et pas seulement le mode mock local.
  static List<Review> reviewsForPlace(Place p) =>
      _reviewSamples[p.id] ?? _generateReviews(p);

  static const _reviewAuthors = [
    'Sophie M.', 'Thomas L.', 'Julie B.', 'Kevin R.', 'Lea H.',
    'Marc D.', 'Chloe P.', 'Antoine D.', 'Noemie C.', 'Pierre V.',
    'Margot S.', 'Romain F.', 'Sarah N.', 'Julien K.', 'Emma R.',
    'Lucas P.', 'Ines T.', 'Baptiste M.', 'Amandine D.', 'Thibault R.',
  ];
  static const _reviewTimes = [
    'il y a 4 jours', 'il y a 1 semaine', 'il y a 2 semaines',
    'il y a 3 semaines', 'il y a 1 mois', 'il y a 6 semaines',
    'il y a 2 mois', 'il y a 3 mois', 'il y a 4 mois', 'il y a 5 mois',
  ];
  static const _reviewRatings = [5.0, 4.0, 5.0, 5.0, 4.0];

  static List<String> _textsForType(PlaceType type) {
    switch (type) {
      case PlaceType.bar:
        return [
          'Super ambiance et cocktails au top. On y retourne sans hesiter !',
          'Endroit tres sympa, staff accueillant. Ideal pour un apero branché.',
          "L'un des meilleurs bars du quartier. Cocktails creatifs et delicieux.",
          'Cadre chaleureux, service rapide et ambiance au rendez-vous. Tres bonne adresse.',
          "Coup de coeur ! Belle carte de cocktails et atmosphere unique. A recommander.",
          'Bar tres agreable, bon rapport qualite-prix. Le personnel est adorable.',
          "Endroit incontournable du quartier. Cocktails inventifs et decor soigne.",
          'Tres bonne soiree, musique parfaite et service aux petits soins.',
        ];
      case PlaceType.restaurant:
        return [
          'Excellent rapport qualite-prix, cuisine savoureuse et service attentionne.',
          "Un vrai regal ! Chaque plat est soigne, l'ambiance est parfaite.",
          'Super resto, portions genereuses et qualite au rendez-vous. On reviendra !',
          'Service impeccable et cuisine delicieuse. Une des meilleures tables du quartier.',
          'Tres bonne experience, produits frais et chef talentueux. A tester absolument.',
          'Cadre agreable et plats savoureux. Le service est rapide et souriant.',
          'Restaurant exceptionnel, carte variee et prix raisonnables. Coup de coeur !',
          'Tres bonne adresse, ambiance chaleureuse et cuisine de qualite. On recommande.',
        ];
      case PlaceType.hotel:
        return [
          'Hotel magnifique, chambre confortable et personnel tres accueillant.',
          'Sejour parfait, emplacement ideal et standing irreprochable. On recommande.',
          'Excellent hotel, service impeccable et cadre exceptionnel. Une vraie reussite.',
          'Tres bel etablissement, proprete parfaite et petit-dejeuner delicieux.',
          'Hotel au top ! Vue magnifique, chambre spacieuse et staff aux petits soins.',
          'Cadre luxueux et service de qualite. Chambre bien agencee et tres propre.',
          'Hotel ideal pour un sejour a Paris. Situation parfaite et accueil chaleureux.',
          'Sejour inoubliable dans cet hotel. Design soigne et confort exceptionnel.',
        ];
      case PlaceType.rooftop:
        return [
          "Vue a couper le souffle ! Cocktails excellents et ambiance magique.",
          'Panorama splendide sur Paris. Parfait au coucher du soleil, incontournable.',
          'Rooftop exceptionnel, vue panoramique et cocktails au top. A faire !',
          'Experience unique avec vue imprenable. Service sympa et ambiance festive.',
          'Le meilleur rooftop du quartier. Vue magnifique et staff accueillant.',
          "Soiree parfaite avec vue exceptionnelle sur les toits de Paris.",
          'Endroit magique au coucher du soleil. Cocktails creatifs et ambiance au top.',
          'Vue panoramique a 360 degres. On y retourne des que possible !',
        ];
      case PlaceType.parc:
        return [
          'Endroit magnifique pour se ressourcer. Parfait pour un pique-nique.',
          'Oasis de verdure au coeur de Paris. Calme et tres agreable en toute saison.',
          'Beau parc, bien entretenu et spacieux. Ideal pour une balade ou se detendre.',
          "Un de mes parcs favoris a Paris. Paysages sublimes et ambiance sereine.",
          "Super endroit pour s'evader du bruit de la ville. Tres bien entretenu.",
          'Parc magnifique, ideal pour le sport ou la detente. Toujours agreable.',
          'Verdure superbe et atmosphere apaisante. Lieu de promenade ideal.',
          'Cadre naturel exceptionnel en plein Paris. Parfait pour se ressourcer.',
        ];
      case PlaceType.adresse:
        return [
          'Endroit incroyable et tres photogenique. A visiter absolument !',
          "Lieu magique plein de charme et d'histoire. On s'y attarde volontiers.",
          'Spot magnifique, vraiment unique a Paris. Les photos ne rendent pas justice.',
          'Lieu incontournable, atmosphere particuliere et cadre exceptionnel.',
          "Super decouverte ! Endroit authentique et hors des sentiers battus.",
          'Adresse charmante que tout le monde devrait connaitre a Paris.',
          'Lieu unique qui merite vraiment le detour. Atmosphere magique garantie.',
          'Endroit authentique et plein de charme. Une belle decouverte parisienne.',
        ];
    }
  }

  static List<Review> _generateReviews(Place p) {
    final hash = p.id.hashCode.abs();
    final texts = _textsForType(p.type);
    return [
      for (var i = 0; i < 5; i++)
        Review(
          author: _reviewAuthors[(hash + i * 7) % _reviewAuthors.length],
          rating: _reviewRatings[i % _reviewRatings.length],
          text: texts[(hash + i * 3) % texts.length],
          relativeTime: _reviewTimes[(hash + i * 11) % _reviewTimes.length],
        ),
    ];
  }

  // ---- Styles de collection mock ----
  List<CollectionStyle> getStyles() {
    return const [
      CollectionStyle(
        id: 's1',
        name: 'Nightlife Chic',
        primaryColor: Color(0xFF6C5CE7),
        iconStyle: 'bold',
        description: 'Rooftops, speakeasies et cocktails haut de gamme.',
      ),
      CollectionStyle(
        id: 's2',
        name: 'Rooftop Chill',
        primaryColor: Color(0xFF74B9FF),
        iconStyle: 'minimal',
        description: 'Vues degagees, terrasses et ambiances detendues.',
      ),
      CollectionStyle(
        id: 's3',
        name: 'Hidden Gems',
        primaryColor: Color(0xFF1E5631),
        iconStyle: 'outline',
        description: 'Adresses confidentielles loin des foules.',
      ),
    ];
  }

  /// Cartes publiques d'influenceurs (accessibles via un code).
  /// Ce sont des collections riches (> 10 lieux), stylees, verifiees.
  List<UserCollection> getInfluencerCollections() {
    final places = getPlaces();
    return [
      UserCollection(
        id: 'inf1',
        ownerName: 'Lea Martin',
        authorHandle: '@lea.inparis',
        isInfluencer: true,
        coverImage: 'https://picsum.photos/seed/leacover/900/450',
        code: 'LEA-PARIS-2024',
        style: const CollectionStyle(
          id: 'infs1',
          name: 'Lea a Paris',
          primaryColor: Color(0xFFE84393),
          iconStyle: 'bold',
          description: 'Mes adresses prefereees a Paris - rooftops, brunchs & spots photo.',
        ),
        places: places
            .where((p) =>
                p.styleTags.contains('rooftop') ||
                p.styleTags.contains('brunch') ||
                p.ambianceTags.contains('branché'))
            .take(14)
            .toList(),
      ),
      UserCollection(
        id: 'inf2',
        ownerName: 'Marco Rossi',
        authorHandle: '@chefmarco',
        isInfluencer: true,
        coverImage: 'https://picsum.photos/seed/marcocover/900/450',
        code: 'MARCO-EATS-7788',
        style: const CollectionStyle(
          id: 'infs2',
          name: "Marco's Food Map",
          primaryColor: Color(0xFFB71C1C),
          iconStyle: 'outline',
          description: 'The best restaurants in Paris, picked by a chef.',
        ),
        places:
            places.where((p) => p.type == PlaceType.restaurant).take(13).toList(),
      ),
    ];
  }

  /// Collections appartenant a l'utilisateur courant (mock).
  List<UserCollection> getUserCollections() {
    final places = getPlaces();
    final styles = getStyles();
    return [
      UserCollection(
        id: 'c1',
        ownerName: 'Alex',
        code: 'PARIS-CHIC-1234',
        style: styles[0],
        places: places.where((p) => p.type == PlaceType.bar).take(5).toList(),
      ),
      UserCollection(
        id: 'c2',
        ownerName: 'Alex',
        code: 'ROOFTOP-COOL-5678',
        style: styles[1],
        places: places
            .where((p) => p.styleTags.contains('rooftop'))
            .take(5)
            .toList(),
      ),
    ];
  }
}
