import 'package:flutter/material.dart';

import '../models/collection_style.dart';
import '../models/place.dart';
import '../models/user_collection.dart';

/// Fournit des donnees mockees (lieux, styles, collections).
///
/// >>> POINT DE BRANCHEMENT BACKEND <<<
/// Remplacer le contenu de cette classe par des appels HTTP (ex: dio/http)
/// renvoyant les memes modeles. La signature des methodes peut rester
/// identique (passer en `Future<...>` + async).
class MockDataService {
  // ---- Vocabulaire de tags (utilise par les filtres) ----
  // Plus la liste est riche, plus le filtrage est precis.

  /// Ambiance / atmosphere du lieu.
  static const List<String> ambianceOptions = [
    'calme',
    'chic',
    'cosy',
    'festif',
    'romantique',
    'business',
    'branché',
    'décontracté',
    'animé',
    'intimiste',
    'familial',
    'insolite',
  ];

  /// Frequentation / clientele type.
  static const List<String> crowdOptions = [
    '20-30 ans',
    '30-45 ans',
    'business',
    'touristes',
    'étudiants',
    'familles',
    'locaux',
    'after-work',
  ];

  /// Creneaux d'affluence reels.
  static const List<String> peakOptions = [
    'matin',
    'midi',
    'après-midi',
    'after-work',
    'soir',
    'nuit',
    'week-end',
  ];

  /// Style musical dominant.
  static const List<String> musicOptions = [
    'house',
    'jazz',
    'afro',
    'lounge',
    'pop',
    'techno',
    'soul',
    'funk',
    'latino',
    'rock',
  ];

  /// Style du lieu ET type de cuisine (regroupes pour un filtrage "par genre").
  static const List<String> styleOptions = [
    // Style de lieu
    'rooftop',
    'speakeasy',
    'terrasse',
    'vue Tour Eiffel',
    'cocktails',
    'vins nature',
    'bière artisanale',
    'club',
    'jardin',
    'péniche',
    'design',
    'boutique-hôtel',
    'palace',
    'luxueux',
    // Cuisine / genre
    'bistrot',
    'brasserie',
    'gastronomique',
    'brunch',
    'italien',
    'pizza',
    'japonais',
    'libanais',
    'indien',
    'thai',
    'vietnamien',
    'coréen',
    'mexicain',
    'burger',
    'vegan',
    'fruits de mer',
    'steakhouse',
    'crêperie',
  ];

  // Quelques placeholders. picsum = photos aleatoires stables (via seed).
  static String _photo(String seed) =>
      'https://picsum.photos/seed/$seed/800/600';

  // Videos de demo publiques (lisibles par video_player).
  static const String _sampleVideoA =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4';
  static const String _sampleVideoB =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4';

  /// Liste de lieux a Paris (bars, restaurants, hotels) bien categorises.
  List<Place> getPlaces() {
    return const [
      // ===================== BARS =====================
      Place(
        id: 'p01',
        name: 'Le Perchoir Marais',
        type: PlaceType.bar,
        latitude: 48.8629,
        longitude: 2.3640,
        address: '33 Rue de la Verrerie, 75004 Paris',
        rating: 4.5,
        reviewCount: 1820,
        priceLevel: 3,
        ambianceTags: ['chic', 'festif', 'branché'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'cocktails', 'vue Tour Eiffel'],
      ),
      Place(
        id: 'p02',
        name: 'Little Red Door',
        type: PlaceType.bar,
        latitude: 48.8632,
        longitude: 2.3622,
        address: '60 Rue Charlot, 75003 Paris',
        rating: 4.7,
        reviewCount: 940,
        priceLevel: 3,
        ambianceTags: ['chic', 'intimiste'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['speakeasy', 'cocktails'],
      ),
      Place(
        id: 'p03',
        name: 'Bar Hemingway (Ritz)',
        type: PlaceType.bar,
        latitude: 48.8681,
        longitude: 2.3284,
        address: '15 Place Vendome, 75001 Paris',
        rating: 4.6,
        reviewCount: 1200,
        priceLevel: 4,
        ambianceTags: ['chic', 'business', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['speakeasy', 'cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'p04',
        name: 'Le Comptoir General',
        type: PlaceType.bar,
        latitude: 48.8704,
        longitude: 2.3672,
        address: '80 Quai de Jemmapes, 75010 Paris',
        rating: 4.3,
        reviewCount: 5600,
        priceLevel: 2,
        ambianceTags: ['festif', 'décontracté', 'insolite'],
        musicTags: ['afro', 'house'],
        styleTags: ['terrasse', 'cocktails'],
      ),
      Place(
        id: 'p05',
        name: 'Le Bar du Plaza Athenee',
        type: PlaceType.bar,
        latitude: 48.8662,
        longitude: 2.3036,
        address: '25 Avenue Montaigne, 75008 Paris',
        rating: 4.5,
        reviewCount: 880,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'p06',
        name: 'Candelaria',
        type: PlaceType.bar,
        latitude: 48.8627,
        longitude: 2.3661,
        address: '52 Rue de Saintonge, 75003 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 3,
        ambianceTags: ['branché', 'animé'],
        musicTags: ['latino', 'house'],
        styleTags: ['speakeasy', 'cocktails', 'mexicain'],
      ),
      Place(
        id: 'p07',
        name: 'Le Syndicat',
        type: PlaceType.bar,
        latitude: 48.8718,
        longitude: 2.3530,
        address: '51 Rue du Faubourg Saint-Denis, 75010 Paris',
        rating: 4.5,
        reviewCount: 1300,
        priceLevel: 3,
        ambianceTags: ['branché', 'intimiste'],
        musicTags: ['soul', 'funk'],
        styleTags: ['cocktails', 'speakeasy'],
      ),
      Place(
        id: 'p08',
        name: 'Experimental Cocktail Club',
        type: PlaceType.bar,
        latitude: 48.8662,
        longitude: 2.3486,
        address: '37 Rue Saint-Sauveur, 75002 Paris',
        rating: 4.4,
        reviewCount: 1750,
        priceLevel: 3,
        ambianceTags: ['animé', 'branché'],
        musicTags: ['house', 'funk'],
        styleTags: ['cocktails', 'speakeasy'],
      ),
      Place(
        id: 'p09',
        name: 'La Belle Hortense',
        type: PlaceType.bar,
        latitude: 48.8570,
        longitude: 2.3588,
        address: '31 Rue Vieille du Temple, 75004 Paris',
        rating: 4.3,
        reviewCount: 640,
        priceLevel: 2,
        ambianceTags: ['cosy', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['vins nature', 'bistrot'],
      ),
      Place(
        id: 'p10',
        name: 'Septime La Cave',
        type: PlaceType.bar,
        latitude: 48.8537,
        longitude: 2.3805,
        address: '3 Rue Basfroi, 75011 Paris',
        rating: 4.5,
        reviewCount: 720,
        priceLevel: 2,
        ambianceTags: ['cosy', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['vins nature'],
      ),
      Place(
        id: 'p11',
        name: 'BrewDog Paris',
        type: PlaceType.bar,
        latitude: 48.8602,
        longitude: 2.3705,
        address: '11 Rue Amelot, 75011 Paris',
        rating: 4.2,
        reviewCount: 2400,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'animé'],
        musicTags: ['rock', 'pop'],
        styleTags: ['bière artisanale', 'terrasse'],
      ),
      Place(
        id: 'p12',
        name: 'Rosa Bonheur',
        type: PlaceType.bar,
        latitude: 48.8800,
        longitude: 2.3830,
        address: '2 Allee de la Cascade, 75019 Paris',
        rating: 4.2,
        reviewCount: 6200,
        priceLevel: 2,
        ambianceTags: ['festif', 'familial', 'décontracté'],
        musicTags: ['pop', 'latino'],
        styleTags: ['terrasse', 'jardin'],
      ),
      Place(
        id: 'p13',
        name: 'Rex Club',
        type: PlaceType.bar,
        latitude: 48.8704,
        longitude: 2.3470,
        address: '5 Boulevard Poissonniere, 75002 Paris',
        rating: 4.4,
        reviewCount: 3800,
        priceLevel: 3,
        ambianceTags: ['festif', 'animé'],
        musicTags: ['techno', 'house'],
        styleTags: ['club'],
      ),
      Place(
        id: 'p14',
        name: 'Sacre Rooftop',
        type: PlaceType.bar,
        latitude: 48.8867,
        longitude: 2.3431,
        address: '18e arrondissement, 75018 Paris',
        rating: 4.2,
        reviewCount: 410,
        priceLevel: 2,
        ambianceTags: ['festif', 'romantique'],
        musicTags: ['house', 'pop'],
        styleTags: ['rooftop', 'terrasse', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p15',
        name: 'Cravan',
        type: PlaceType.bar,
        latitude: 48.8556,
        longitude: 2.3401,
        address: '17 Rue Jean de la Fontaine, 75016 Paris',
        rating: 4.6,
        reviewCount: 520,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['speakeasy', 'cocktails'],
      ),
      Place(
        id: 'p16',
        name: 'Bisou',
        type: PlaceType.bar,
        latitude: 48.8615,
        longitude: 2.3672,
        address: '15 Boulevard du Temple, 75003 Paris',
        rating: 4.5,
        reviewCount: 980,
        priceLevel: 2,
        ambianceTags: ['branché', 'intimiste'],
        musicTags: ['soul'],
        styleTags: ['cocktails'],
      ),

      // ===================== RESTAURANTS =====================
      Place(
        id: 'p17',
        name: 'Septime',
        type: PlaceType.restaurant,
        latitude: 48.8536,
        longitude: 2.3819,
        address: '80 Rue de Charonne, 75011 Paris',
        rating: 4.6,
        reviewCount: 3100,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'p18',
        name: 'Bouillon Pigalle',
        type: PlaceType.restaurant,
        latitude: 48.8823,
        longitude: 2.3375,
        address: '22 Boulevard de Clichy, 75018 Paris',
        rating: 4.4,
        reviewCount: 14800,
        priceLevel: 1,
        ambianceTags: ['festif', 'familial', 'décontracté'],
        musicTags: ['pop'],
        styleTags: ['bistrot', 'brunch'],
      ),
      Place(
        id: 'p19',
        name: 'Le Jules Verne',
        type: PlaceType.restaurant,
        latitude: 48.8582,
        longitude: 2.2945,
        address: 'Tour Eiffel, Avenue Gustave Eiffel, 75007 Paris',
        rating: 4.5,
        reviewCount: 2200,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p20',
        name: 'Holybelly 5',
        type: PlaceType.restaurant,
        latitude: 48.8717,
        longitude: 2.3592,
        address: '5 Rue Lucien Sampaix, 75010 Paris',
        rating: 4.5,
        reviewCount: 4300,
        priceLevel: 2,
        ambianceTags: ['cosy', 'décontracté'],
        musicTags: ['pop', 'soul'],
        styleTags: ['brunch'],
      ),
      Place(
        id: 'p21',
        name: 'Clamato',
        type: PlaceType.restaurant,
        latitude: 48.8534,
        longitude: 2.3812,
        address: '80 Rue de Charonne, 75011 Paris',
        rating: 4.4,
        reviewCount: 1500,
        priceLevel: 3,
        ambianceTags: ['cosy', 'branché'],
        musicTags: ['jazz'],
        styleTags: ['fruits de mer', 'vins nature'],
      ),
      Place(
        id: 'p22',
        name: "Le Relais de l'Entrecote",
        type: PlaceType.restaurant,
        latitude: 48.8707,
        longitude: 2.3076,
        address: '15 Rue Marbeuf, 75008 Paris',
        rating: 4.2,
        reviewCount: 9200,
        priceLevel: 2,
        ambianceTags: ['business', 'animé'],
        musicTags: ['lounge'],
        styleTags: ['steakhouse'],
      ),
      Place(
        id: 'p23',
        name: 'Brasserie Lipp',
        type: PlaceType.restaurant,
        latitude: 48.8540,
        longitude: 2.3331,
        address: '151 Boulevard Saint-Germain, 75006 Paris',
        rating: 4.1,
        reviewCount: 5200,
        priceLevel: 3,
        ambianceTags: ['business', 'chic'],
        musicTags: ['jazz'],
        styleTags: ['brasserie', 'terrasse'],
      ),
      Place(
        id: 'p24',
        name: 'East Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8519,
        longitude: 2.3782,
        address: '133 Rue du Faubourg Saint-Antoine, 75011 Paris',
        rating: 4.4,
        reviewCount: 11200,
        priceLevel: 2,
        ambianceTags: ['animé', 'familial', 'festif'],
        musicTags: ['pop'],
        styleTags: ['italien', 'pizza'],
      ),
      Place(
        id: 'p25',
        name: 'Pink Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8819,
        longitude: 2.3375,
        address: '20bis Rue de Douai, 75009 Paris',
        rating: 4.5,
        reviewCount: 13900,
        priceLevel: 3,
        ambianceTags: ['branché', 'animé'],
        musicTags: ['pop', 'soul'],
        styleTags: ['italien', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'p26',
        name: 'Kodawari Ramen',
        type: PlaceType.restaurant,
        latitude: 48.8530,
        longitude: 2.3360,
        address: '29 Rue Mazarine, 75006 Paris',
        rating: 4.4,
        reviewCount: 4100,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'animé', 'insolite'],
        musicTags: ['pop'],
        styleTags: ['japonais'],
      ),
      Place(
        id: 'p27',
        name: 'Sushi B',
        type: PlaceType.restaurant,
        latitude: 48.8676,
        longitude: 2.3360,
        address: '5 Rue Rameau, 75002 Paris',
        rating: 4.7,
        reviewCount: 560,
        priceLevel: 4,
        ambianceTags: ['chic', 'intimiste'],
        musicTags: ['lounge'],
        styleTags: ['japonais', 'gastronomique'],
        isPremium: true,
      ),
      Place(
        id: 'p28',
        name: 'Liza',
        type: PlaceType.restaurant,
        latitude: 48.8676,
        longitude: 2.3399,
        address: '14 Rue de la Banque, 75002 Paris',
        rating: 4.4,
        reviewCount: 2300,
        priceLevel: 3,
        ambianceTags: ['cosy', 'romantique'],
        musicTags: ['lounge', 'latino'],
        styleTags: ['libanais'],
      ),
      Place(
        id: 'p29',
        name: 'Desi Road',
        type: PlaceType.restaurant,
        latitude: 48.8543,
        longitude: 2.3330,
        address: '14 Rue Dauphine, 75006 Paris',
        rating: 4.3,
        reviewCount: 1900,
        priceLevel: 2,
        ambianceTags: ['cosy', 'familial'],
        musicTags: ['latino'],
        styleTags: ['indien'],
      ),
      Place(
        id: 'p30',
        name: 'Lao Siam',
        type: PlaceType.restaurant,
        latitude: 48.8722,
        longitude: 2.3826,
        address: '49 Rue de Belleville, 75019 Paris',
        rating: 4.4,
        reviewCount: 3600,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'familial', 'animé'],
        musicTags: ['pop'],
        styleTags: ['thai'],
      ),
      Place(
        id: 'p31',
        name: 'Pho 14',
        type: PlaceType.restaurant,
        latitude: 48.8270,
        longitude: 2.3590,
        address: '129 Avenue de Choisy, 75013 Paris',
        rating: 4.3,
        reviewCount: 5400,
        priceLevel: 1,
        ambianceTags: ['décontracté', 'familial'],
        musicTags: ['pop'],
        styleTags: ['vietnamien'],
      ),
      Place(
        id: 'p32',
        name: 'Le Coq Rico',
        type: PlaceType.restaurant,
        latitude: 48.8867,
        longitude: 2.3409,
        address: '98 Rue Lepic, 75018 Paris',
        rating: 4.3,
        reviewCount: 1800,
        priceLevel: 4,
        ambianceTags: ['chic', 'familial'],
        musicTags: ['jazz'],
        styleTags: ['gastronomique', 'terrasse'],
      ),
      Place(
        id: 'p33',
        name: 'Big Fernand',
        type: PlaceType.restaurant,
        latitude: 48.8730,
        longitude: 2.3470,
        address: '55 Rue du Faubourg Poissonniere, 75009 Paris',
        rating: 4.3,
        reviewCount: 6700,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'animé', 'familial'],
        musicTags: ['rock', 'pop'],
        styleTags: ['burger'],
      ),
      Place(
        id: 'p34',
        name: 'PNY (Paris New York)',
        type: PlaceType.restaurant,
        latitude: 48.8702,
        longitude: 2.3548,
        address: '50 Rue du Faubourg Saint-Denis, 75010 Paris',
        rating: 4.4,
        reviewCount: 8200,
        priceLevel: 2,
        ambianceTags: ['branché', 'décontracté'],
        musicTags: ['funk', 'soul'],
        styleTags: ['burger'],
      ),
      Place(
        id: 'p35',
        name: 'Wild & The Moon',
        type: PlaceType.restaurant,
        latitude: 48.8616,
        longitude: 2.3662,
        address: '55 Rue Charlot, 75003 Paris',
        rating: 4.2,
        reviewCount: 2100,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['vegan', 'brunch'],
      ),
      Place(
        id: 'p36',
        name: 'Le Potager du Marais',
        type: PlaceType.restaurant,
        latitude: 48.8617,
        longitude: 2.3565,
        address: '24 Rue Rambuteau, 75003 Paris',
        rating: 4.3,
        reviewCount: 1600,
        priceLevel: 2,
        ambianceTags: ['cosy', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['vegan'],
      ),
      Place(
        id: 'p37',
        name: 'Breizh Cafe',
        type: PlaceType.restaurant,
        latitude: 48.8593,
        longitude: 2.3637,
        address: '109 Rue Vieille du Temple, 75003 Paris',
        rating: 4.4,
        reviewCount: 9100,
        priceLevel: 2,
        ambianceTags: ['cosy', 'familial'],
        musicTags: ['pop'],
        styleTags: ['crêperie'],
      ),
      Place(
        id: 'p38',
        name: 'Hero',
        type: PlaceType.restaurant,
        latitude: 48.8662,
        longitude: 2.3470,
        address: '289 Rue Saint-Denis, 75002 Paris',
        rating: 4.3,
        reviewCount: 2700,
        priceLevel: 2,
        ambianceTags: ['animé', 'branché'],
        musicTags: ['funk', 'soul'],
        styleTags: ['coréen', 'cocktails'],
      ),
      Place(
        id: 'p39',
        name: 'Anahuacalli',
        type: PlaceType.restaurant,
        latitude: 48.8487,
        longitude: 2.3501,
        address: '30 Rue des Bernardins, 75005 Paris',
        rating: 4.4,
        reviewCount: 1400,
        priceLevel: 3,
        ambianceTags: ['cosy', 'familial', 'romantique'],
        musicTags: ['latino'],
        styleTags: ['mexicain'],
      ),
      Place(
        id: 'p40',
        name: 'La Coupole',
        type: PlaceType.restaurant,
        latitude: 48.8419,
        longitude: 2.3290,
        address: '102 Boulevard du Montparnasse, 75014 Paris',
        rating: 4.2,
        reviewCount: 12800,
        priceLevel: 3,
        ambianceTags: ['business', 'festif', 'chic'],
        musicTags: ['jazz'],
        styleTags: ['brasserie', 'terrasse'],
      ),
      Place(
        id: 'p41',
        name: 'Le Tout-Paris',
        type: PlaceType.restaurant,
        latitude: 48.8585,
        longitude: 2.3470,
        address: 'Cheval Blanc, 8 Quai du Louvre, 75001 Paris',
        rating: 4.5,
        reviewCount: 880,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'rooftop', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p42',
        name: 'Bouillon Republique',
        type: PlaceType.restaurant,
        latitude: 48.8674,
        longitude: 2.3636,
        address: '39 Boulevard du Temple, 75003 Paris',
        rating: 4.3,
        reviewCount: 8900,
        priceLevel: 1,
        ambianceTags: ['festif', 'familial', 'décontracté'],
        musicTags: ['pop'],
        styleTags: ['bistrot'],
      ),

      // ===================== HOTELS =====================
      Place(
        id: 'p43',
        name: 'Hotel Costes',
        type: PlaceType.hotel,
        latitude: 48.8676,
        longitude: 2.3274,
        address: '239 Rue Saint-Honore, 75001 Paris',
        rating: 4.4,
        reviewCount: 1800,
        priceLevel: 4,
        ambianceTags: ['chic', 'festif'],
        musicTags: ['lounge', 'house'],
        styleTags: ['palace', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'p44',
        name: 'Le Pavillon de la Reine',
        type: PlaceType.hotel,
        latitude: 48.8556,
        longitude: 2.3661,
        address: '28 Place des Vosges, 75003 Paris',
        rating: 4.7,
        reviewCount: 950,
        priceLevel: 4,
        ambianceTags: ['romantique', 'chic', 'intimiste'],
        musicTags: ['lounge'],
        styleTags: ['boutique-hôtel', 'jardin'],
      ),
      Place(
        id: 'p45',
        name: 'Hotel Grand Amour',
        type: PlaceType.hotel,
        latitude: 48.8714,
        longitude: 2.3550,
        address: '18 Rue de la Fidelite, 75010 Paris',
        rating: 4.3,
        reviewCount: 1100,
        priceLevel: 3,
        ambianceTags: ['cosy', 'festif', 'branché'],
        musicTags: ['pop', 'afro'],
        styleTags: ['boutique-hôtel', 'design', 'terrasse'],
      ),
      Place(
        id: 'p46',
        name: 'Generator Paris',
        type: PlaceType.hotel,
        latitude: 48.8809,
        longitude: 2.3700,
        address: '9-11 Place du Colonel Fabien, 75010 Paris',
        rating: 4.1,
        reviewCount: 6400,
        priceLevel: 2,
        ambianceTags: ['festif', 'décontracté', 'business'],
        musicTags: ['house', 'pop'],
        styleTags: ['rooftop', 'vue Tour Eiffel'],
      ),
      Place(
        id: 'p47',
        name: 'Mama Shelter Paris East',
        type: PlaceType.hotel,
        latitude: 48.8676,
        longitude: 2.4053,
        address: '109 Rue de Bagnolet, 75020 Paris',
        rating: 4.2,
        reviewCount: 3900,
        priceLevel: 2,
        ambianceTags: ['festif', 'décontracté', 'familial'],
        musicTags: ['afro', 'house'],
        styleTags: ['rooftop', 'design'],
      ),
      Place(
        id: 'p48',
        name: 'Le Bristol Paris',
        type: PlaceType.hotel,
        latitude: 48.8721,
        longitude: 2.3157,
        address: '112 Rue du Faubourg Saint-Honore, 75008 Paris',
        rating: 4.8,
        reviewCount: 2600,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace', 'jardin'],
        isPremium: true,
      ),
      Place(
        id: 'p49',
        name: 'Hotel Particulier Montmartre',
        type: PlaceType.hotel,
        latitude: 48.8876,
        longitude: 2.3380,
        address: '23 Avenue Junot, 75018 Paris',
        rating: 4.5,
        reviewCount: 720,
        priceLevel: 4,
        ambianceTags: ['romantique', 'intimiste', 'insolite'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['boutique-hôtel', 'jardin'],
        isPremium: true,
      ),
      Place(
        id: 'p50',
        name: 'CitizenM Paris Gare de Lyon',
        type: PlaceType.hotel,
        latitude: 48.8443,
        longitude: 2.3743,
        address: '17 Boulevard Diderot, 75012 Paris',
        rating: 4.4,
        reviewCount: 4800,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'business', 'branché'],
        musicTags: ['house'],
        styleTags: ['design', 'rooftop'],
      ),
      Place(
        id: 'p51',
        name: 'Hotel Providence',
        type: PlaceType.hotel,
        latitude: 48.8709,
        longitude: 2.3555,
        address: '90 Rue Rene Boulanger, 75010 Paris',
        rating: 4.4,
        reviewCount: 1300,
        priceLevel: 3,
        ambianceTags: ['cosy', 'romantique', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['boutique-hôtel', 'cocktails'],
      ),
      Place(
        id: 'p52',
        name: 'OFF Paris Seine',
        type: PlaceType.hotel,
        latitude: 48.8388,
        longitude: 2.3736,
        address: "20-22 Port d'Austerlitz, 75013 Paris",
        rating: 4.2,
        reviewCount: 2200,
        priceLevel: 3,
        ambianceTags: ['insolite', 'branché', 'romantique'],
        musicTags: ['lounge', 'house'],
        styleTags: ['péniche', 'design', 'terrasse'],
      ),
      Place(
        id: 'p53',
        name: 'Hotel Molitor',
        type: PlaceType.hotel,
        latitude: 48.8447,
        longitude: 2.2530,
        address: '13 Rue Nungesser et Coli, 75016 Paris',
        rating: 4.4,
        reviewCount: 3400,
        priceLevel: 4,
        ambianceTags: ['branché', 'festif', 'familial'],
        musicTags: ['house', 'pop'],
        styleTags: ['design', 'rooftop'],
        isPremium: true,
      ),
      Place(
        id: 'p54',
        name: 'Mob Hotel Les Puces',
        type: PlaceType.hotel,
        latitude: 48.9018,
        longitude: 2.3447,
        address: '4-6 Rue Gambetta, 93400 Saint-Ouen',
        rating: 4.2,
        reviewCount: 2900,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'familial', 'branché'],
        musicTags: ['afro', 'funk'],
        styleTags: ['rooftop', 'terrasse', 'design'],
      ),

      // ===================== BARS / ROOFTOPS (suite) =====================
      Place(
        id: 'p55',
        name: 'Le Perchoir Menilmontant',
        type: PlaceType.bar,
        latitude: 48.8668,
        longitude: 2.3897,
        address: '14 Rue Crespin du Gast, 75011 Paris',
        rating: 4.3,
        reviewCount: 6100,
        priceLevel: 3,
        ambianceTags: ['festif', 'branché'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'terrasse', 'cocktails', 'vue Tour Eiffel'],
      ),
      Place(
        id: 'p56',
        name: 'Le Tres Particulier',
        type: PlaceType.bar,
        latitude: 48.8884,
        longitude: 2.3375,
        address: '23 Avenue Junot, 75018 Paris',
        rating: 4.4,
        reviewCount: 2400,
        priceLevel: 4,
        ambianceTags: ['intimiste', 'romantique', 'insolite'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['speakeasy', 'jardin', 'cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'p57',
        name: 'Moonshiner',
        type: PlaceType.bar,
        latitude: 48.8554,
        longitude: 2.3739,
        address: '5 Rue Sedaine, 75011 Paris',
        rating: 4.5,
        reviewCount: 1700,
        priceLevel: 2,
        ambianceTags: ['intimiste', 'branché'],
        musicTags: ['jazz', 'soul'],
        styleTags: ['speakeasy', 'cocktails'],
      ),
      Place(
        id: 'p58',
        name: 'Lavomatic',
        type: PlaceType.bar,
        latitude: 48.8675,
        longitude: 2.3656,
        address: '30 Rue Rene Boulanger, 75010 Paris',
        rating: 4.3,
        reviewCount: 2900,
        priceLevel: 2,
        ambianceTags: ['branché', 'insolite', 'animé'],
        musicTags: ['funk', 'house'],
        styleTags: ['speakeasy', 'cocktails'],
      ),
      Place(
        id: 'p59',
        name: 'Dirty Dick',
        type: PlaceType.bar,
        latitude: 48.8817,
        longitude: 2.3372,
        address: '10 Rue Frochot, 75009 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 2,
        ambianceTags: ['festif', 'animé', 'insolite'],
        musicTags: ['latino', 'pop'],
        styleTags: ['cocktails'],
      ),
      Place(
        id: 'p60',
        name: 'Combat',
        type: PlaceType.bar,
        latitude: 48.8721,
        longitude: 2.3847,
        address: '63 Rue de Belleville, 75019 Paris',
        rating: 4.5,
        reviewCount: 1500,
        priceLevel: 2,
        ambianceTags: ['cosy', 'branché'],
        musicTags: ['soul', 'funk'],
        styleTags: ['cocktails', 'vins nature'],
      ),
      Place(
        id: 'p61',
        name: 'Bar Botaniste (Shangri-La)',
        type: PlaceType.bar,
        latitude: 48.8639,
        longitude: 2.2898,
        address: '10 Avenue d Iena, 75116 Paris',
        rating: 4.6,
        reviewCount: 640,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge', 'jazz'],
        styleTags: ['cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'p62',
        name: 'Le Mary Celeste',
        type: PlaceType.bar,
        latitude: 48.8624,
        longitude: 2.3631,
        address: '1 Rue Commines, 75003 Paris',
        rating: 4.3,
        reviewCount: 1300,
        priceLevel: 3,
        ambianceTags: ['branché', 'cosy'],
        musicTags: ['lounge', 'soul'],
        styleTags: ['cocktails', 'fruits de mer'],
      ),

      // ===================== RESTAURANTS (suite) =====================
      Place(
        id: 'p63',
        name: 'Le Chateaubriand',
        type: PlaceType.restaurant,
        latitude: 48.8669,
        longitude: 2.3717,
        address: '129 Avenue Parmentier, 75011 Paris',
        rating: 4.4,
        reviewCount: 2600,
        priceLevel: 4,
        ambianceTags: ['chic', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique'],
        isPremium: true,
      ),
      Place(
        id: 'p64',
        name: 'Frenchie',
        type: PlaceType.restaurant,
        latitude: 48.8662,
        longitude: 2.3486,
        address: '5 Rue du Nil, 75002 Paris',
        rating: 4.5,
        reviewCount: 3300,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'bistrot'],
        isPremium: true,
      ),
      Place(
        id: 'p65',
        name: 'Bistrot Paul Bert',
        type: PlaceType.restaurant,
        latitude: 48.8527,
        longitude: 2.3849,
        address: '18 Rue Paul Bert, 75011 Paris',
        rating: 4.4,
        reviewCount: 4200,
        priceLevel: 3,
        ambianceTags: ['cosy', 'romantique'],
        musicTags: ['jazz'],
        styleTags: ['bistrot', 'terrasse'],
      ),
      Place(
        id: 'p66',
        name: 'Chez Janou',
        type: PlaceType.restaurant,
        latitude: 48.8564,
        longitude: 2.3671,
        address: '2 Rue Roger Verlomme, 75003 Paris',
        rating: 4.4,
        reviewCount: 7800,
        priceLevel: 2,
        ambianceTags: ['festif', 'cosy', 'familial'],
        musicTags: ['lounge'],
        styleTags: ['bistrot', 'terrasse'],
      ),
      Place(
        id: 'p67',
        name: "L'As du Fallafel",
        type: PlaceType.restaurant,
        latitude: 48.8576,
        longitude: 2.3593,
        address: '34 Rue des Rosiers, 75004 Paris',
        rating: 4.4,
        reviewCount: 16200,
        priceLevel: 1,
        ambianceTags: ['décontracté', 'animé', 'familial'],
        musicTags: ['pop'],
        styleTags: ['libanais'],
      ),
      Place(
        id: 'p68',
        name: 'Miznon',
        type: PlaceType.restaurant,
        latitude: 48.8580,
        longitude: 2.3590,
        address: '22 Rue des Ecouffes, 75004 Paris',
        rating: 4.4,
        reviewCount: 5900,
        priceLevel: 2,
        ambianceTags: ['animé', 'décontracté'],
        musicTags: ['pop', 'latino'],
        styleTags: ['libanais', 'vegan'],
      ),
      Place(
        id: 'p69',
        name: 'Ober Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8615,
        longitude: 2.3739,
        address: '107 Boulevard Richard-Lenoir, 75011 Paris',
        rating: 4.4,
        reviewCount: 12100,
        priceLevel: 2,
        ambianceTags: ['animé', 'festif', 'familial'],
        musicTags: ['pop'],
        styleTags: ['italien', 'pizza'],
      ),
      Place(
        id: 'p70',
        name: 'Blueberry Maki Bar',
        type: PlaceType.restaurant,
        latitude: 48.8518,
        longitude: 2.3360,
        address: '6 Rue du Sabot, 75006 Paris',
        rating: 4.5,
        reviewCount: 1100,
        priceLevel: 3,
        ambianceTags: ['cosy', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['japonais'],
      ),
      Place(
        id: 'p71',
        name: 'Dumbo',
        type: PlaceType.restaurant,
        latitude: 48.8666,
        longitude: 2.3679,
        address: '20 Rue Rambuteau, 75003 Paris',
        rating: 4.5,
        reviewCount: 4600,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'animé', 'branché'],
        musicTags: ['funk', 'soul'],
        styleTags: ['burger'],
      ),
      Place(
        id: 'p72',
        name: "Chez l'Ami Jean",
        type: PlaceType.restaurant,
        latitude: 48.8588,
        longitude: 2.3050,
        address: '27 Rue Malar, 75007 Paris',
        rating: 4.5,
        reviewCount: 2200,
        priceLevel: 3,
        ambianceTags: ['cosy', 'animé'],
        musicTags: ['jazz'],
        styleTags: ['bistrot', 'gastronomique'],
      ),
      Place(
        id: 'p73',
        name: 'Angelina',
        type: PlaceType.restaurant,
        latitude: 48.8654,
        longitude: 2.3284,
        address: '226 Rue de Rivoli, 75001 Paris',
        rating: 4.4,
        reviewCount: 18900,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique', 'familial'],
        musicTags: ['lounge'],
        styleTags: ['brunch', 'terrasse'],
      ),
      Place(
        id: 'p74',
        name: 'Le Servan',
        type: PlaceType.restaurant,
        latitude: 48.8636,
        longitude: 2.3809,
        address: '32 Rue Saint-Maur, 75011 Paris',
        rating: 4.4,
        reviewCount: 1500,
        priceLevel: 3,
        ambianceTags: ['cosy', 'branché', 'romantique'],
        musicTags: ['jazz'],
        styleTags: ['gastronomique', 'bistrot'],
      ),

      // ===================== HOTELS (suite) =====================
      Place(
        id: 'p75',
        name: 'Ritz Paris',
        type: PlaceType.hotel,
        latitude: 48.8681,
        longitude: 2.3284,
        address: '15 Place Vendome, 75001 Paris',
        rating: 4.8,
        reviewCount: 3600,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace', 'jardin'],
        isPremium: true,
      ),
      Place(
        id: 'p76',
        name: 'Four Seasons George V',
        type: PlaceType.hotel,
        latitude: 48.8686,
        longitude: 2.3008,
        address: '31 Avenue George V, 75008 Paris',
        rating: 4.8,
        reviewCount: 4100,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace'],
        isPremium: true,
      ),
      Place(
        id: 'p77',
        name: 'Le Meurice',
        type: PlaceType.hotel,
        latitude: 48.8654,
        longitude: 2.3281,
        address: '228 Rue de Rivoli, 75001 Paris',
        rating: 4.7,
        reviewCount: 2900,
        priceLevel: 4,
        ambianceTags: ['chic', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace'],
        isPremium: true,
      ),
      Place(
        id: 'p78',
        name: 'The Hoxton Paris',
        type: PlaceType.hotel,
        latitude: 48.8688,
        longitude: 2.3506,
        address: '30-32 Rue du Sentier, 75002 Paris',
        rating: 4.4,
        reviewCount: 3200,
        priceLevel: 3,
        ambianceTags: ['branché', 'cosy', 'business'],
        musicTags: ['house', 'soul'],
        styleTags: ['boutique-hôtel', 'design'],
      ),
      Place(
        id: 'p79',
        name: 'SO/ Paris',
        type: PlaceType.hotel,
        latitude: 48.8520,
        longitude: 2.3610,
        address: '10 Rue Agrippa d Aubigne, 75004 Paris',
        rating: 4.5,
        reviewCount: 1800,
        priceLevel: 4,
        ambianceTags: ['branché', 'festif', 'chic'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'design', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p80',
        name: 'Brach Paris',
        type: PlaceType.hotel,
        latitude: 48.8636,
        longitude: 2.2820,
        address: '1-7 Rue Jean Richepin, 75116 Paris',
        rating: 4.6,
        reviewCount: 1400,
        priceLevel: 4,
        ambianceTags: ['branché', 'chic', 'cosy'],
        musicTags: ['lounge', 'soul'],
        styleTags: ['design', 'rooftop'],
        isPremium: true,
      ),
      Place(
        id: 'p81',
        name: 'Hotel Rochechouart',
        type: PlaceType.hotel,
        latitude: 48.8820,
        longitude: 2.3437,
        address: '55 Boulevard de Rochechouart, 75009 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 3,
        ambianceTags: ['festif', 'branché', 'décontracté'],
        musicTags: ['house', 'pop'],
        styleTags: ['rooftop', 'design', 'terrasse'],
      ),
      Place(
        id: 'p82',
        name: 'Kimpton St Honore',
        type: PlaceType.hotel,
        latitude: 48.8712,
        longitude: 2.3349,
        address: '27-29 Boulevard des Capucines, 75002 Paris',
        rating: 4.5,
        reviewCount: 1600,
        priceLevel: 4,
        ambianceTags: ['branché', 'chic', 'festif'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'design', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p83',
        name: '25hours Hotel Terminus Nord',
        type: PlaceType.hotel,
        latitude: 48.8810,
        longitude: 2.3573,
        address: '12 Boulevard de Denain, 75010 Paris',
        rating: 4.3,
        reviewCount: 2400,
        priceLevel: 2,
        ambianceTags: ['branché', 'décontracté', 'familial'],
        musicTags: ['funk', 'afro'],
        styleTags: ['design', 'boutique-hôtel'],
      ),
      Place(
        id: 'p84',
        name: 'Hotel National des Arts et Metiers',
        type: PlaceType.hotel,
        latitude: 48.8659,
        longitude: 2.3560,
        address: '243 Rue Saint-Martin, 75003 Paris',
        rating: 4.4,
        reviewCount: 1900,
        priceLevel: 3,
        ambianceTags: ['branché', 'romantique', 'cosy'],
        musicTags: ['lounge', 'house'],
        styleTags: ['rooftop', 'design', 'boutique-hôtel'],
      ),
    ].map(_withMockMedia).toList();
  }

  /// Enrichit chaque lieu (medias + donnees derivees pour les filtres avances).
  ///
  /// >>> POINT DE BRANCHEMENT BACKEND <<<
  /// Le prix reel, la frequentation et les horaires d'affluence sont ici
  /// DERIVES de façon deterministe a partir du type/prix/tags (heuristiques
  /// de demo). Quand un backend sera branche, ces valeurs viendront de vraies
  /// donnees (ex: Google Popular Times, tickets moyens, etc.).
  Place _withMockMedia(Place p) {
    final ambiance = [...p.ambianceTags];
    // "calme" : intimiste/cosy sans cote festif/anime.
    if ((ambiance.contains('intimiste') || ambiance.contains('cosy')) &&
        !ambiance.contains('festif') &&
        !ambiance.contains('animé')) {
      ambiance.add('calme');
    }

    final style = [...p.styleTags];
    // "luxueux" : haut de gamme (prix 4, palace ou premium).
    if (p.priceLevel >= 4 || style.contains('palace') || p.isPremium) {
      if (!style.contains('luxueux')) style.add('luxueux');
    }

    // Lien Google Maps REEL (recherche par nom + adresse) : ouvre la vraie
    // fiche du lieu avec ses avis reels, photos et itineraire.
    final mapsUrl = 'https://www.google.com/maps/search/?api=1&query='
        '${Uri.encodeComponent('${p.name} ${p.address}')}';
    // Hashtag Instagram (best-effort a partir du nom).
    final slug = p.name
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]'), '');
    final instagramUrl = 'https://www.instagram.com/explore/tags/$slug/';

    return Place(
      id: p.id,
      name: p.name,
      type: p.type,
      latitude: p.latitude,
      longitude: p.longitude,
      address: p.address,
      rating: p.rating,
      reviewCount: p.reviewCount,
      priceLevel: p.priceLevel,
      ambianceTags: ambiance,
      musicTags: p.musicTags,
      styleTags: style,
      photos: [
        _photo('${p.id}a'),
        _photo('${p.id}b'),
        _photo('${p.id}c'),
      ],
      videos: const [],
      isPremium: p.isPremium,
      averagePrice: _averagePrice(p),
      crowdTags: _crowd(p),
      peakTags: _peak(p),
      mapsUrl: mapsUrl,
      instagramUrl: instagramUrl,
      // websiteUrl laisse a null : on ne fabrique pas de faux site.
      // Extraits "Instagram" (placeholders de demo en attendant l'integration
      // reelle des Reels via l'API/embed Instagram).
      instagramVideos: [
        p.id.hashCode.isEven ? _sampleVideoA : _sampleVideoB,
      ],
      // Nos interviews maison : vides pour l'instant (tournage a venir).
      originalVideos: const [],
      // Avis : volontairement vides. On NE genere PAS de faux avis ;
      // la fiche renvoie vers les avis Google reels (voir mapsUrl).
      reviews: const [],
    );
  }

  /// Prix moyen reel (€) derive du type et du niveau de prix, avec variation.
  int _averagePrice(Place p) {
    const barTiers = [15, 25, 45, 70];
    const restoTiers = [20, 35, 60, 110];
    const hotelTiers = [90, 150, 250, 430];
    final tiers = switch (p.type) {
      PlaceType.bar => barTiers,
      PlaceType.restaurant => restoTiers,
      PlaceType.hotel => hotelTiers,
    };
    final base = tiers[(p.priceLevel - 1).clamp(0, 3)];
    final jitter = p.id.hashCode.abs() % 11; // 0..10
    return base + jitter;
  }

  /// Frequentation type derivee de l'ambiance / du style.
  List<String> _crowd(Place p) {
    final s = <String>{};
    final a = p.ambianceTags;
    final st = p.styleTags;
    if (st.contains('club') || a.contains('festif') || a.contains('animé')) {
      s.addAll(['20-30 ans', 'étudiants']);
    }
    if (a.contains('business') ||
        st.contains('gastronomique') ||
        st.contains('palace')) {
      s.add('business');
    }
    if (st.contains('vue Tour Eiffel') ||
        st.contains('palace') ||
        st.contains('rooftop') ||
        p.isPremium) {
      s.add('touristes');
    }
    if (a.contains('familial')) s.add('familles');
    if (a.contains('cosy') ||
        a.contains('intimiste') ||
        st.contains('bistrot') ||
        st.contains('vins nature')) {
      s.add('locaux');
    }
    if (st.contains('cocktails') ||
        a.contains('branché') ||
        a.contains('chic')) {
      s.addAll(['after-work', '30-45 ans']);
    }
    if (s.isEmpty) s.add('locaux');
    return s.toList();
  }

  /// Creneaux d'affluence derives du type et du style.
  List<String> _peak(Place p) {
    final s = <String>{};
    switch (p.type) {
      case PlaceType.bar:
        s.addAll(['after-work', 'soir', 'week-end']);
        if (p.styleTags.contains('club') || p.ambianceTags.contains('festif')) {
          s.add('nuit');
        }
        break;
      case PlaceType.restaurant:
        s.addAll(['midi', 'soir']);
        if (p.styleTags.contains('brunch')) s.addAll(['matin', 'week-end']);
        break;
      case PlaceType.hotel:
        s.addAll(['soir', 'nuit', 'week-end']);
        break;
    }
    if (p.styleTags.contains('terrasse') || p.styleTags.contains('jardin')) {
      s.add('après-midi');
    }
    return s.toList();
  }

  // ---- Styles de collection mock ----
  List<CollectionStyle> getStyles() {
    return const [
      CollectionStyle(
        id: 's1',
        name: 'Nightlife Chic',
        primaryColor: Color(0xFF6C5CE7),
        iconStyle: 'bold',
        description: 'Rooftops, speakeasies et cocktails haut de gamme.',
      ),
      CollectionStyle(
        id: 's2',
        name: 'Rooftop Chill',
        primaryColor: Color(0xFF74B9FF),
        iconStyle: 'minimal',
        description: 'Vues degagees, terrasses et ambiances detendues.',
      ),
      CollectionStyle(
        id: 's3',
        name: 'Hidden Gems',
        primaryColor: Color(0xFF1E5631),
        iconStyle: 'outline',
        description: 'Adresses confidentielles loin des foules.',
      ),
    ];
  }

  /// Cartes publiques d'influenceurs (accessibles via un code).
  /// Ce sont des collections riches (> 10 lieux), stylees, verifiees.
  List<UserCollection> getInfluencerCollections() {
    final places = getPlaces();
    return [
      UserCollection(
        id: 'inf1',
        ownerName: 'Lea Martin',
        authorHandle: '@lea.inparis',
        isInfluencer: true,
        coverImage: 'https://picsum.photos/seed/leacover/900/450',
        code: 'LEA-PARIS-2024',
        style: const CollectionStyle(
          id: 'infs1',
          name: 'Lea a Paris',
          primaryColor: Color(0xFFE84393),
          iconStyle: 'bold',
          description: 'Mes adresses prefereees a Paris - rooftops, brunchs & spots photo.',
        ),
        places: places
            .where((p) =>
                p.styleTags.contains('rooftop') ||
                p.styleTags.contains('brunch') ||
                p.ambianceTags.contains('branché'))
            .take(14)
            .toList(),
      ),
      UserCollection(
        id: 'inf2',
        ownerName: 'Marco Rossi',
        authorHandle: '@chefmarco',
        isInfluencer: true,
        coverImage: 'https://picsum.photos/seed/marcocover/900/450',
        code: 'MARCO-EATS-7788',
        style: const CollectionStyle(
          id: 'infs2',
          name: "Marco's Food Map",
          primaryColor: Color(0xFFB71C1C),
          iconStyle: 'outline',
          description: 'The best restaurants in Paris, picked by a chef.',
        ),
        places:
            places.where((p) => p.type == PlaceType.restaurant).take(13).toList(),
      ),
    ];
  }

  /// Collections appartenant a l'utilisateur courant (mock).
  List<UserCollection> getUserCollections() {
    final places = getPlaces();
    final styles = getStyles();
    return [
      UserCollection(
        id: 'c1',
        ownerName: 'Alex',
        code: 'PARIS-CHIC-1234',
        style: styles[0],
        places: places.where((p) => p.type == PlaceType.bar).take(5).toList(),
      ),
      UserCollection(
        id: 'c2',
        ownerName: 'Alex',
        code: 'ROOFTOP-COOL-5678',
        style: styles[1],
        places: places
            .where((p) => p.styleTags.contains('rooftop'))
            .take(5)
            .toList(),
      ),
    ];
  }
}
