import 'package:flutter/material.dart';

import '../config.dart';
import '../models/collection_style.dart';
import '../models/place.dart';
import '../models/user_collection.dart';

/// Fournit des donnees mockees (lieux, styles, collections).
///
/// >>> POINT DE BRANCHEMENT BACKEND <<<
/// Remplacer le contenu de cette classe par des appels HTTP (ex: dio/http)
/// renvoyant les memes modeles. La signature des methodes peut rester
/// identique (passer en `Future<...>` + async).
class MockDataService {
  // ---- Vocabulaire de tags (utilise par les filtres) ----
  // Plus la liste est riche, plus le filtrage est precis.

  /// Ambiance / atmosphere du lieu.
  static const List<String> ambianceOptions = [
    'calme',
    'chic',
    'cosy',
    'festif',
    'romantique',
    'business',
    'branché',
    'décontracté',
    'animé',
    'intimiste',
    'familial',
    'insolite',
  ];

  /// Frequentation / clientele type.
  static const List<String> crowdOptions = [
    '20-30 ans',
    '30-45 ans',
    'business',
    'touristes',
    'étudiants',
    'familles',
    'locaux',
    'after-work',
  ];

  /// Creneaux d'affluence reels.
  static const List<String> peakOptions = [
    'matin',
    'midi',
    'après-midi',
    'after-work',
    'soir',
    'nuit',
    'week-end',
  ];

  /// Style musical dominant.
  static const List<String> musicOptions = [
    'house',
    'jazz',
    'afro',
    'lounge',
    'pop',
    'techno',
    'soul',
    'funk',
    'latino',
    'rock',
  ];

  /// Style du lieu uniquement (sans cuisine — voir cuisineOptions).
  static const List<String> styleOptions = [
    'rooftop',
    'speakeasy',
    'terrasse',
    'vue Tour Eiffel',
    'vue panoramique',
    'cocktails',
    'vins nature',
    'bière artisanale',
    'club',
    'jardin',
    'péniche',
    'design',
    'boutique-hôtel',
    'palace',
    'luxueux',
    'live music',
    'happy hour',
    'cave à vins',
    'pique-nique',
    'pelouse',
    'nature',
    'gratuit',
    'instagrammable',
    'street art',
    'marché',
    'galerie couverte',
  ];

  /// Type de cuisine / genre de restaurant.
  static const List<String> cuisineOptions = [
    'bistrot',
    'brasserie',
    'gastronomique',
    'brunch',
    'italien',
    'pizza',
    'japonais',
    'libanais',
    'indien',
    'thai',
    'vietnamien',
    'coréen',
    'mexicain',
    'burger',
    'vegan',
    'fruits de mer',
    'steakhouse',
    'crêperie',
    'street food',
    'tapas',
  ];

  /// Horaires d'ouverture du lieu.
  static const List<String> openingHoursOptions = [
    'Toute la journée',
    'Matin + Midi',
    'Midi uniquement',
    'Midi + Soir',
    'Soir uniquement',
    'Soir + Nuit',
    'Week-end uniquement',
  ];

  // Videos de demo publiques (lisibles par video_player).
  static const String _sampleVideoA =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/bee.mp4';
  static const String _sampleVideoB =
      'https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4';

  // ---- Photos par lieu ----
  //  
  // SUPABASE STORAGE (recommande) :
  //   Bucket public : "place-photos"
  //   Chemin       : {place_id}/1.jpg, {place_id}/2.jpg, ...
  //   Exemple      : place-photos/p01/1.jpg   place-photos/p01/2.jpg
  //
  //   _maxPhotosPerPlace controle combien d'images l'app essaie de charger.
  //   Les URLs manquantes affichent la couleur de fallback (cf. PlacePhoto).
  //   Augmente cette valeur si certains lieux ont plus de photos.
  static const int _maxPhotosPerPlace = 8;

  // Override par lieu : utile si un lieu utilise des noms de fichiers differents
  // ou des URLs provenant d'un autre CDN. Laisser vide pour la convention auto.
  static const Map<String, List<String>> _placePhotos = {
    // 'p01': [
    //   'https://mon-autre-cdn.com/perchoir-rooftop.jpg',
    //   'https://mon-autre-cdn.com/perchoir-bar.jpg',
    // ],
  };

  // URL de base Supabase Storage (bucket public "place-photos").
  static String _supabasePhotoUrl(String placeId, int index) =>
      '${Config.supabaseUrl}'
      '/storage/v1/object/public/place-photos/$placeId/$index.jpg';

  static List<String> _photosForPlace(String id) {
    // Override explicite ? On l'utilise tel quel.
    if (_placePhotos.containsKey(id)) return _placePhotos[id]!;

    // Supabase configure → URLs generees automatiquement.
    // Deposer les images dans : place-photos/{id}/1.jpg ... {id}/{_max}.jpg
    if (Config.isSupabaseConfigured) {
      return [
        for (var i = 1; i <= _maxPhotosPerPlace; i++) _supabasePhotoUrl(id, i),
      ];
    }

    // Mode demo local (Supabase absent) → assets locaux.
    return [
      for (var i = 1; i <= 5; i++) 'assets/places/${id}_$i.jpg',
    ];
  }

  // ---- Videos clips par lieu (bucket Supabase "place-videos") ----
  //
  // SUPABASE STORAGE :
  //   Bucket public : "place-videos"
  //   Chemin        : {place_id}/1.mp4, {place_id}/2.mp4, ...
  //   Exemple       : place-videos/p01/1.mp4
  //
  // Chaque lieu tente de charger jusqu'a _maxVideosPerPlace slots.
  // Les slots sans fichier Supabase sont caches automatiquement (HEAD check).
  static const int _maxVideosPerPlace = 3;

  // Override manuel pour des URLs hors-convention (YouTube, autre CDN, etc.)
  static const Map<String, List<String>> _igVideos = {
    // 'p01': ['https://mon-cdn.com/videos/perchoir-ig.mp4'],
  };

  static String _supabaseVideoUrl(String placeId, int index) =>
      '${Config.supabaseUrl}'
      '/storage/v1/object/public/place-videos/$placeId/$index.mp4';

  static List<String> _igVideosForPlace(String id) {
    if (_igVideos.containsKey(id)) return _igVideos[id]!;
    if (Config.isSupabaseConfigured) {
      return [
        for (var i = 1; i <= _maxVideosPerPlace; i++) _supabaseVideoUrl(id, i),
      ];
    }
    return [id.hashCode.isEven ? _sampleVideoA : _sampleVideoB];
  }

  // ---- Videos originales (interviews maison) par lieu ----
  // Pour ajouter une ou plusieurs videos de votre tournage :
  static const Map<String, List<String>> _originalVideosMap = {
    // 'p01': [
    //   'https://mon-cdn.com/videos/perchoir-interview.mp4',
    //   'https://mon-cdn.com/videos/perchoir-coulisses.mp4',
    // ],
  };

  static List<String> _originalVideosForPlace(String id) =>
      _originalVideosMap[id] ?? const [];

  // ---- Extraits d'avis par lieu (jusqu'a 10 par lieu) ----
  // Source : avis Google verifies. Remplacer par l'API Google Places quand disponible.
  // Pour ajouter des avis a un lieu, ajouter une entree dans cette map.
  static const Map<String, List<Review>> _reviewSamples = {
    'p01': [
      Review(
        author: 'Sophie M.',
        rating: 5.0,
        text: 'Rooftop magnifique avec vue imprenable sur Paris. Les cocktails sont excellents et l\'ambiance en soiree est parfaite. Incontournable !',
        relativeTime: 'il y a 1 semaine',
      ),
      Review(
        author: 'Thomas L.',
        rating: 4.0,
        text: 'Super endroit, un peu de queue a l\'entree mais ca vaut vraiment le coup. Prix raisonnables pour le quartier Marais.',
        relativeTime: 'il y a 3 semaines',
      ),
      Review(
        author: 'Julie B.',
        rating: 5.0,
        text: 'Vue a couper le souffle au coucher du soleil. Les cocktails signature sont delicieux. On y retourne des cet ete !',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Kevin R.',
        rating: 4.0,
        text: 'Endroit parfait pour un apero entre amis. Ambiance decontractee et branchee. Petite attente mais ca vaut le coup.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Lea H.',
        rating: 5.0,
        text: 'LE rooftop du Marais. La vue sur les toits de Paris est exceptionnelle. Personnel sympa et cocktails originaux.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Marc D.',
        rating: 3.0,
        text: 'Belle vue mais prix eleves et service parfois lent. L\'acces est difficile sans reservation. A reserver en avance.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Chloe P.',
        rating: 5.0,
        text: 'Un endroit magique ! La terrasse au coucher du soleil est un moment inoubliable. Cocktails creatifs et staff accueillant.',
        relativeTime: 'il y a 3 mois',
      ),
    ],
    'p02': [
      Review(
        author: 'Camille R.',
        rating: 5.0,
        text: 'Le meilleur bar a cocktails de Paris sans hesiter. Chaque creation est unique et le cadre speakeasy est incroyable.',
        relativeTime: 'il y a 5 jours',
      ),
      Review(
        author: 'Antoine D.',
        rating: 5.0,
        text: 'Ambiance feutree, staff aux petits soins. Les cocktails changent regulierement selon les saisons. Un must.',
        relativeTime: 'il y a 2 semaines',
      ),
      Review(
        author: 'Noemie C.',
        rating: 5.0,
        text: 'Bar a cocktails d\'exception. Chaque verre est une experience. Le cadre intime et la musique lounge completent parfaitement.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Pierre V.',
        rating: 4.0,
        text: 'Cocktails inventifs et de grande qualite. L\'ambiance speakeasy est vraiment reussie. Un peu cher mais on y retourne.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Margot S.',
        rating: 5.0,
        text: 'Adresse incontournable pour les amateurs de bons cocktails. La carte change selon les saisons, toujours surprenante.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Romain F.',
        rating: 4.0,
        text: 'Tres bon bar avec une carte de cocktails originale. Service attentionne. L\'ambiance est parfaite pour une soiree en duo.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Sarah N.',
        rating: 5.0,
        text: 'Magnifique lieu, cocktails sublimes. Les barmen sont de vrais artistes. A faire absolument si vous etes de passage a Paris.',
        relativeTime: 'il y a 3 mois',
      ),
      Review(
        author: 'Julien K.',
        rating: 4.0,
        text: 'Speakeasy authentique avec une belle selection de spiritueux. Ambiance intime et feutree. Reserve sur semaine pour eviter la queue.',
        relativeTime: 'il y a 4 mois',
      ),
    ],
    'p03': [
      Review(
        author: 'Marie-Claire B.',
        rating: 5.0,
        text: 'L\'experience ultime a Paris. Le cadre du Ritz est somptueux, les cocktails sont des oeuvres d\'art. Un souvenir inoubliable.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'James W.',
        rating: 4.0,
        text: 'Atmosphere is exceptional, prices are what you expect from the Ritz. The Hemingway cocktail is a must-try.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Isabelle G.',
        rating: 5.0,
        text: 'Un bar d\'exception dans un cadre historique unique. Colin Field, le barman legendaire, vous accueille comme un ami. Magique.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'David M.',
        rating: 5.0,
        text: 'Les prix sont eleves mais l\'experience ne s\'oublie pas. Le Serendipity cocktail est divin. Service irréprochable.',
        relativeTime: 'il y a 3 mois',
      ),
      Review(
        author: 'Alexandra T.',
        rating: 4.0,
        text: 'Bar iconique avec une histoire fascinante. Le cadre de la Place Vendome ajoute au charme. A essayer au moins une fois.',
        relativeTime: 'il y a 3 mois',
      ),
      Review(
        author: 'Paul L.',
        rating: 5.0,
        text: 'Endroit mythique. Les cocktails sont des chefs-d\'oeuvre. Colin Field est un artiste. Reservez votre table a l\'avance.',
        relativeTime: 'il y a 4 mois',
      ),
      Review(
        author: 'Emma R.',
        rating: 5.0,
        text: 'Une experience hors du commun. Chaque detail est parfait : le decor, le service, les cocktails. On se sent dans un autre monde.',
        relativeTime: 'il y a 5 mois',
      ),
      Review(
        author: 'Francois B.',
        rating: 4.0,
        text: 'Le bar le plus luxueux de Paris. Les cocktails sont parfaits mais comptez 30-40€ par verre. Pour une occasion speciale.',
        relativeTime: 'il y a 6 mois',
      ),
    ],
    'p04': [
      Review(
        author: 'Lucas P.',
        rating: 4.0,
        text: 'Lieu unique et decale ! La deco est folle, les cocktails bons et l\'ambiance musicale top. Parfait pour un after-work original.',
        relativeTime: 'il y a 2 semaines',
      ),
      Review(
        author: 'Ines T.',
        rating: 4.0,
        text: 'Tres festif le week-end, clientele sympa et diverse. La terrasse au bord du canal est top en ete.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Baptiste M.',
        rating: 5.0,
        text: 'Un endroit dingue et createur. La deco afro-chic est unique a Paris. La terrasse sur le canal est parfaite en ete.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Amandine D.',
        rating: 3.0,
        text: 'Concept interessant mais un peu confus. Biere bonne, nourriture correcte. L\'ambiance peut etre bruyante en soiree.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Thibault R.',
        rating: 4.0,
        text: 'Bar insolite avec une deco afro-tropicale hors du commun. Ideal pour sortir de l\'ordinaire. Cocktails bons et creatifs.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Fanny C.',
        rating: 5.0,
        text: 'Incroyable ! La deco est spectaculaire, les cocktails excellents et la terrasse sur le canal saint-martin est magnifique.',
        relativeTime: 'il y a 3 mois',
      ),
    ],
    'p05': [
      Review(
        author: 'Elise F.',
        rating: 5.0,
        text: 'Cadre de reve avenue Montaigne. On se sent dans un autre monde. Service irreprochable, cocktails divins.',
        relativeTime: 'il y a 3 semaines',
      ),
      Review(
        author: 'Nicolas V.',
        rating: 5.0,
        text: 'Le summum du luxe parisien. Cocktails exceptionnels servis dans un cadre Art Deco somptueux. Service parfait.',
        relativeTime: 'il y a 1 mois',
      ),
      Review(
        author: 'Charlotte B.',
        rating: 4.0,
        text: 'Bar d\'exception au Plaza Athenee. Les prix sont en accord avec le cadre. A faire pour une occasion speciale.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Maxime G.',
        rating: 5.0,
        text: 'Une experience unique. Le bar flottant au milieu du restaurant est spectaculaire. Cocktails divins et service 5 etoiles.',
        relativeTime: 'il y a 2 mois',
      ),
      Review(
        author: 'Valerie P.',
        rating: 4.0,
        text: 'Tres bel endroit, personnel attentionné. Le cocktail signature "Alain Ducasse" est a ne pas manquer. Un peu cher.',
        relativeTime: 'il y a 3 mois',
      ),
    ],
    // Ajouter d'autres lieux ici : 'p06': [...], 'p07': [...], etc.
    // Chaque entree peut contenir jusqu'a 10 avis (les 10 premiers seront affiches).
  };

  /// Liste de lieux a Paris (bars, restaurants, hotels) bien categorises.
  List<Place> getPlaces() {
    return const [
      // ===================== BARS =====================
      Place(
        id: 'p01',
        name: 'Le Perchoir Marais',
        type: PlaceType.bar,
        latitude: 48.8629,
        longitude: 2.3640,
        address: '33 Rue de la Verrerie, 75004 Paris',
        rating: 4.5,
        reviewCount: 1820,
        priceLevel: 3,
        ambianceTags: ['chic', 'festif', 'branché'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'cocktails', 'vue Tour Eiffel'],
      ),
      Place(
        id: 'p02',
        name: 'Little Red Door',
        type: PlaceType.bar,
        latitude: 48.8632,
        longitude: 2.3622,
        address: '60 Rue Charlot, 75003 Paris',
        rating: 4.7,
        reviewCount: 940,
        priceLevel: 3,
        ambianceTags: ['chic', 'intimiste'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['speakeasy', 'cocktails'],
      ),
      Place(
        id: 'p03',
        name: 'Bar Hemingway (Ritz)',
        type: PlaceType.bar,
        latitude: 48.8681,
        longitude: 2.3284,
        address: '15 Place Vendome, 75001 Paris',
        rating: 4.6,
        reviewCount: 1200,
        priceLevel: 4,
        ambianceTags: ['chic', 'business', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['speakeasy', 'cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'p04',
        name: 'Le Comptoir General',
        type: PlaceType.bar,
        latitude: 48.8704,
        longitude: 2.3672,
        address: '80 Quai de Jemmapes, 75010 Paris',
        rating: 4.3,
        reviewCount: 5600,
        priceLevel: 2,
        ambianceTags: ['festif', 'décontracté', 'insolite'],
        musicTags: ['afro', 'house'],
        styleTags: ['terrasse', 'cocktails'],
      ),
      Place(
        id: 'p05',
        name: 'Le Bar du Plaza Athenee',
        type: PlaceType.bar,
        latitude: 48.8662,
        longitude: 2.3036,
        address: '25 Avenue Montaigne, 75008 Paris',
        rating: 4.5,
        reviewCount: 880,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'p06',
        name: 'Candelaria',
        type: PlaceType.bar,
        latitude: 48.8627,
        longitude: 2.3661,
        address: '52 Rue de Saintonge, 75003 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 3,
        ambianceTags: ['branché', 'animé'],
        musicTags: ['latino', 'house'],
        styleTags: ['speakeasy', 'cocktails', 'mexicain'],
      ),
      Place(
        id: 'p07',
        name: 'Le Syndicat',
        type: PlaceType.bar,
        latitude: 48.8718,
        longitude: 2.3530,
        address: '51 Rue du Faubourg Saint-Denis, 75010 Paris',
        rating: 4.5,
        reviewCount: 1300,
        priceLevel: 3,
        ambianceTags: ['branché', 'intimiste'],
        musicTags: ['soul', 'funk'],
        styleTags: ['cocktails', 'speakeasy'],
      ),
      Place(
        id: 'p08',
        name: 'Experimental Cocktail Club',
        type: PlaceType.bar,
        latitude: 48.8662,
        longitude: 2.3486,
        address: '37 Rue Saint-Sauveur, 75002 Paris',
        rating: 4.4,
        reviewCount: 1750,
        priceLevel: 3,
        ambianceTags: ['animé', 'branché'],
        musicTags: ['house', 'funk'],
        styleTags: ['cocktails', 'speakeasy'],
      ),
      Place(
        id: 'p09',
        name: 'La Belle Hortense',
        type: PlaceType.bar,
        latitude: 48.8570,
        longitude: 2.3588,
        address: '31 Rue Vieille du Temple, 75004 Paris',
        rating: 4.3,
        reviewCount: 640,
        priceLevel: 2,
        ambianceTags: ['cosy', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['vins nature', 'bistrot'],
      ),
      Place(
        id: 'p10',
        name: 'Septime La Cave',
        type: PlaceType.bar,
        latitude: 48.8537,
        longitude: 2.3805,
        address: '3 Rue Basfroi, 75011 Paris',
        rating: 4.5,
        reviewCount: 720,
        priceLevel: 2,
        ambianceTags: ['cosy', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['vins nature'],
      ),
      Place(
        id: 'p11',
        name: 'BrewDog Paris',
        type: PlaceType.bar,
        latitude: 48.8602,
        longitude: 2.3705,
        address: '11 Rue Amelot, 75011 Paris',
        rating: 4.2,
        reviewCount: 2400,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'animé'],
        musicTags: ['rock', 'pop'],
        styleTags: ['bière artisanale', 'terrasse'],
      ),
      Place(
        id: 'p12',
        name: 'Rosa Bonheur',
        type: PlaceType.bar,
        latitude: 48.8800,
        longitude: 2.3830,
        address: '2 Allee de la Cascade, 75019 Paris',
        rating: 4.2,
        reviewCount: 6200,
        priceLevel: 2,
        ambianceTags: ['festif', 'familial', 'décontracté'],
        musicTags: ['pop', 'latino'],
        styleTags: ['terrasse', 'jardin'],
      ),
      Place(
        id: 'p13',
        name: 'Rex Club',
        type: PlaceType.bar,
        latitude: 48.8704,
        longitude: 2.3470,
        address: '5 Boulevard Poissonniere, 75002 Paris',
        rating: 4.4,
        reviewCount: 3800,
        priceLevel: 3,
        ambianceTags: ['festif', 'animé'],
        musicTags: ['techno', 'house'],
        styleTags: ['club'],
      ),
      Place(
        id: 'p14',
        name: 'Sacre Rooftop',
        type: PlaceType.bar,
        latitude: 48.8867,
        longitude: 2.3431,
        address: '18e arrondissement, 75018 Paris',
        rating: 4.2,
        reviewCount: 410,
        priceLevel: 2,
        ambianceTags: ['festif', 'romantique'],
        musicTags: ['house', 'pop'],
        styleTags: ['rooftop', 'terrasse', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p15',
        name: 'Cravan',
        type: PlaceType.bar,
        latitude: 48.8556,
        longitude: 2.3401,
        address: '17 Rue Jean de la Fontaine, 75016 Paris',
        rating: 4.6,
        reviewCount: 520,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['speakeasy', 'cocktails'],
      ),
      Place(
        id: 'p16',
        name: 'Bisou',
        type: PlaceType.bar,
        latitude: 48.8615,
        longitude: 2.3672,
        address: '15 Boulevard du Temple, 75003 Paris',
        rating: 4.5,
        reviewCount: 980,
        priceLevel: 2,
        ambianceTags: ['branché', 'intimiste'],
        musicTags: ['soul'],
        styleTags: ['cocktails'],
      ),

      // ===================== RESTAURANTS =====================
      Place(
        id: 'p17',
        name: 'Septime',
        type: PlaceType.restaurant,
        latitude: 48.8536,
        longitude: 2.3819,
        address: '80 Rue de Charonne, 75011 Paris',
        rating: 4.6,
        reviewCount: 3100,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'p18',
        name: 'Bouillon Pigalle',
        type: PlaceType.restaurant,
        latitude: 48.8823,
        longitude: 2.3375,
        address: '22 Boulevard de Clichy, 75018 Paris',
        rating: 4.4,
        reviewCount: 14800,
        priceLevel: 1,
        ambianceTags: ['festif', 'familial', 'décontracté'],
        musicTags: ['pop'],
        styleTags: ['bistrot', 'brunch'],
      ),
      Place(
        id: 'p19',
        name: 'Le Jules Verne',
        type: PlaceType.restaurant,
        latitude: 48.8582,
        longitude: 2.2945,
        address: 'Tour Eiffel, Avenue Gustave Eiffel, 75007 Paris',
        rating: 4.5,
        reviewCount: 2200,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p20',
        name: 'Holybelly 5',
        type: PlaceType.restaurant,
        latitude: 48.8717,
        longitude: 2.3592,
        address: '5 Rue Lucien Sampaix, 75010 Paris',
        rating: 4.5,
        reviewCount: 4300,
        priceLevel: 2,
        ambianceTags: ['cosy', 'décontracté'],
        musicTags: ['pop', 'soul'],
        styleTags: ['brunch'],
      ),
      Place(
        id: 'p21',
        name: 'Clamato',
        type: PlaceType.restaurant,
        latitude: 48.8534,
        longitude: 2.3812,
        address: '80 Rue de Charonne, 75011 Paris',
        rating: 4.4,
        reviewCount: 1500,
        priceLevel: 3,
        ambianceTags: ['cosy', 'branché'],
        musicTags: ['jazz'],
        styleTags: ['fruits de mer', 'vins nature'],
      ),
      Place(
        id: 'p22',
        name: "Le Relais de l'Entrecote",
        type: PlaceType.restaurant,
        latitude: 48.8707,
        longitude: 2.3076,
        address: '15 Rue Marbeuf, 75008 Paris',
        rating: 4.2,
        reviewCount: 9200,
        priceLevel: 2,
        ambianceTags: ['business', 'animé'],
        musicTags: ['lounge'],
        styleTags: ['steakhouse'],
      ),
      Place(
        id: 'p23',
        name: 'Brasserie Lipp',
        type: PlaceType.restaurant,
        latitude: 48.8540,
        longitude: 2.3331,
        address: '151 Boulevard Saint-Germain, 75006 Paris',
        rating: 4.1,
        reviewCount: 5200,
        priceLevel: 3,
        ambianceTags: ['business', 'chic'],
        musicTags: ['jazz'],
        styleTags: ['brasserie', 'terrasse'],
      ),
      Place(
        id: 'p24',
        name: 'East Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8519,
        longitude: 2.3782,
        address: '133 Rue du Faubourg Saint-Antoine, 75011 Paris',
        rating: 4.4,
        reviewCount: 11200,
        priceLevel: 2,
        ambianceTags: ['animé', 'familial', 'festif'],
        musicTags: ['pop'],
        styleTags: ['italien', 'pizza'],
      ),
      Place(
        id: 'p25',
        name: 'Pink Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8819,
        longitude: 2.3375,
        address: '20bis Rue de Douai, 75009 Paris',
        rating: 4.5,
        reviewCount: 13900,
        priceLevel: 3,
        ambianceTags: ['branché', 'animé'],
        musicTags: ['pop', 'soul'],
        styleTags: ['italien', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'p26',
        name: 'Kodawari Ramen',
        type: PlaceType.restaurant,
        latitude: 48.8530,
        longitude: 2.3360,
        address: '29 Rue Mazarine, 75006 Paris',
        rating: 4.4,
        reviewCount: 4100,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'animé', 'insolite'],
        musicTags: ['pop'],
        styleTags: ['japonais'],
      ),
      Place(
        id: 'p27',
        name: 'Sushi B',
        type: PlaceType.restaurant,
        latitude: 48.8676,
        longitude: 2.3360,
        address: '5 Rue Rameau, 75002 Paris',
        rating: 4.7,
        reviewCount: 560,
        priceLevel: 4,
        ambianceTags: ['chic', 'intimiste'],
        musicTags: ['lounge'],
        styleTags: ['japonais', 'gastronomique'],
        isPremium: true,
      ),
      Place(
        id: 'p28',
        name: 'Liza',
        type: PlaceType.restaurant,
        latitude: 48.8676,
        longitude: 2.3399,
        address: '14 Rue de la Banque, 75002 Paris',
        rating: 4.4,
        reviewCount: 2300,
        priceLevel: 3,
        ambianceTags: ['cosy', 'romantique'],
        musicTags: ['lounge', 'latino'],
        styleTags: ['libanais'],
      ),
      Place(
        id: 'p29',
        name: 'Desi Road',
        type: PlaceType.restaurant,
        latitude: 48.8543,
        longitude: 2.3330,
        address: '14 Rue Dauphine, 75006 Paris',
        rating: 4.3,
        reviewCount: 1900,
        priceLevel: 2,
        ambianceTags: ['cosy', 'familial'],
        musicTags: ['latino'],
        styleTags: ['indien'],
      ),
      Place(
        id: 'p30',
        name: 'Lao Siam',
        type: PlaceType.restaurant,
        latitude: 48.8722,
        longitude: 2.3826,
        address: '49 Rue de Belleville, 75019 Paris',
        rating: 4.4,
        reviewCount: 3600,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'familial', 'animé'],
        musicTags: ['pop'],
        styleTags: ['thai'],
      ),
      Place(
        id: 'p31',
        name: 'Pho 14',
        type: PlaceType.restaurant,
        latitude: 48.8270,
        longitude: 2.3590,
        address: '129 Avenue de Choisy, 75013 Paris',
        rating: 4.3,
        reviewCount: 5400,
        priceLevel: 1,
        ambianceTags: ['décontracté', 'familial'],
        musicTags: ['pop'],
        styleTags: ['vietnamien'],
      ),
      Place(
        id: 'p32',
        name: 'Le Coq Rico',
        type: PlaceType.restaurant,
        latitude: 48.8867,
        longitude: 2.3409,
        address: '98 Rue Lepic, 75018 Paris',
        rating: 4.3,
        reviewCount: 1800,
        priceLevel: 4,
        ambianceTags: ['chic', 'familial'],
        musicTags: ['jazz'],
        styleTags: ['gastronomique', 'terrasse'],
      ),
      Place(
        id: 'p33',
        name: 'Big Fernand',
        type: PlaceType.restaurant,
        latitude: 48.8730,
        longitude: 2.3470,
        address: '55 Rue du Faubourg Poissonniere, 75009 Paris',
        rating: 4.3,
        reviewCount: 6700,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'animé', 'familial'],
        musicTags: ['rock', 'pop'],
        styleTags: ['burger'],
      ),
      Place(
        id: 'p34',
        name: 'PNY (Paris New York)',
        type: PlaceType.restaurant,
        latitude: 48.8702,
        longitude: 2.3548,
        address: '50 Rue du Faubourg Saint-Denis, 75010 Paris',
        rating: 4.4,
        reviewCount: 8200,
        priceLevel: 2,
        ambianceTags: ['branché', 'décontracté'],
        musicTags: ['funk', 'soul'],
        styleTags: ['burger'],
      ),
      Place(
        id: 'p35',
        name: 'Wild & The Moon',
        type: PlaceType.restaurant,
        latitude: 48.8616,
        longitude: 2.3662,
        address: '55 Rue Charlot, 75003 Paris',
        rating: 4.2,
        reviewCount: 2100,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['vegan', 'brunch'],
      ),
      Place(
        id: 'p36',
        name: 'Le Potager du Marais',
        type: PlaceType.restaurant,
        latitude: 48.8617,
        longitude: 2.3565,
        address: '24 Rue Rambuteau, 75003 Paris',
        rating: 4.3,
        reviewCount: 1600,
        priceLevel: 2,
        ambianceTags: ['cosy', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['vegan'],
      ),
      Place(
        id: 'p37',
        name: 'Breizh Cafe',
        type: PlaceType.restaurant,
        latitude: 48.8593,
        longitude: 2.3637,
        address: '109 Rue Vieille du Temple, 75003 Paris',
        rating: 4.4,
        reviewCount: 9100,
        priceLevel: 2,
        ambianceTags: ['cosy', 'familial'],
        musicTags: ['pop'],
        styleTags: ['crêperie'],
      ),
      Place(
        id: 'p38',
        name: 'Hero',
        type: PlaceType.restaurant,
        latitude: 48.8662,
        longitude: 2.3470,
        address: '289 Rue Saint-Denis, 75002 Paris',
        rating: 4.3,
        reviewCount: 2700,
        priceLevel: 2,
        ambianceTags: ['animé', 'branché'],
        musicTags: ['funk', 'soul'],
        styleTags: ['coréen', 'cocktails'],
      ),
      Place(
        id: 'p39',
        name: 'Anahuacalli',
        type: PlaceType.restaurant,
        latitude: 48.8487,
        longitude: 2.3501,
        address: '30 Rue des Bernardins, 75005 Paris',
        rating: 4.4,
        reviewCount: 1400,
        priceLevel: 3,
        ambianceTags: ['cosy', 'familial', 'romantique'],
        musicTags: ['latino'],
        styleTags: ['mexicain'],
      ),
      Place(
        id: 'p40',
        name: 'La Coupole',
        type: PlaceType.restaurant,
        latitude: 48.8419,
        longitude: 2.3290,
        address: '102 Boulevard du Montparnasse, 75014 Paris',
        rating: 4.2,
        reviewCount: 12800,
        priceLevel: 3,
        ambianceTags: ['business', 'festif', 'chic'],
        musicTags: ['jazz'],
        styleTags: ['brasserie', 'terrasse'],
      ),
      Place(
        id: 'p41',
        name: 'Le Tout-Paris',
        type: PlaceType.restaurant,
        latitude: 48.8585,
        longitude: 2.3470,
        address: 'Cheval Blanc, 8 Quai du Louvre, 75001 Paris',
        rating: 4.5,
        reviewCount: 880,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'rooftop', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p42',
        name: 'Bouillon Republique',
        type: PlaceType.restaurant,
        latitude: 48.8674,
        longitude: 2.3636,
        address: '39 Boulevard du Temple, 75003 Paris',
        rating: 4.3,
        reviewCount: 8900,
        priceLevel: 1,
        ambianceTags: ['festif', 'familial', 'décontracté'],
        musicTags: ['pop'],
        styleTags: ['bistrot'],
      ),

      // ===================== HOTELS =====================
      Place(
        id: 'p43',
        name: 'Hotel Costes',
        type: PlaceType.hotel,
        latitude: 48.8676,
        longitude: 2.3274,
        address: '239 Rue Saint-Honore, 75001 Paris',
        rating: 4.4,
        reviewCount: 1800,
        priceLevel: 4,
        ambianceTags: ['chic', 'festif'],
        musicTags: ['lounge', 'house'],
        styleTags: ['palace', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'p44',
        name: 'Le Pavillon de la Reine',
        type: PlaceType.hotel,
        latitude: 48.8556,
        longitude: 2.3661,
        address: '28 Place des Vosges, 75003 Paris',
        rating: 4.7,
        reviewCount: 950,
        priceLevel: 4,
        ambianceTags: ['romantique', 'chic', 'intimiste'],
        musicTags: ['lounge'],
        styleTags: ['boutique-hôtel', 'jardin'],
      ),
      Place(
        id: 'p45',
        name: 'Hotel Grand Amour',
        type: PlaceType.hotel,
        latitude: 48.8714,
        longitude: 2.3550,
        address: '18 Rue de la Fidelite, 75010 Paris',
        rating: 4.3,
        reviewCount: 1100,
        priceLevel: 3,
        ambianceTags: ['cosy', 'festif', 'branché'],
        musicTags: ['pop', 'afro'],
        styleTags: ['boutique-hôtel', 'design', 'terrasse'],
      ),
      Place(
        id: 'p46',
        name: 'Generator Paris',
        type: PlaceType.hotel,
        latitude: 48.8809,
        longitude: 2.3700,
        address: '9-11 Place du Colonel Fabien, 75010 Paris',
        rating: 4.1,
        reviewCount: 6400,
        priceLevel: 2,
        ambianceTags: ['festif', 'décontracté', 'business'],
        musicTags: ['house', 'pop'],
        styleTags: ['rooftop', 'vue Tour Eiffel'],
      ),
      Place(
        id: 'p47',
        name: 'Mama Shelter Paris East',
        type: PlaceType.hotel,
        latitude: 48.8676,
        longitude: 2.4053,
        address: '109 Rue de Bagnolet, 75020 Paris',
        rating: 4.2,
        reviewCount: 3900,
        priceLevel: 2,
        ambianceTags: ['festif', 'décontracté', 'familial'],
        musicTags: ['afro', 'house'],
        styleTags: ['rooftop', 'design'],
      ),
      Place(
        id: 'p48',
        name: 'Le Bristol Paris',
        type: PlaceType.hotel,
        latitude: 48.8721,
        longitude: 2.3157,
        address: '112 Rue du Faubourg Saint-Honore, 75008 Paris',
        rating: 4.8,
        reviewCount: 2600,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace', 'jardin'],
        isPremium: true,
      ),
      Place(
        id: 'p49',
        name: 'Hotel Particulier Montmartre',
        type: PlaceType.hotel,
        latitude: 48.8876,
        longitude: 2.3380,
        address: '23 Avenue Junot, 75018 Paris',
        rating: 4.5,
        reviewCount: 720,
        priceLevel: 4,
        ambianceTags: ['romantique', 'intimiste', 'insolite'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['boutique-hôtel', 'jardin'],
        isPremium: true,
      ),
      Place(
        id: 'p50',
        name: 'CitizenM Paris Gare de Lyon',
        type: PlaceType.hotel,
        latitude: 48.8443,
        longitude: 2.3743,
        address: '17 Boulevard Diderot, 75012 Paris',
        rating: 4.4,
        reviewCount: 4800,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'business', 'branché'],
        musicTags: ['house'],
        styleTags: ['design', 'rooftop'],
      ),
      Place(
        id: 'p51',
        name: 'Hotel Providence',
        type: PlaceType.hotel,
        latitude: 48.8709,
        longitude: 2.3555,
        address: '90 Rue Rene Boulanger, 75010 Paris',
        rating: 4.4,
        reviewCount: 1300,
        priceLevel: 3,
        ambianceTags: ['cosy', 'romantique', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['boutique-hôtel', 'cocktails'],
      ),
      Place(
        id: 'p52',
        name: 'OFF Paris Seine',
        type: PlaceType.hotel,
        latitude: 48.8388,
        longitude: 2.3736,
        address: "20-22 Port d'Austerlitz, 75013 Paris",
        rating: 4.2,
        reviewCount: 2200,
        priceLevel: 3,
        ambianceTags: ['insolite', 'branché', 'romantique'],
        musicTags: ['lounge', 'house'],
        styleTags: ['péniche', 'design', 'terrasse'],
      ),
      Place(
        id: 'p53',
        name: 'Hotel Molitor',
        type: PlaceType.hotel,
        latitude: 48.8447,
        longitude: 2.2530,
        address: '13 Rue Nungesser et Coli, 75016 Paris',
        rating: 4.4,
        reviewCount: 3400,
        priceLevel: 4,
        ambianceTags: ['branché', 'festif', 'familial'],
        musicTags: ['house', 'pop'],
        styleTags: ['design', 'rooftop'],
        isPremium: true,
      ),
      Place(
        id: 'p54',
        name: 'Mob Hotel Les Puces',
        type: PlaceType.hotel,
        latitude: 48.9018,
        longitude: 2.3447,
        address: '4-6 Rue Gambetta, 93400 Saint-Ouen',
        rating: 4.2,
        reviewCount: 2900,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'familial', 'branché'],
        musicTags: ['afro', 'funk'],
        styleTags: ['rooftop', 'terrasse', 'design'],
      ),

      // ===================== BARS / ROOFTOPS (suite) =====================
      Place(
        id: 'p55',
        name: 'Le Perchoir Menilmontant',
        type: PlaceType.bar,
        latitude: 48.8668,
        longitude: 2.3897,
        address: '14 Rue Crespin du Gast, 75011 Paris',
        rating: 4.3,
        reviewCount: 6100,
        priceLevel: 3,
        ambianceTags: ['festif', 'branché'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'terrasse', 'cocktails', 'vue Tour Eiffel'],
      ),
      Place(
        id: 'p56',
        name: 'Le Tres Particulier',
        type: PlaceType.bar,
        latitude: 48.8884,
        longitude: 2.3375,
        address: '23 Avenue Junot, 75018 Paris',
        rating: 4.4,
        reviewCount: 2400,
        priceLevel: 4,
        ambianceTags: ['intimiste', 'romantique', 'insolite'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['speakeasy', 'jardin', 'cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'p57',
        name: 'Moonshiner',
        type: PlaceType.bar,
        latitude: 48.8554,
        longitude: 2.3739,
        address: '5 Rue Sedaine, 75011 Paris',
        rating: 4.5,
        reviewCount: 1700,
        priceLevel: 2,
        ambianceTags: ['intimiste', 'branché'],
        musicTags: ['jazz', 'soul'],
        styleTags: ['speakeasy', 'cocktails'],
      ),
      Place(
        id: 'p58',
        name: 'Lavomatic',
        type: PlaceType.bar,
        latitude: 48.8675,
        longitude: 2.3656,
        address: '30 Rue Rene Boulanger, 75010 Paris',
        rating: 4.3,
        reviewCount: 2900,
        priceLevel: 2,
        ambianceTags: ['branché', 'insolite', 'animé'],
        musicTags: ['funk', 'house'],
        styleTags: ['speakeasy', 'cocktails'],
      ),
      Place(
        id: 'p59',
        name: 'Dirty Dick',
        type: PlaceType.bar,
        latitude: 48.8817,
        longitude: 2.3372,
        address: '10 Rue Frochot, 75009 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 2,
        ambianceTags: ['festif', 'animé', 'insolite'],
        musicTags: ['latino', 'pop'],
        styleTags: ['cocktails'],
      ),
      Place(
        id: 'p60',
        name: 'Combat',
        type: PlaceType.bar,
        latitude: 48.8721,
        longitude: 2.3847,
        address: '63 Rue de Belleville, 75019 Paris',
        rating: 4.5,
        reviewCount: 1500,
        priceLevel: 2,
        ambianceTags: ['cosy', 'branché'],
        musicTags: ['soul', 'funk'],
        styleTags: ['cocktails', 'vins nature'],
      ),
      Place(
        id: 'p61',
        name: 'Bar Botaniste (Shangri-La)',
        type: PlaceType.bar,
        latitude: 48.8639,
        longitude: 2.2898,
        address: '10 Avenue d Iena, 75116 Paris',
        rating: 4.6,
        reviewCount: 640,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge', 'jazz'],
        styleTags: ['cocktails'],
        isPremium: true,
      ),
      Place(
        id: 'p62',
        name: 'Le Mary Celeste',
        type: PlaceType.bar,
        latitude: 48.8624,
        longitude: 2.3631,
        address: '1 Rue Commines, 75003 Paris',
        rating: 4.3,
        reviewCount: 1300,
        priceLevel: 3,
        ambianceTags: ['branché', 'cosy'],
        musicTags: ['lounge', 'soul'],
        styleTags: ['cocktails', 'fruits de mer'],
      ),

      // ===================== RESTAURANTS (suite) =====================
      Place(
        id: 'p63',
        name: 'Le Chateaubriand',
        type: PlaceType.restaurant,
        latitude: 48.8669,
        longitude: 2.3717,
        address: '129 Avenue Parmentier, 75011 Paris',
        rating: 4.4,
        reviewCount: 2600,
        priceLevel: 4,
        ambianceTags: ['chic', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique'],
        isPremium: true,
      ),
      Place(
        id: 'p64',
        name: 'Frenchie',
        type: PlaceType.restaurant,
        latitude: 48.8662,
        longitude: 2.3486,
        address: '5 Rue du Nil, 75002 Paris',
        rating: 4.5,
        reviewCount: 3300,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['gastronomique', 'bistrot'],
        isPremium: true,
      ),
      Place(
        id: 'p65',
        name: 'Bistrot Paul Bert',
        type: PlaceType.restaurant,
        latitude: 48.8527,
        longitude: 2.3849,
        address: '18 Rue Paul Bert, 75011 Paris',
        rating: 4.4,
        reviewCount: 4200,
        priceLevel: 3,
        ambianceTags: ['cosy', 'romantique'],
        musicTags: ['jazz'],
        styleTags: ['bistrot', 'terrasse'],
      ),
      Place(
        id: 'p66',
        name: 'Chez Janou',
        type: PlaceType.restaurant,
        latitude: 48.8564,
        longitude: 2.3671,
        address: '2 Rue Roger Verlomme, 75003 Paris',
        rating: 4.4,
        reviewCount: 7800,
        priceLevel: 2,
        ambianceTags: ['festif', 'cosy', 'familial'],
        musicTags: ['lounge'],
        styleTags: ['bistrot', 'terrasse'],
      ),
      Place(
        id: 'p67',
        name: "L'As du Fallafel",
        type: PlaceType.restaurant,
        latitude: 48.8576,
        longitude: 2.3593,
        address: '34 Rue des Rosiers, 75004 Paris',
        rating: 4.4,
        reviewCount: 16200,
        priceLevel: 1,
        ambianceTags: ['décontracté', 'animé', 'familial'],
        musicTags: ['pop'],
        styleTags: ['libanais'],
      ),
      Place(
        id: 'p68',
        name: 'Miznon',
        type: PlaceType.restaurant,
        latitude: 48.8580,
        longitude: 2.3590,
        address: '22 Rue des Ecouffes, 75004 Paris',
        rating: 4.4,
        reviewCount: 5900,
        priceLevel: 2,
        ambianceTags: ['animé', 'décontracté'],
        musicTags: ['pop', 'latino'],
        styleTags: ['libanais', 'vegan'],
      ),
      Place(
        id: 'p69',
        name: 'Ober Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8615,
        longitude: 2.3739,
        address: '107 Boulevard Richard-Lenoir, 75011 Paris',
        rating: 4.4,
        reviewCount: 12100,
        priceLevel: 2,
        ambianceTags: ['animé', 'festif', 'familial'],
        musicTags: ['pop'],
        styleTags: ['italien', 'pizza'],
      ),
      Place(
        id: 'p70',
        name: 'Blueberry Maki Bar',
        type: PlaceType.restaurant,
        latitude: 48.8518,
        longitude: 2.3360,
        address: '6 Rue du Sabot, 75006 Paris',
        rating: 4.5,
        reviewCount: 1100,
        priceLevel: 3,
        ambianceTags: ['cosy', 'branché'],
        musicTags: ['lounge'],
        styleTags: ['japonais'],
      ),
      Place(
        id: 'p71',
        name: 'Dumbo',
        type: PlaceType.restaurant,
        latitude: 48.8666,
        longitude: 2.3679,
        address: '20 Rue Rambuteau, 75003 Paris',
        rating: 4.5,
        reviewCount: 4600,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'animé', 'branché'],
        musicTags: ['funk', 'soul'],
        styleTags: ['burger'],
      ),
      Place(
        id: 'p72',
        name: "Chez l'Ami Jean",
        type: PlaceType.restaurant,
        latitude: 48.8588,
        longitude: 2.3050,
        address: '27 Rue Malar, 75007 Paris',
        rating: 4.5,
        reviewCount: 2200,
        priceLevel: 3,
        ambianceTags: ['cosy', 'animé'],
        musicTags: ['jazz'],
        styleTags: ['bistrot', 'gastronomique'],
      ),
      Place(
        id: 'p73',
        name: 'Angelina',
        type: PlaceType.restaurant,
        latitude: 48.8654,
        longitude: 2.3284,
        address: '226 Rue de Rivoli, 75001 Paris',
        rating: 4.4,
        reviewCount: 18900,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique', 'familial'],
        musicTags: ['lounge'],
        styleTags: ['brunch', 'terrasse'],
      ),
      Place(
        id: 'p74',
        name: 'Le Servan',
        type: PlaceType.restaurant,
        latitude: 48.8636,
        longitude: 2.3809,
        address: '32 Rue Saint-Maur, 75011 Paris',
        rating: 4.4,
        reviewCount: 1500,
        priceLevel: 3,
        ambianceTags: ['cosy', 'branché', 'romantique'],
        musicTags: ['jazz'],
        styleTags: ['gastronomique', 'bistrot'],
      ),

      // ===================== HOTELS (suite) =====================
      Place(
        id: 'p75',
        name: 'Ritz Paris',
        type: PlaceType.hotel,
        latitude: 48.8681,
        longitude: 2.3284,
        address: '15 Place Vendome, 75001 Paris',
        rating: 4.8,
        reviewCount: 3600,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace', 'jardin'],
        isPremium: true,
      ),
      Place(
        id: 'p76',
        name: 'Four Seasons George V',
        type: PlaceType.hotel,
        latitude: 48.8686,
        longitude: 2.3008,
        address: '31 Avenue George V, 75008 Paris',
        rating: 4.8,
        reviewCount: 4100,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace'],
        isPremium: true,
      ),
      Place(
        id: 'p77',
        name: 'Le Meurice',
        type: PlaceType.hotel,
        latitude: 48.8654,
        longitude: 2.3281,
        address: '228 Rue de Rivoli, 75001 Paris',
        rating: 4.7,
        reviewCount: 2900,
        priceLevel: 4,
        ambianceTags: ['chic', 'business'],
        musicTags: ['lounge'],
        styleTags: ['palace'],
        isPremium: true,
      ),
      Place(
        id: 'p78',
        name: 'The Hoxton Paris',
        type: PlaceType.hotel,
        latitude: 48.8688,
        longitude: 2.3506,
        address: '30-32 Rue du Sentier, 75002 Paris',
        rating: 4.4,
        reviewCount: 3200,
        priceLevel: 3,
        ambianceTags: ['branché', 'cosy', 'business'],
        musicTags: ['house', 'soul'],
        styleTags: ['boutique-hôtel', 'design'],
      ),
      Place(
        id: 'p79',
        name: 'SO/ Paris',
        type: PlaceType.hotel,
        latitude: 48.8520,
        longitude: 2.3610,
        address: '10 Rue Agrippa d Aubigne, 75004 Paris',
        rating: 4.5,
        reviewCount: 1800,
        priceLevel: 4,
        ambianceTags: ['branché', 'festif', 'chic'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'design', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p80',
        name: 'Brach Paris',
        type: PlaceType.hotel,
        latitude: 48.8636,
        longitude: 2.2820,
        address: '1-7 Rue Jean Richepin, 75116 Paris',
        rating: 4.6,
        reviewCount: 1400,
        priceLevel: 4,
        ambianceTags: ['branché', 'chic', 'cosy'],
        musicTags: ['lounge', 'soul'],
        styleTags: ['design', 'rooftop'],
        isPremium: true,
      ),
      Place(
        id: 'p81',
        name: 'Hotel Rochechouart',
        type: PlaceType.hotel,
        latitude: 48.8820,
        longitude: 2.3437,
        address: '55 Boulevard de Rochechouart, 75009 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 3,
        ambianceTags: ['festif', 'branché', 'décontracté'],
        musicTags: ['house', 'pop'],
        styleTags: ['rooftop', 'design', 'terrasse'],
      ),
      Place(
        id: 'p82',
        name: 'Kimpton St Honore',
        type: PlaceType.hotel,
        latitude: 48.8712,
        longitude: 2.3349,
        address: '27-29 Boulevard des Capucines, 75002 Paris',
        rating: 4.5,
        reviewCount: 1600,
        priceLevel: 4,
        ambianceTags: ['branché', 'chic', 'festif'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'design', 'vue Tour Eiffel'],
        isPremium: true,
      ),
      Place(
        id: 'p83',
        name: '25hours Hotel Terminus Nord',
        type: PlaceType.hotel,
        latitude: 48.8810,
        longitude: 2.3573,
        address: '12 Boulevard de Denain, 75010 Paris',
        rating: 4.3,
        reviewCount: 2400,
        priceLevel: 2,
        ambianceTags: ['branché', 'décontracté', 'familial'],
        musicTags: ['funk', 'afro'],
        styleTags: ['design', 'boutique-hôtel'],
      ),
      Place(
        id: 'p84',
        name: 'Hotel National des Arts et Metiers',
        type: PlaceType.hotel,
        latitude: 48.8659,
        longitude: 2.3560,
        address: '243 Rue Saint-Martin, 75003 Paris',
        rating: 4.4,
        reviewCount: 1900,
        priceLevel: 3,
        ambianceTags: ['branché', 'romantique', 'cosy'],
        musicTags: ['lounge', 'house'],
        styleTags: ['rooftop', 'design', 'boutique-hôtel'],
      ),

      // ===================== RESTAURANTS (suite 2) =====================
      Place(
        id: 'p85',
        name: 'Septime',
        type: PlaceType.restaurant,
        latitude: 48.8540,
        longitude: 2.3785,
        address: '80 Rue de Charonne, 75011 Paris',
        rating: 4.7,
        reviewCount: 3200,
        priceLevel: 3,
        ambianceTags: ['chic', 'intimiste', 'romantique'],
        musicTags: ['jazz', 'soul'],
        styleTags: ['gastronomique', 'vins nature'],
        isPremium: true,
      ),
      Place(
        id: 'p86',
        name: 'Frenchie',
        type: PlaceType.restaurant,
        latitude: 48.8639,
        longitude: 2.3473,
        address: '5 Rue du Nil, 75002 Paris',
        rating: 4.6,
        reviewCount: 2800,
        priceLevel: 3,
        ambianceTags: ['chic', 'branché', 'intimiste'],
        musicTags: ['jazz', 'soul'],
        styleTags: ['gastronomique', 'brunch'],
        isPremium: true,
      ),
      Place(
        id: 'p87',
        name: 'Le Comptoir du Relais',
        type: PlaceType.restaurant,
        latitude: 48.8531,
        longitude: 2.3355,
        address: '9 Carrefour de l\'Odeon, 75006 Paris',
        rating: 4.4,
        reviewCount: 4200,
        priceLevel: 2,
        ambianceTags: ['animé', 'décontracté', 'romantique'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['bistrot', 'terrasse'],
      ),
      Place(
        id: 'p88',
        name: 'Cafe de Flore',
        type: PlaceType.restaurant,
        latitude: 48.8539,
        longitude: 2.3330,
        address: '172 Boulevard Saint-Germain, 75006 Paris',
        rating: 4.1,
        reviewCount: 12000,
        priceLevel: 3,
        ambianceTags: ['chic', 'animé', 'romantique'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['brasserie', 'terrasse'],
      ),
      Place(
        id: 'p89',
        name: 'Holybelly',
        type: PlaceType.restaurant,
        latitude: 48.8674,
        longitude: 2.3612,
        address: '19 Rue Lucien Sampaix, 75010 Paris',
        rating: 4.5,
        reviewCount: 5600,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'branché', 'familial'],
        musicTags: ['pop', 'soul'],
        styleTags: ['brunch', 'vegan'],
      ),
      Place(
        id: 'p90',
        name: 'Bouillon Pigalle',
        type: PlaceType.restaurant,
        latitude: 48.8824,
        longitude: 2.3482,
        address: '22 Boulevard de Clichy, 75018 Paris',
        rating: 4.3,
        reviewCount: 8900,
        priceLevel: 1,
        ambianceTags: ['animé', 'familial', 'décontracté'],
        musicTags: ['pop', 'funk'],
        styleTags: ['brasserie'],
      ),
      Place(
        id: 'p91',
        name: 'Mokonuts',
        type: PlaceType.restaurant,
        latitude: 48.8554,
        longitude: 2.3784,
        address: '5 Rue Saint-Bernard, 75011 Paris',
        rating: 4.6,
        reviewCount: 1800,
        priceLevel: 2,
        ambianceTags: ['cosy', 'décontracté', 'intimiste'],
        musicTags: ['soul', 'pop'],
        styleTags: ['brunch', 'vegan'],
      ),
      Place(
        id: 'p92',
        name: 'Chez L\'Ami Jean',
        type: PlaceType.restaurant,
        latitude: 48.8596,
        longitude: 2.3078,
        address: '27 Rue Malar, 75007 Paris',
        rating: 4.5,
        reviewCount: 3100,
        priceLevel: 2,
        ambianceTags: ['animé', 'décontracté', 'familial'],
        musicTags: ['jazz', 'folk'],
        styleTags: ['bistrot', 'gastronomique'],
      ),
      Place(
        id: 'p93',
        name: 'Le Baratin',
        type: PlaceType.restaurant,
        latitude: 48.8677,
        longitude: 2.3965,
        address: '3 Rue Jouye-Rouve, 75020 Paris',
        rating: 4.4,
        reviewCount: 1400,
        priceLevel: 2,
        ambianceTags: ['intimiste', 'décontracté', 'branché'],
        musicTags: ['jazz', 'soul'],
        styleTags: ['bistrot', 'vins nature'],
      ),
      Place(
        id: 'p94',
        name: 'Tomy & Co',
        type: PlaceType.restaurant,
        latitude: 48.8571,
        longitude: 2.3071,
        address: '22 Rue Surcouf, 75007 Paris',
        rating: 4.6,
        reviewCount: 1200,
        priceLevel: 3,
        ambianceTags: ['chic', 'intimiste', 'romantique'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['gastronomique'],
        isPremium: true,
      ),
      Place(
        id: 'p95',
        name: 'Clown Bar',
        type: PlaceType.restaurant,
        latitude: 48.8622,
        longitude: 2.3741,
        address: '114 Rue Amelot, 75011 Paris',
        rating: 4.5,
        reviewCount: 2200,
        priceLevel: 2,
        ambianceTags: ['branché', 'animé', 'insolite'],
        musicTags: ['jazz', 'afro'],
        styleTags: ['bistrot', 'vins nature'],
      ),
      Place(
        id: 'p96',
        name: 'Le Servan',
        type: PlaceType.restaurant,
        latitude: 48.8584,
        longitude: 2.3826,
        address: '32 Rue Saint-Maur, 75011 Paris',
        rating: 4.4,
        reviewCount: 2600,
        priceLevel: 2,
        ambianceTags: ['branché', 'cosy', 'animé'],
        musicTags: ['afro', 'soul'],
        styleTags: ['gastronomique', 'vietnamien', 'thai'],
      ),
      Place(
        id: 'p97',
        name: 'Bouillon Chartier',
        type: PlaceType.restaurant,
        latitude: 48.8726,
        longitude: 2.3443,
        address: '7 Rue du Faubourg Montmartre, 75009 Paris',
        rating: 4.1,
        reviewCount: 22000,
        priceLevel: 1,
        ambianceTags: ['animé', 'familial', 'insolite'],
        musicTags: ['jazz'],
        styleTags: ['brasserie'],
      ),
      Place(
        id: 'p98',
        name: 'Pink Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8822,
        longitude: 2.3435,
        address: '20ter Rue de Douai, 75009 Paris',
        rating: 4.4,
        reviewCount: 7800,
        priceLevel: 2,
        ambianceTags: ['branché', 'festif', 'romantique'],
        musicTags: ['pop', 'afro'],
        styleTags: ['italien', 'rooftop', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'p99',
        name: 'East Mamma',
        type: PlaceType.restaurant,
        latitude: 48.8531,
        longitude: 2.3766,
        address: '133 Rue du Faubourg Saint-Antoine, 75011 Paris',
        rating: 4.3,
        reviewCount: 9200,
        priceLevel: 2,
        ambianceTags: ['animé', 'festif', 'branché'],
        musicTags: ['pop', 'afro'],
        styleTags: ['italien', 'pizza'],
      ),
      Place(
        id: 'p100',
        name: 'Cafe de la Paix',
        type: PlaceType.restaurant,
        latitude: 48.8712,
        longitude: 2.3319,
        address: '5 Place de l\'Opera, 75009 Paris',
        rating: 4.3,
        reviewCount: 6500,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['brasserie', 'gastronomique', 'terrasse'],
      ),
      Place(
        id: 'p101',
        name: 'Sushi Yoshinori',
        type: PlaceType.restaurant,
        latitude: 48.8527,
        longitude: 2.3312,
        address: '18 Rue Gregoire de Tours, 75006 Paris',
        rating: 4.7,
        reviewCount: 900,
        priceLevel: 3,
        ambianceTags: ['chic', 'intimiste', 'romantique'],
        musicTags: ['lounge'],
        styleTags: ['japonais', 'gastronomique'],
        isPremium: true,
      ),
      Place(
        id: 'p102',
        name: 'Les Enfants Rouges',
        type: PlaceType.restaurant,
        latitude: 48.8625,
        longitude: 2.3607,
        address: '39 Rue de Bretagne, 75003 Paris',
        rating: 4.2,
        reviewCount: 8300,
        priceLevel: 2,
        ambianceTags: ['animé', 'familial', 'décontracté'],
        musicTags: ['pop', 'afro'],
        styleTags: ['brunch', 'marché'],
      ),
      Place(
        id: 'p103',
        name: 'Le Grand Bain',
        type: PlaceType.restaurant,
        latitude: 48.8732,
        longitude: 2.3850,
        address: '14 Rue Denoyez, 75020 Paris',
        rating: 4.5,
        reviewCount: 1600,
        priceLevel: 2,
        ambianceTags: ['branché', 'décontracté', 'animé'],
        musicTags: ['afro', 'funk'],
        styleTags: ['vegan', 'gastronomique', 'vins nature'],
      ),
      Place(
        id: 'p104',
        name: 'Yard',
        type: PlaceType.restaurant,
        latitude: 48.8609,
        longitude: 2.3742,
        address: '6 Rue de Mont-Louis, 75011 Paris',
        rating: 4.3,
        reviewCount: 1900,
        priceLevel: 2,
        ambianceTags: ['branché', 'décontracté', 'cosy'],
        musicTags: ['soul', 'pop'],
        styleTags: ['brunch', 'vins nature', 'cocktails'],
      ),

      // ===================== BARS (suite 3) =====================
      Place(
        id: 'p105',
        name: 'Little Red Door',
        type: PlaceType.bar,
        latitude: 48.8598,
        longitude: 2.3566,
        address: '60 Rue Charlot, 75003 Paris',
        rating: 4.5,
        reviewCount: 2400,
        priceLevel: 3,
        ambianceTags: ['chic', 'intimiste', 'branché'],
        musicTags: ['house', 'lounge'],
        styleTags: ['cocktails', 'speakeasy'],
        isPremium: true,
      ),
      Place(
        id: 'p106',
        name: 'Mary Celeste',
        type: PlaceType.bar,
        latitude: 48.8597,
        longitude: 2.3568,
        address: '1 Rue Commines, 75003 Paris',
        rating: 4.4,
        reviewCount: 3100,
        priceLevel: 2,
        ambianceTags: ['animé', 'branché', 'décontracté'],
        musicTags: ['afro', 'soul'],
        styleTags: ['cocktails', 'fruits de mer'],
      ),
      Place(
        id: 'p107',
        name: 'Experimental Cocktail Club',
        type: PlaceType.bar,
        latitude: 48.8619,
        longitude: 2.3441,
        address: '60 Rue de la Monnaie, 75001 Paris',
        rating: 4.5,
        reviewCount: 4200,
        priceLevel: 3,
        ambianceTags: ['chic', 'intimiste', 'branché'],
        musicTags: ['house', 'lounge'],
        styleTags: ['cocktails', 'speakeasy'],
        isPremium: true,
      ),
      Place(
        id: 'p108',
        name: 'Glass',
        type: PlaceType.bar,
        latitude: 48.8809,
        longitude: 2.3414,
        address: '7 Rue Frochot, 75009 Paris',
        rating: 4.1,
        reviewCount: 1800,
        priceLevel: 2,
        ambianceTags: ['festif', 'branché', 'animé'],
        musicTags: ['rock', 'pop'],
        styleTags: ['cocktails', 'club'],
      ),
      Place(
        id: 'p109',
        name: 'Lulu White',
        type: PlaceType.bar,
        latitude: 48.8809,
        longitude: 2.3409,
        address: '12 Rue Frochot, 75009 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 2,
        ambianceTags: ['insolite', 'intimiste', 'branché'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['cocktails', 'speakeasy'],
      ),
      Place(
        id: 'p110',
        name: 'La Cave a Michel',
        type: PlaceType.bar,
        latitude: 48.8748,
        longitude: 2.3618,
        address: '36 Rue Sainte-Marthe, 75010 Paris',
        rating: 4.5,
        reviewCount: 1600,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'cosy', 'animé'],
        musicTags: ['jazz', 'afro'],
        styleTags: ['vins nature', 'terrasse'],
      ),
      Place(
        id: 'p111',
        name: 'Sherry Butt',
        type: PlaceType.bar,
        latitude: 48.8538,
        longitude: 2.3607,
        address: '20 Rue Beautreillis, 75004 Paris',
        rating: 4.4,
        reviewCount: 2800,
        priceLevel: 2,
        ambianceTags: ['cosy', 'branché', 'intimiste'],
        musicTags: ['jazz', 'soul'],
        styleTags: ['cocktails'],
      ),
      Place(
        id: 'p112',
        name: 'Le Syndicat',
        type: PlaceType.bar,
        latitude: 48.8724,
        longitude: 2.3580,
        address: '51 Rue du Faubourg Saint-Denis, 75010 Paris',
        rating: 4.5,
        reviewCount: 2500,
        priceLevel: 2,
        ambianceTags: ['branché', 'animé', 'insolite'],
        musicTags: ['house', 'techno'],
        styleTags: ['cocktails', 'speakeasy'],
        isPremium: true,
      ),
      Place(
        id: 'p113',
        name: 'Danico',
        type: PlaceType.bar,
        latitude: 48.8645,
        longitude: 2.3456,
        address: '6 Rue Vivienne, 75002 Paris',
        rating: 4.5,
        reviewCount: 1900,
        priceLevel: 3,
        ambianceTags: ['chic', 'intimiste', 'branché'],
        musicTags: ['house', 'lounge'],
        styleTags: ['cocktails', 'speakeasy'],
      ),
      Place(
        id: 'p114',
        name: 'Au Sauvignon',
        type: PlaceType.bar,
        latitude: 48.8560,
        longitude: 2.3320,
        address: '80 Rue des Saints-Peres, 75007 Paris',
        rating: 4.2,
        reviewCount: 3400,
        priceLevel: 2,
        ambianceTags: ['cosy', 'décontracté', 'intimiste'],
        musicTags: ['jazz'],
        styleTags: ['vins nature', 'terrasse'],
      ),
      Place(
        id: 'p115',
        name: 'Brasserie Barbes',
        type: PlaceType.bar,
        latitude: 48.8827,
        longitude: 2.3482,
        address: '2 Boulevard Barbes, 75018 Paris',
        rating: 4.0,
        reviewCount: 5200,
        priceLevel: 2,
        ambianceTags: ['animé', 'décontracté', 'festif'],
        musicTags: ['afro', 'pop'],
        styleTags: ['terrasse', 'bière artisanale'],
      ),
      Place(
        id: 'p116',
        name: 'Ballroom du Beef Club',
        type: PlaceType.bar,
        latitude: 48.8624,
        longitude: 2.3477,
        address: '58 Rue Jean-Jacques Rousseau, 75001 Paris',
        rating: 4.3,
        reviewCount: 2600,
        priceLevel: 3,
        ambianceTags: ['festif', 'branché', 'insolite'],
        musicTags: ['house', 'techno'],
        styleTags: ['cocktails', 'speakeasy', 'club'],
      ),
      Place(
        id: 'p117',
        name: 'Gravity Bar',
        type: PlaceType.bar,
        latitude: 48.8751,
        longitude: 2.3578,
        address: '44 Rue des Vinaigriers, 75010 Paris',
        rating: 4.3,
        reviewCount: 1400,
        priceLevel: 2,
        ambianceTags: ['décontracté', 'branché', 'animé'],
        musicTags: ['funk', 'soul'],
        styleTags: ['bière artisanale'],
      ),

      // ===================== HOTELS (suite 3) =====================
      Place(
        id: 'p118',
        name: 'Le Grand Mazarin',
        type: PlaceType.hotel,
        latitude: 48.8577,
        longitude: 2.3545,
        address: '6 Rue des Archives, 75004 Paris',
        rating: 4.5,
        reviewCount: 1800,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique', 'cosy'],
        musicTags: ['lounge', 'jazz'],
        styleTags: ['boutique-hôtel', 'design'],
      ),
      Place(
        id: 'p119',
        name: 'Hotel du Petit Moulin',
        type: PlaceType.hotel,
        latitude: 48.8605,
        longitude: 2.3596,
        address: '29 Rue du Poitou, 75003 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 3,
        ambianceTags: ['branché', 'romantique', 'insolite'],
        musicTags: ['lounge'],
        styleTags: ['boutique-hôtel', 'design'],
        isPremium: true,
      ),
      Place(
        id: 'p120',
        name: 'Mama Shelter Paris East',
        type: PlaceType.hotel,
        latitude: 48.8699,
        longitude: 2.4038,
        address: '109 Rue de Bagnolet, 75020 Paris',
        rating: 4.2,
        reviewCount: 3800,
        priceLevel: 2,
        ambianceTags: ['festif', 'branché', 'décontracté'],
        musicTags: ['house', 'pop', 'afro'],
        styleTags: ['design', 'rooftop'],
      ),
      Place(
        id: 'p121',
        name: 'Hotel de Nell',
        type: PlaceType.hotel,
        latitude: 48.8756,
        longitude: 2.3463,
        address: '7-9 Rue du Conservatoire, 75009 Paris',
        rating: 4.5,
        reviewCount: 1600,
        priceLevel: 3,
        ambianceTags: ['cosy', 'romantique', 'chic'],
        musicTags: ['jazz', 'lounge'],
        styleTags: ['boutique-hôtel', 'design'],
      ),
      Place(
        id: 'p122',
        name: 'Hotel des Grands Boulevards',
        type: PlaceType.hotel,
        latitude: 48.8703,
        longitude: 2.3481,
        address: '17 Boulevard Poissonniere, 75002 Paris',
        rating: 4.5,
        reviewCount: 4200,
        priceLevel: 3,
        ambianceTags: ['branché', 'chic', 'romantique'],
        musicTags: ['house', 'lounge'],
        styleTags: ['boutique-hôtel', 'jardin', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'p123',
        name: 'Off Paris Seine',
        type: PlaceType.hotel,
        latitude: 48.8383,
        longitude: 2.3670,
        address: 'Port de la Gare, 75013 Paris',
        rating: 4.3,
        reviewCount: 2200,
        priceLevel: 3,
        ambianceTags: ['insolite', 'romantique', 'décontracté'],
        musicTags: ['lounge', 'afro'],
        styleTags: ['péniche', 'design'],
      ),
      Place(
        id: 'p124',
        name: 'Hotel Drouot',
        type: PlaceType.hotel,
        latitude: 48.8756,
        longitude: 2.3422,
        address: '6 Rue Drouot, 75009 Paris',
        rating: 4.3,
        reviewCount: 1400,
        priceLevel: 2,
        ambianceTags: ['cosy', 'branché', 'décontracté'],
        musicTags: ['lounge'],
        styleTags: ['boutique-hôtel', 'design'],
      ),
      Place(
        id: 'p125',
        name: 'Hotel La Louisiane',
        type: PlaceType.hotel,
        latitude: 48.8538,
        longitude: 2.3355,
        address: '60 Rue de Seine, 75006 Paris',
        rating: 4.1,
        reviewCount: 2800,
        priceLevel: 2,
        ambianceTags: ['cosy', 'romantique', 'décontracté'],
        musicTags: ['jazz'],
        styleTags: ['bistrot', 'boutique-hôtel'],
      ),

      // ===================== ROOFTOPS =====================
      Place(
        id: 'p126',
        name: 'Le Perchoir Menilmontant',
        type: PlaceType.rooftop,
        latitude: 48.8647,
        longitude: 2.3882,
        address: '14 Rue Crespin du Gast, 75011 Paris',
        rating: 4.5,
        reviewCount: 8400,
        priceLevel: 2,
        ambianceTags: ['branché', 'festif', 'animé'],
        musicTags: ['house', 'afro'],
        styleTags: ['rooftop', 'cocktails', 'vue panoramique'],
        isPremium: true,
      ),
      Place(
        id: 'p127',
        name: 'Le Perchoir Marais',
        type: PlaceType.rooftop,
        latitude: 48.8572,
        longitude: 2.3519,
        address: '33 Rue de la Verrerie, 75004 Paris',
        rating: 4.4,
        reviewCount: 6200,
        priceLevel: 2,
        ambianceTags: ['branché', 'animé', 'festif'],
        musicTags: ['house', 'lounge'],
        styleTags: ['rooftop', 'cocktails', 'vue panoramique'],
        isPremium: true,
      ),
      Place(
        id: 'p128',
        name: 'Galeries Lafayette Rooftop',
        type: PlaceType.rooftop,
        latitude: 48.8741,
        longitude: 2.3319,
        address: '40 Boulevard Haussmann, 75009 Paris',
        rating: 4.4,
        reviewCount: 25000,
        priceLevel: 1,
        ambianceTags: ['animé', 'familial', 'décontracté'],
        musicTags: [],
        styleTags: ['rooftop', 'vue panoramique', 'vue Tour Eiffel', 'gratuit'],
      ),
      Place(
        id: 'p129',
        name: 'Terrass Hotel Rooftop',
        type: PlaceType.rooftop,
        latitude: 48.8847,
        longitude: 2.3316,
        address: '12 Rue Joseph de Maistre, 75018 Paris',
        rating: 4.5,
        reviewCount: 3200,
        priceLevel: 2,
        ambianceTags: ['chic', 'romantique', 'branché'],
        musicTags: ['lounge', 'house'],
        styleTags: ['rooftop', 'vue panoramique', 'cocktails', 'terrasse'],
        isPremium: true,
      ),
      Place(
        id: 'p130',
        name: 'Maison Blanche',
        type: PlaceType.rooftop,
        latitude: 48.8735,
        longitude: 2.3025,
        address: '15 Avenue Montaigne, 75008 Paris',
        rating: 4.3,
        reviewCount: 1800,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge', 'house'],
        styleTags: ['rooftop', 'vue panoramique', 'gastronomique'],
      ),
      Place(
        id: 'p131',
        name: 'L\'Oiseau Blanc - Peninsula',
        type: PlaceType.rooftop,
        latitude: 48.8686,
        longitude: 2.2964,
        address: '19 Avenue Kleber, 75016 Paris',
        rating: 4.7,
        reviewCount: 2400,
        priceLevel: 4,
        ambianceTags: ['chic', 'romantique', 'business'],
        musicTags: ['lounge'],
        styleTags: ['rooftop', 'vue Tour Eiffel', 'gastronomique', 'palace'],
        isPremium: true,
      ),
      Place(
        id: 'p132',
        name: 'Ciel de Paris - Tour Montparnasse',
        type: PlaceType.rooftop,
        latitude: 48.8419,
        longitude: 2.3219,
        address: '33 Avenue du Maine, 75015 Paris',
        rating: 4.2,
        reviewCount: 9600,
        priceLevel: 3,
        ambianceTags: ['chic', 'romantique', 'animé'],
        musicTags: ['lounge'],
        styleTags: ['rooftop', 'vue panoramique', 'gastronomique'],
      ),
      Place(
        id: 'p133',
        name: 'Rooftop du Printemps Haussmann',
        type: PlaceType.rooftop,
        latitude: 48.8738,
        longitude: 2.3316,
        address: '64 Boulevard Haussmann, 75009 Paris',
        rating: 4.3,
        reviewCount: 18000,
        priceLevel: 1,
        ambianceTags: ['animé', 'décontracté', 'familial'],
        musicTags: [],
        styleTags: ['rooftop', 'vue panoramique', 'vue Tour Eiffel', 'gratuit'],
      ),
      Place(
        id: 'p134',
        name: 'La Samaritaine Rooftop',
        type: PlaceType.rooftop,
        latitude: 48.8607,
        longitude: 2.3452,
        address: '9 Rue de la Monnaie, 75001 Paris',
        rating: 4.4,
        reviewCount: 2100,
        priceLevel: 3,
        ambianceTags: ['chic', 'branché', 'romantique'],
        musicTags: ['lounge', 'house'],
        styleTags: ['rooftop', 'vue panoramique', 'cocktails'],
        isPremium: true,
      ),

      // ===================== PARCS =====================
      Place(
        id: 'p135',
        name: 'Jardin du Luxembourg',
        type: PlaceType.parc,
        latitude: 48.8462,
        longitude: 2.3372,
        address: 'Rue de Medicis, 75006 Paris',
        rating: 4.8,
        reviewCount: 45000,
        priceLevel: 1,
        ambianceTags: ['calme', 'romantique', 'familial'],
        musicTags: [],
        styleTags: ['jardin', 'pelouse', 'pique-nique', 'gratuit'],
      ),
      Place(
        id: 'p136',
        name: 'Parc des Buttes-Chaumont',
        type: PlaceType.parc,
        latitude: 48.8798,
        longitude: 2.3816,
        address: '1 Rue Botzaris, 75019 Paris',
        rating: 4.7,
        reviewCount: 38000,
        priceLevel: 1,
        ambianceTags: ['calme', 'romantique', 'familial'],
        musicTags: [],
        styleTags: ['nature', 'pelouse', 'pique-nique', 'vue panoramique', 'gratuit'],
        isPremium: true,
      ),
      Place(
        id: 'p137',
        name: 'Jardin des Tuileries',
        type: PlaceType.parc,
        latitude: 48.8638,
        longitude: 2.3274,
        address: 'Place de la Concorde, 75001 Paris',
        rating: 4.5,
        reviewCount: 52000,
        priceLevel: 1,
        ambianceTags: ['animé', 'romantique', 'familial'],
        musicTags: [],
        styleTags: ['jardin', 'pelouse', 'pique-nique', 'vue Tour Eiffel', 'gratuit'],
      ),
      Place(
        id: 'p138',
        name: 'Parc de Belleville',
        type: PlaceType.parc,
        latitude: 48.8690,
        longitude: 2.3877,
        address: '47 Rue des Couronnes, 75020 Paris',
        rating: 4.5,
        reviewCount: 12000,
        priceLevel: 1,
        ambianceTags: ['décontracté', 'familial', 'animé'],
        musicTags: [],
        styleTags: ['vue panoramique', 'pelouse', 'pique-nique', 'gratuit'],
      ),
      Place(
        id: 'p139',
        name: 'Promenade Plantee',
        type: PlaceType.parc,
        latitude: 48.8476,
        longitude: 2.3712,
        address: '1 Coulee Verte Rene-Dumont, 75012 Paris',
        rating: 4.5,
        reviewCount: 8500,
        priceLevel: 1,
        ambianceTags: ['calme', 'romantique', 'insolite'],
        musicTags: [],
        styleTags: ['nature', 'jardin', 'pique-nique', 'gratuit', 'instagrammable'],
      ),
      Place(
        id: 'p140',
        name: 'Parc Monceau',
        type: PlaceType.parc,
        latitude: 48.8797,
        longitude: 2.3096,
        address: '35 Boulevard de Courcelles, 75008 Paris',
        rating: 4.6,
        reviewCount: 22000,
        priceLevel: 1,
        ambianceTags: ['calme', 'chic', 'romantique'],
        musicTags: [],
        styleTags: ['jardin', 'pelouse', 'pique-nique', 'gratuit'],
      ),
      Place(
        id: 'p141',
        name: 'Jardin des Plantes',
        type: PlaceType.parc,
        latitude: 48.8447,
        longitude: 2.3598,
        address: '57 Rue Cuvier, 75005 Paris',
        rating: 4.4,
        reviewCount: 18000,
        priceLevel: 2,
        ambianceTags: ['calme', 'familial', 'décontracté'],
        musicTags: [],
        styleTags: ['nature', 'jardin', 'pique-nique'],
      ),
      Place(
        id: 'p142',
        name: 'Parc de la Villette',
        type: PlaceType.parc,
        latitude: 48.8940,
        longitude: 2.3933,
        address: '211 Avenue Jean Jaures, 75019 Paris',
        rating: 4.5,
        reviewCount: 35000,
        priceLevel: 1,
        ambianceTags: ['animé', 'familial', 'décontracté'],
        musicTags: [],
        styleTags: ['nature', 'pelouse', 'pique-nique', 'gratuit'],
      ),
      Place(
        id: 'p143',
        name: 'Square des Batignolles',
        type: PlaceType.parc,
        latitude: 48.8863,
        longitude: 2.3189,
        address: 'Rue Cardinet, 75017 Paris',
        rating: 4.3,
        reviewCount: 4500,
        priceLevel: 1,
        ambianceTags: ['calme', 'familial', 'décontracté'],
        musicTags: [],
        styleTags: ['nature', 'pelouse', 'pique-nique', 'gratuit'],
      ),
      Place(
        id: 'p144',
        name: 'Bois de Vincennes',
        type: PlaceType.parc,
        latitude: 48.8344,
        longitude: 2.4339,
        address: 'Route de la Pyramide, 75012 Paris',
        rating: 4.5,
        reviewCount: 28000,
        priceLevel: 1,
        ambianceTags: ['calme', 'familial', 'décontracté'],
        musicTags: [],
        styleTags: ['nature', 'pelouse', 'pique-nique', 'gratuit'],
      ),

      // ===================== ADRESSES & SPOTS PHOTO =====================
      Place(
        id: 'p145',
        name: 'Rue de Cremieux',
        type: PlaceType.adresse,
        latitude: 48.8474,
        longitude: 2.3688,
        address: 'Rue de Cremieux, 75012 Paris',
        rating: 4.6,
        reviewCount: 15000,
        priceLevel: 1,
        ambianceTags: ['insolite', 'romantique', 'animé'],
        musicTags: [],
        styleTags: ['instagrammable', 'gratuit'],
      ),
      Place(
        id: 'p146',
        name: 'Rue Montorgueil',
        type: PlaceType.adresse,
        latitude: 48.8633,
        longitude: 2.3474,
        address: 'Rue Montorgueil, 75002 Paris',
        rating: 4.5,
        reviewCount: 35000,
        priceLevel: 1,
        ambianceTags: ['animé', 'familial', 'décontracté'],
        musicTags: [],
        styleTags: ['marché', 'gratuit', 'instagrammable'],
      ),
      Place(
        id: 'p147',
        name: 'Passage des Panoramas',
        type: PlaceType.adresse,
        latitude: 48.8706,
        longitude: 2.3447,
        address: '11 Boulevard Montmartre, 75002 Paris',
        rating: 4.5,
        reviewCount: 12000,
        priceLevel: 1,
        ambianceTags: ['insolite', 'romantique', 'cosy'],
        musicTags: [],
        styleTags: ['galerie couverte', 'instagrammable', 'gratuit'],
      ),
      Place(
        id: 'p148',
        name: 'Rue Denoyez',
        type: PlaceType.adresse,
        latitude: 48.8732,
        longitude: 2.3850,
        address: 'Rue Denoyez, 75020 Paris',
        rating: 4.3,
        reviewCount: 8000,
        priceLevel: 1,
        ambianceTags: ['insolite', 'branché', 'décontracté'],
        musicTags: [],
        styleTags: ['street art', 'instagrammable', 'gratuit'],
      ),
      Place(
        id: 'p149',
        name: 'Passage Jouffroy',
        type: PlaceType.adresse,
        latitude: 48.8727,
        longitude: 2.3461,
        address: '10 Boulevard Montmartre, 75009 Paris',
        rating: 4.5,
        reviewCount: 8500,
        priceLevel: 1,
        ambianceTags: ['insolite', 'cosy', 'romantique'],
        musicTags: [],
        styleTags: ['galerie couverte', 'instagrammable', 'gratuit'],
      ),
      Place(
        id: 'p150',
        name: 'Marche d\'Aligre',
        type: PlaceType.adresse,
        latitude: 48.8497,
        longitude: 2.3740,
        address: 'Place d\'Aligre, 75012 Paris',
        rating: 4.6,
        reviewCount: 18000,
        priceLevel: 1,
        ambianceTags: ['animé', 'familial', 'décontracté'],
        musicTags: [],
        styleTags: ['marché', 'gratuit'],
      ),
      Place(
        id: 'p151',
        name: 'Rue des Martyrs',
        type: PlaceType.adresse,
        latitude: 48.8793,
        longitude: 2.3404,
        address: 'Rue des Martyrs, 75009 Paris',
        rating: 4.4,
        reviewCount: 22000,
        priceLevel: 1,
        ambianceTags: ['animé', 'décontracté', 'familial'],
        musicTags: [],
        styleTags: ['marché', 'gastronomique', 'gratuit'],
      ),
      Place(
        id: 'p152',
        name: 'Galerie Vivienne',
        type: PlaceType.adresse,
        latitude: 48.8648,
        longitude: 2.3381,
        address: '4 Rue des Petits Champs, 75002 Paris',
        rating: 4.6,
        reviewCount: 10000,
        priceLevel: 1,
        ambianceTags: ['chic', 'romantique', 'insolite'],
        musicTags: [],
        styleTags: ['galerie couverte', 'instagrammable', 'gratuit'],
      ),
      Place(
        id: 'p153',
        name: 'Canal Saint-Martin',
        type: PlaceType.adresse,
        latitude: 48.8720,
        longitude: 2.3635,
        address: 'Quai de Valmy, 75010 Paris',
        rating: 4.6,
        reviewCount: 32000,
        priceLevel: 1,
        ambianceTags: ['romantique', 'décontracté', 'animé'],
        musicTags: [],
        styleTags: ['instagrammable', 'pique-nique', 'gratuit'],
      ),
    ].map(_withMockMedia).toList();
  }

  /// Enrichit chaque lieu (medias + donnees derivees pour les filtres avances).
  ///
  /// >>> POINT DE BRANCHEMENT BACKEND <<<
  /// Le prix reel, la frequentation et les horaires d'affluence sont ici
  /// DERIVES de façon deterministe a partir du type/prix/tags (heuristiques
  /// de demo). Quand un backend sera branche, ces valeurs viendront de vraies
  /// donnees (ex: Google Popular Times, tickets moyens, etc.).
  Place _withMockMedia(Place p) {
    final ambiance = [...p.ambianceTags];
    // "calme" : intimiste/cosy sans cote festif/anime.
    if ((ambiance.contains('intimiste') || ambiance.contains('cosy')) &&
        !ambiance.contains('festif') &&
        !ambiance.contains('animé')) {
      ambiance.add('calme');
    }

    final style = [...p.styleTags];
    // "luxueux" : haut de gamme (prix 4, palace ou premium).
    if (p.priceLevel >= 4 || style.contains('palace') || p.isPremium) {
      if (!style.contains('luxueux')) style.add('luxueux');
    }

    // Lien Google Maps REEL (recherche par nom + adresse) : ouvre la vraie
    // fiche du lieu avec ses avis reels, photos et itineraire.
    final mapsUrl = 'https://www.google.com/maps/search/?api=1&query='
        '${Uri.encodeComponent('${p.name} ${p.address}')}';
    // Hashtag Instagram (best-effort a partir du nom).
    final slug = p.name
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9]'), '');
    final instagramUrl = 'https://www.instagram.com/explore/tags/$slug/';

    return Place(
      id: p.id,
      name: p.name,
      type: p.type,
      latitude: p.latitude,
      longitude: p.longitude,
      address: p.address,
      rating: p.rating,
      reviewCount: p.reviewCount,
      priceLevel: p.priceLevel,
      ambianceTags: ambiance,
      musicTags: p.musicTags,
      styleTags: style,
      photos: _photosForPlace(p.id),
      videos: const [],
      isPremium: p.isPremium,
      averagePrice: _averagePrice(p),
      crowdTags: _crowd(p),
      peakTags: _peak(p),
      mapsUrl: mapsUrl,
      instagramUrl: instagramUrl,
      // websiteUrl laisse a null : on ne fabrique pas de faux site.
      // Extraits "Instagram" : utilise _igVideos[id] si rempli, sinon demo.
      instagramVideos: _igVideosForPlace(p.id),
      // Nos interviews maison : rempli via _originalVideosMap si disponible.
      originalVideos: _originalVideosForPlace(p.id),
      // Extraits d'avis Google : specifiques si disponibles, sinon generes.
      reviews: _reviewSamples[p.id] ?? _generateReviews(p),
    );
  }

  /// Prix moyen reel (€) derive du type et du niveau de prix, avec variation.
  int _averagePrice(Place p) {
    const barTiers = [15, 25, 45, 70];
    const restoTiers = [20, 35, 60, 110];
    const hotelTiers = [90, 150, 250, 430];
    const rooftopTiers = [15, 25, 45, 70];
    const parcTiers = [0, 5, 12, 20];
    const adresseTiers = [0, 0, 0, 0];
    final tiers = switch (p.type) {
      PlaceType.bar => barTiers,
      PlaceType.restaurant => restoTiers,
      PlaceType.hotel => hotelTiers,
      PlaceType.rooftop => rooftopTiers,
      PlaceType.parc => parcTiers,
      PlaceType.adresse => adresseTiers,
    };
    final base = tiers[(p.priceLevel - 1).clamp(0, 3)];
    if (base == 0) return 0;
    final jitter = p.id.hashCode.abs() % 11; // 0..10
    return base + jitter;
  }

  /// Frequentation type derivee de l'ambiance / du style.
  List<String> _crowd(Place p) {
    final s = <String>{};
    final a = p.ambianceTags;
    final st = p.styleTags;
    if (st.contains('club') || a.contains('festif') || a.contains('animé')) {
      s.addAll(['20-30 ans', 'étudiants']);
    }
    if (a.contains('business') ||
        st.contains('gastronomique') ||
        st.contains('palace')) {
      s.add('business');
    }
    if (st.contains('vue Tour Eiffel') ||
        st.contains('palace') ||
        st.contains('rooftop') ||
        p.isPremium) {
      s.add('touristes');
    }
    if (a.contains('familial')) s.add('familles');
    if (a.contains('cosy') ||
        a.contains('intimiste') ||
        st.contains('bistrot') ||
        st.contains('vins nature')) {
      s.add('locaux');
    }
    if (st.contains('cocktails') ||
        a.contains('branché') ||
        a.contains('chic')) {
      s.addAll(['after-work', '30-45 ans']);
    }
    // Parcs et adresses : toujours familles + locaux par défaut.
    if (p.type == PlaceType.parc || p.type == PlaceType.adresse) {
      s.add('familles');
      if (p.rating >= 4.5 ||
          p.styleTags.contains('vue Tour Eiffel') ||
          p.styleTags.contains('instagrammable')) {
        s.add('touristes');
      }
    }
    if (s.isEmpty) s.add('locaux');
    return s.toList();
  }

  /// Creneaux d'affluence derives du type et du style.
  List<String> _peak(Place p) {
    final s = <String>{};
    switch (p.type) {
      case PlaceType.bar:
        s.addAll(['after-work', 'soir', 'week-end']);
        if (p.styleTags.contains('club') || p.ambianceTags.contains('festif')) {
          s.add('nuit');
        }
        break;
      case PlaceType.restaurant:
        s.addAll(['midi', 'soir']);
        if (p.styleTags.contains('brunch')) s.addAll(['matin', 'week-end']);
        break;
      case PlaceType.hotel:
        s.addAll(['soir', 'nuit', 'week-end']);
        break;
      case PlaceType.rooftop:
        s.addAll(['after-work', 'soir', 'week-end']);
        if (p.ambianceTags.contains('festif')) s.add('nuit');
        break;
      case PlaceType.parc:
        s.addAll(['matin', 'après-midi', 'week-end']);
        if (p.ambianceTags.contains('animé')) s.add('soir');
        break;
      case PlaceType.adresse:
        s.addAll(['matin', 'après-midi', 'week-end']);
        break;
    }
    if (p.styleTags.contains('terrasse') || p.styleTags.contains('jardin')) {
      s.add('après-midi');
    }
    return s.toList();
  }

  // ---- Génération d'avis Google pour les lieux sans entrée dans _reviewSamples ----

  static const _reviewAuthors = [
    'Sophie M.', 'Thomas L.', 'Julie B.', 'Kevin R.', 'Lea H.',
    'Marc D.', 'Chloe P.', 'Antoine D.', 'Noemie C.', 'Pierre V.',
    'Margot S.', 'Romain F.', 'Sarah N.', 'Julien K.', 'Emma R.',
    'Lucas P.', 'Ines T.', 'Baptiste M.', 'Amandine D.', 'Thibault R.',
  ];
  static const _reviewTimes = [
    'il y a 4 jours', 'il y a 1 semaine', 'il y a 2 semaines',
    'il y a 3 semaines', 'il y a 1 mois', 'il y a 6 semaines',
    'il y a 2 mois', 'il y a 3 mois', 'il y a 4 mois', 'il y a 5 mois',
  ];
  static const _reviewRatings = [5.0, 4.0, 5.0, 5.0, 4.0];

  static List<String> _textsForType(PlaceType type) {
    switch (type) {
      case PlaceType.bar:
        return [
          'Super ambiance et cocktails au top. On y retourne sans hesiter !',
          'Endroit tres sympa, staff accueillant. Ideal pour un apero branché.',
          "L'un des meilleurs bars du quartier. Cocktails creatifs et delicieux.",
          'Cadre chaleureux, service rapide et ambiance au rendez-vous. Tres bonne adresse.',
          "Coup de coeur ! Belle carte de cocktails et atmosphere unique. A recommander.",
          'Bar tres agreable, bon rapport qualite-prix. Le personnel est adorable.',
          "Endroit incontournable du quartier. Cocktails inventifs et decor soigne.",
          'Tres bonne soiree, musique parfaite et service aux petits soins.',
        ];
      case PlaceType.restaurant:
        return [
          'Excellent rapport qualite-prix, cuisine savoureuse et service attentionne.',
          "Un vrai regal ! Chaque plat est soigne, l'ambiance est parfaite.",
          'Super resto, portions genereuses et qualite au rendez-vous. On reviendra !',
          'Service impeccable et cuisine delicieuse. Une des meilleures tables du quartier.',
          'Tres bonne experience, produits frais et chef talentueux. A tester absolument.',
          'Cadre agreable et plats savoureux. Le service est rapide et souriant.',
          'Restaurant exceptionnel, carte variee et prix raisonnables. Coup de coeur !',
          'Tres bonne adresse, ambiance chaleureuse et cuisine de qualite. On recommande.',
        ];
      case PlaceType.hotel:
        return [
          'Hotel magnifique, chambre confortable et personnel tres accueillant.',
          'Sejour parfait, emplacement ideal et standing irreprochable. On recommande.',
          'Excellent hotel, service impeccable et cadre exceptionnel. Une vraie reussite.',
          'Tres bel etablissement, proprete parfaite et petit-dejeuner delicieux.',
          'Hotel au top ! Vue magnifique, chambre spacieuse et staff aux petits soins.',
          'Cadre luxueux et service de qualite. Chambre bien agencee et tres propre.',
          'Hotel ideal pour un sejour a Paris. Situation parfaite et accueil chaleureux.',
          'Sejour inoubliable dans cet hotel. Design soigne et confort exceptionnel.',
        ];
      case PlaceType.rooftop:
        return [
          "Vue a couper le souffle ! Cocktails excellents et ambiance magique.",
          'Panorama splendide sur Paris. Parfait au coucher du soleil, incontournable.',
          'Rooftop exceptionnel, vue panoramique et cocktails au top. A faire !',
          'Experience unique avec vue imprenable. Service sympa et ambiance festive.',
          'Le meilleur rooftop du quartier. Vue magnifique et staff accueillant.',
          "Soiree parfaite avec vue exceptionnelle sur les toits de Paris.",
          'Endroit magique au coucher du soleil. Cocktails creatifs et ambiance au top.',
          'Vue panoramique a 360 degres. On y retourne des que possible !',
        ];
      case PlaceType.parc:
        return [
          'Endroit magnifique pour se ressourcer. Parfait pour un pique-nique.',
          'Oasis de verdure au coeur de Paris. Calme et tres agreable en toute saison.',
          'Beau parc, bien entretenu et spacieux. Ideal pour une balade ou se detendre.',
          "Un de mes parcs favoris a Paris. Paysages sublimes et ambiance sereine.",
          "Super endroit pour s'evader du bruit de la ville. Tres bien entretenu.",
          'Parc magnifique, ideal pour le sport ou la detente. Toujours agreable.',
          'Verdure superbe et atmosphere apaisante. Lieu de promenade ideal.',
          'Cadre naturel exceptionnel en plein Paris. Parfait pour se ressourcer.',
        ];
      case PlaceType.adresse:
        return [
          'Endroit incroyable et tres photogenique. A visiter absolument !',
          "Lieu magique plein de charme et d'histoire. On s'y attarde volontiers.",
          'Spot magnifique, vraiment unique a Paris. Les photos ne rendent pas justice.',
          'Lieu incontournable, atmosphere particuliere et cadre exceptionnel.',
          "Super decouverte ! Endroit authentique et hors des sentiers battus.",
          'Adresse charmante que tout le monde devrait connaitre a Paris.',
          'Lieu unique qui merite vraiment le detour. Atmosphere magique garantie.',
          'Endroit authentique et plein de charme. Une belle decouverte parisienne.',
        ];
    }
  }

  static List<Review> _generateReviews(Place p) {
    final hash = p.id.hashCode.abs();
    final texts = _textsForType(p.type);
    return [
      for (var i = 0; i < 5; i++)
        Review(
          author: _reviewAuthors[(hash + i * 7) % _reviewAuthors.length],
          rating: _reviewRatings[i % _reviewRatings.length],
          text: texts[(hash + i * 3) % texts.length],
          relativeTime: _reviewTimes[(hash + i * 11) % _reviewTimes.length],
        ),
    ];
  }

  // ---- Styles de collection mock ----
  List<CollectionStyle> getStyles() {
    return const [
      CollectionStyle(
        id: 's1',
        name: 'Nightlife Chic',
        primaryColor: Color(0xFF6C5CE7),
        iconStyle: 'bold',
        description: 'Rooftops, speakeasies et cocktails haut de gamme.',
      ),
      CollectionStyle(
        id: 's2',
        name: 'Rooftop Chill',
        primaryColor: Color(0xFF74B9FF),
        iconStyle: 'minimal',
        description: 'Vues degagees, terrasses et ambiances detendues.',
      ),
      CollectionStyle(
        id: 's3',
        name: 'Hidden Gems',
        primaryColor: Color(0xFF1E5631),
        iconStyle: 'outline',
        description: 'Adresses confidentielles loin des foules.',
      ),
    ];
  }

  /// Cartes publiques d'influenceurs (accessibles via un code).
  /// Ce sont des collections riches (> 10 lieux), stylees, verifiees.
  List<UserCollection> getInfluencerCollections() {
    final places = getPlaces();
    return [
      UserCollection(
        id: 'inf1',
        ownerName: 'Lea Martin',
        authorHandle: '@lea.inparis',
        isInfluencer: true,
        coverImage: 'https://picsum.photos/seed/leacover/900/450',
        code: 'LEA-PARIS-2024',
        style: const CollectionStyle(
          id: 'infs1',
          name: 'Lea a Paris',
          primaryColor: Color(0xFFE84393),
          iconStyle: 'bold',
          description: 'Mes adresses prefereees a Paris - rooftops, brunchs & spots photo.',
        ),
        places: places
            .where((p) =>
                p.styleTags.contains('rooftop') ||
                p.styleTags.contains('brunch') ||
                p.ambianceTags.contains('branché'))
            .take(14)
            .toList(),
      ),
      UserCollection(
        id: 'inf2',
        ownerName: 'Marco Rossi',
        authorHandle: '@chefmarco',
        isInfluencer: true,
        coverImage: 'https://picsum.photos/seed/marcocover/900/450',
        code: 'MARCO-EATS-7788',
        style: const CollectionStyle(
          id: 'infs2',
          name: "Marco's Food Map",
          primaryColor: Color(0xFFB71C1C),
          iconStyle: 'outline',
          description: 'The best restaurants in Paris, picked by a chef.',
        ),
        places:
            places.where((p) => p.type == PlaceType.restaurant).take(13).toList(),
      ),
    ];
  }

  /// Collections appartenant a l'utilisateur courant (mock).
  List<UserCollection> getUserCollections() {
    final places = getPlaces();
    final styles = getStyles();
    return [
      UserCollection(
        id: 'c1',
        ownerName: 'Alex',
        code: 'PARIS-CHIC-1234',
        style: styles[0],
        places: places.where((p) => p.type == PlaceType.bar).take(5).toList(),
      ),
      UserCollection(
        id: 'c2',
        ownerName: 'Alex',
        code: 'ROOFTOP-COOL-5678',
        style: styles[1],
        places: places
            .where((p) => p.styleTags.contains('rooftop'))
            .take(5)
            .toList(),
      ),
    ];
  }
}
